hiero-ledger/hiero-json-rpc-relay

packages/relay/src/lib/eth.ts
packages/relay/src/lib/mirrorNode.ts
packages/relay/src/lib/model.ts

Closes #64 
With this change metamask now properly received gasPrice and is able to estimate gas in hbar

metamask properly estimating gas

---

README.md

Clarify that docker compose is intended for development purposes only
Fixes #78 
**Checklist**

Clarify development purpose of docker compose

---

packages/relay/src/index.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/mirrorNode.ts
packages/relay/src/lib/net.ts
packages/relay/src/lib/relay.ts
packages/server/src/server.ts

* Support reward percentages for FeeHistory
* re-jigger chain_id detection, drive from network if not hard wired
* prettier reformatting

Chain ID and FeeHistory Tweaks

---

.github/workflows/release-production.yml
docker-compose.yml
helm-chart/Chart.yaml
helm-chart/values.yaml
packages/relay/package.json
packages/server/package.json

- Bump version to 0.1.0-rc1
- Add Production github action to support release tags
Fixes #145 
**Checklist**

Bump version to 0.1.0-rc1

---

.github/workflows/release-production.yml
helm-chart/Chart.yaml
helm-chart/values.yaml
packages/relay/package.json
packages/server/package.json

Bump version
- Bump version to 0.2.0-SNAPSHOT
- Add production release github action
Fixes #146 
**Checklist**

Bump version to 0.2.0-SNAPSHOT

---

README.md
packages/server/tests/postman.json

Closes #77 
Adds postman tests mirroring existing tests.
Signed-off-by: Mitchell Martin <mitch@swirldslabs.com>

add postman tests

---

.github/workflows/release-production.yml

I missed artifact creation in the initial PR
- Add npm project artifact for additional dev testing option
Fixes #148 
**Checklist**

Add artifact build and upload logic to release logic

---

packages/server/tests/acceptance.spec.ts
packages/server/tests/utils.ts

Fixes #
https://github.com/hashgraph/hedera-json-rpc-relay/issues/164
**Checklist**

Signed transaction generator

---

packages/relay/src/lib/eth.ts
packages/server/tests/acceptance.spec.ts

Signed-off-by: Daniel Ivanov <daniel.k.ivanov95@gmail.com>
Fixes #
**Checklist**

Feat: Add more unsupported acceptance tests

---

packages/server/tests/acceptance.spec.ts

Update the docker image versions:
- `NETWORK_NODE_IMAGE_TAG: 0.26.2`
- `HAVEGED_IMAGE_TAG: 0.26.2`
- `MIRROR_IMAGE_TAG: 0.58.0`
Fixes #200 
**Checklist**

Fix acceptance test timeout issue

---

packages/server/tests/acceptance.spec.ts
packages/server/tests/utils.ts

Fixes #183 
Fixes #197 
**Checklist**

Refactor Acceptance tests to use ethers.provider

---

README.md

Signed-off-by: Mitchell Martin <mitch@swirldslabs.com>
Correct Readme organization
Fixes #195

Correct README Organization, Postman placed incorrectly

---

package-lock.json
packages/relay/package.json
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

Expand mirror node network fees fallback to encompass all errors
- Add warning log
- Expand test integration capabilities using `sinon`
- Add `eth.spec.ts` coverage for mirror node failures for gas endpoints
Fixes #239 
Locally pointed against testnet backends to confirm fix
**Checklist**

Handle Mirror Node network fee errors

---

helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.3.0-SNAPSHOT
Fixes #247 
**Checklist**

Bump v0.3.0-SNAPSHOT

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.2.0-rc1
Fixes #245 
**Checklist**

Bump v0.2.0-rc1

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.2.0-rc2
Fixes #
**Checklist**

Bump v0.2.0-rc2

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.2.0rc3
Fixes #
**Checklist**

Bump v0.2.0rc3

---

dapp-example/tests/support/bootstrap.js

Expand DApp SDK client to support non local envs
Fixes #274 
**Checklist**

Expand DApp SDK client to support non local envs

---

packages/relay/package.json
packages/relay/src/lib/clients/mirrorNodeClient.ts

Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/203
**Checklist**

Add retry logic to MirrorNodeClient calls

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.2.0
Fixes #
**Checklist**

Bump v0.2.0

---

dapp-example/src/App.js
dapp-example/tests/e2e/index.spec.js
dapp-example/tests/support/bootstrap.js
package-lock.json
packages/relay/src/lib/clients/mirrorNodeClient.ts

Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>
- Update `bootstrap.js` script to wait for the creation of an EVM account
- Remove mirror node retry logic - slowing down the usability of the DApp(Relay)
- Improve integration tests
Fixes #284  #285
**Checklist**

DApp tests not working on public networks

---

packages/server/tests/acceptance/rpc.spec.ts

Add `eth_call` coverage to acceptance tests
Fixes #218 
**Checklist**

eth_call acceptance tests

---

.github/workflows/release-production.yml
docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

- Bump 0.3.0-rc1
- add version to npm package artifact
Fixes #
**Checklist**

Bump 0.3.0-rc1

---

package.json

Docker  service instance of the relay is sometimes held up by 
```
Need to install the following packages: lerna
```
- Add lerna to dependency to support complete docker build and release
Fixes #181 
**Checklist**

Add lerna to dependency to support complete docker build and release

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/acceptance/rpc.spec.ts

Update eth_getLogs to utilize index across block transactions
Fixes #303 
**Checklist**

Update eth_getLogs to utilize index across block transactions

---

package.json

Cherry pick #318 to release 0.3
Fixes #181 
**Checklist**

Add lerna to dependency to support complete docker build and release (0.3)

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.3.0-rc2
Includes
- lerna fix
- logs index fix
Fixes #
**Checklist**

Bump 0.3.0-rc2

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/216
**Checklist**

Add cache logic to capture static INVALID entity transaction failures

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.3.0-rc3
Fixes #
**Checklist**

Bump 0.3.0-rc3

---

packages/relay/src/lib/errors.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/precheck.ts
packages/relay/tests/lib/precheck.spec.ts

Fixes #
- https://github.com/hashgraph/hedera-json-rpc-relay/issues/342
**Checklist**

Add precheck for empty data and value less than one tinybar

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.4.0-rc1
Fixes #
**Checklist**

Bump 0.4.0-rc1

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/helpers/assertions.ts

Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/338
**Checklist**

Align transaction with ethereum execution apis

---

packages/relay/src/lib/eth.ts
packages/relay/src/lib/precheck.ts
packages/relay/tests/lib/precheck.spec.ts

Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/349
**Checklist**

Optimize parse transaction on prechecks

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.4.0 version
Fixes #
**Checklist**

Bump 0.4.0 version

---

docker-compose.yml
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.4.1
Fixes #
**Checklist**

Bump 0.4.1

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.6.0-snapshot
Fixes #
**Checklist**

Bump 0.6.0-snapshot

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.5.0-rc1
Fixes #
**Checklist**

Bump 0.5.0-rc1

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.5.0
Fixes #
**Checklist**

Bump v0.5.0

---

README.md
docs/rpc-api.md
packages/server/tests/postman.json

- Add useful badges to README
- Build actions
- Latest Version
- RPC API Doc link
- Discord link
- Made with typescript
- License
- Enhance newman `eth_getBlockByNumber` test with `lastest` tag
- Add `eth_getBlockTransactionCountByNumber` test to newman tests
Fixes #421 
**Checklist**

Enhance README and newman coverage

---

tools/truffle-example/README.md

Add truffle readme.md

---

tools/README.md
tools/web3js-example/README.md

Add web3js readme.md

---

packages/relay/src/formatters.ts
packages/relay/src/index.ts
packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/constants.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/precheck.ts
packages/server/src/server.ts

Added a request id that follows activity through the stack.
Fixes #238 
``` 
[2022-08-09 06:55:27.204 +0000] DEBUG (rpc-server/65064 on Georgis-MacBook-Pro-3.local): [Request ID: f61ff7bb-d6ea-40a3-b6d9-185b3b5ff60f] eth_getTransactionReceipt
[2022-08-09 06:55:27.204 +0000] TRACE (relay-eth/65064 on Georgis-MacBook-Pro-3.local): [Request ID: f61ff7bb-d6ea-40a3-b6d9-185b3b5ff60f] getTransactionReceipt(0xbe547272e48ffc1c0ee2d54c98f6ff4243e6f4e1b53c1872652f452cf2a77e4a)
[2022-08-09 06:55:27.226 +0000] DEBUG (mirror-node/65064 on Georgis-MacBook-Pro-3.local): [Request ID: f61ff7bb-d6ea-40a3-b6d9-185b3b5ff60f] [GET] contracts/results/0xbe547272e48ffc1c0ee2d54c98f6ff4243e6f4e1b53c1872652f452cf2a77e4a 200 22 ms
[2022-08-09 …
```

Add trace id to logs

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.7.0-snapshot
Fixes #
**Checklist**

Bump 0.7.0-snapshot

---

packages/relay/src/lib/precheck.ts
packages/relay/tests/lib/precheck.spec.ts
packages/server/tests/acceptance/erc20.spec.ts
packages/server/tests/acceptance/htsPrecompile.spec.ts
packages/server/tests/acceptance/rpc.spec.ts
packages/server/tests/clients/servicesClient.ts

- Add logic to check for a valid account returned from mirror node
- Return resource not found on 404
- Add log in acceptance test to show expected evm address
Fixes #446 
**Checklist**

Add check for valid account in balance precheck

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
package.json
packages/relay/package.json
packages/server/package.json
packages/server/tests/postman.json

Bump 0.6.0
Fixes #
**Checklist**

Bump 0.6.0

---

tools/README.md

Describe the invalid precomputed address issue in the tools readme

---

k6/README.md
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/server/tests/postman.json

Fix postman eth_getBalance test
- Update to get balance on `0.0.98` account
Additional misc fixes
- Fix `eth_call` log
- Add `callerName` to query log
- Fix k6 README
Fixes #465 
**Checklist**

Fix postman eth_getBalance test & misc edits

---

package-lock.json
packages/relay/package.json
packages/server/package.json

Bump sdk to v2.18.0
Fixes #469 
**Checklist**

Bump sdk to v2.18.0

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.8.0-snapshot
Fixes #
**Checklist**

Bump 0.8.0-snapshot

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.7.0-rc1
Fixes #
**Checklist**

Bump 0.7.0-rc1

---

helm-chart/environments/minikube.yaml
helm-chart/templates/cronjob.yaml
helm-chart/templates/role.yaml
helm-chart/templates/rolebinding.yaml
helm-chart/templates/serviceaccount.yaml
helm-chart/values.yaml

Signed-off-by: Matt Halder <rustyShacklefurd@users.noreply.github.com>
This PR adds the ability to enable or disable a rolling restart of the hedera-json-rpc-relay deployment
**Checklist**

Rolling restarts done via cronjob

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.7.0
Fixes #
**Checklist**

Bump 0.7.0

---

dapp-example/tests/support/bootstrap.js
packages/server/tests/acceptance/htsPrecompile.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/helpers/prerequisite.ts

- Bump mirror 0.64.0
- Fix dapp example bootstrap string check
- enable tests waiting on new versions
Fixes #483 
Should unblock all but 1 of the draft acceptance test PRs 
**Checklist**

Bump mirror 0.64.0 and misc test setup fixes

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0 9 0 snapshot
Fixes #
**Checklist**

Bump 0-9-0 snapshot

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.8.0-rc1
Fixes #
**Checklist**

Bump version to 0.8.0-rc1

---

packages/relay/src/lib/errors/JsonRpcError.ts
packages/server/tests/acceptance/rpc.spec.ts

Rate limit test workaround
Fixes #547 
**Checklist**

Rate limit test workaround

---

packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/precheck.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/precheck.spec.ts

nonce precheck logic is currently missing some logic and logs
- add log to show nonce value to help better inform `WRONG_NONCE` errors observed
- Update `RESOURCE_NOT_FOUND` error to allow for resource details
- Add nonce precheck test cases for better coverage
- break out account check from nonce check
- add account check tests cases
- simplify nonce precheck logic
- clean up orphaned references observed
Fixes #534 
Let me know if the high nonce might be too risky to do
**Checklist**

update nonce precheck logic

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.8.0
Fixes #
**Checklist**

Bump 0.8.0

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.10.0-snapshot
Fixes #
**Checklist**

Bump 0.10.0-snapshot

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.9.0-rc1
Fixes #
**Checklist**

Bump 0.9.0-rc1

---

package-lock.json
packages/relay/package.json
packages/relay/src/lib/clients/sdkClient.ts
packages/server/package.json

Cherry pick #593 
Add TransactionRecordQuery calls to capture fail transaction costs
- update executeTransaction catch with TransactionRecordQuery logic
- update executeGetTransactionRecord catch with TransactionRecordQuery logic
Addresses #592 
**Checklist**

Add TransactionRecordQuery calls to capture failed transaction costs (0.9)

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.9.0-rc2
Fixes #
**Checklist**

Bump 0.9.0-rc2

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.9.0
Fixes #
**Checklist**

Bump 0.9.0

---

tools/subgraph-example/README.md
tools/subgraph-example/docker-compose.yml

Updates the subgraph example readme
Fixes #
**Checklist**

Update subgraph example docs

---

tools/README.md

Add graph integration status to readme
Fixes #
**Checklist**

Add graph integration status

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.11.0-snapshot
Fixes #
**Checklist**

Bump 0.11.0-snapshot

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/relay/src/lib/errors/JsonRpcError.ts
packages/server/package.json
packages/server/src/koaJsonRpc/index.ts
packages/server/tests/acceptance/rateLimiter.spec.ts

- Bump 0.10.0-rc1
- cherry picked https://github.com/hashgraph/hedera-json-rpc-relay/pull/637
Fixes #
**Checklist**

Bump 0.10.0-rc1

---

Dockerfile

Add missing python to node alpine base image
Fixes #639 
**Checklist**

Add missing python to node alpine base image

---

Dockerfile

Add missing python to node alpine base image
Add missing python to node alpine base image.
Cherry pick of #640 
Fixes #
**Checklist**

Add missing python to node alpine base image (0.10)

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.10.0-rc2
Fixes #
**Checklist**

Bump 0.10.0-rc2

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.10.0
Fixes #
**Checklist**

Bump 0.10.0

---

packages/relay/src/lib/eth.ts
packages/relay/tests/helpers.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/openrpc.spec.ts

Provide a workaround to pull evm_address for contract logs
- for logs retrieve evm_address from mirror node
Fixes #644 
**Checklist**

Pull evm_address for contract logs

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.12.0-snapshot
Fixes #
**Checklist**

bump 0.12.0-snapshot

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.11.0-rc1
Fixes #
**Checklist**

Bump 0.11.0-rc1

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.11.0
Fixes #
**Checklist**

Bump 0.11.0

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.12.0-rc1

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.13.0-snapshot

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.12.0

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/710
**Checklist**

Fix handling of null amount value when fetching transactions from the mirror node

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.14.0-snapshot
Fixes #

Bump 0.14.0-snapshot

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.13.0-rc1

---

package-lock.json
packages/relay/package.json
packages/server/package.json

bump sdk version to 2.19.0

---

package-lock.json
packages/relay/package.json
packages/server/package.json
packages/server/src/server.ts
packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/helpers/prerequisite.ts

Cherry pick #718 and #726
Update dependent versions for tests and sdk.

Bump test sdk version

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.13.0-rc2

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

* Handle empty state_change array in contract details
cherry pick #733 
Cherry pick commit which addresses bug in issue #732

Handle empty state_changes array in contract details (#733)

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.13.0-rc3

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

* Return 32 byte 0 on empty state_changes array
Cherry pick #738  into 0.13.0 to be included into an rc release
Fixes #732

Cherry pick #738 into 0.13.0

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump to v0.13.0-rc4

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.13.0

---

helm-chart/value-test.yaml

Adds `values-test.yaml` chart for `testnet` and `previewnet.`
Fixes #743 
**Checklist**

Add a test values yaml for chart

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/constants.ts
packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/helpers.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts
packages/server/tests/acceptance/rpc.spec.ts

Cherry pick the following prs for release into version v0.13.1
#717 #744

Cherry pick commits for v0.13.1

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump v0.13.1

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/acceptance/rpc.spec.ts
packages/server/tests/helpers/prerequisite.ts

Pad slot value on comparison

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump snapshot version to 0.15.0-snapshot

Bump 0.15.0-snapshot

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.14.0-rc1

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.14.0

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.16.0-snapshot

Bump 0.16.0 snapshot

---

packages/server/tests/acceptance/rpc.spec.ts
packages/server/tests/helpers/assertions.ts

Fixes a couple of issues that cause the acceptance tests from `rpc.spec.ts` to occasionally fail.
Fixes #
**Checklist**

Fix acceptance test inconsistency

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.15.0 for general availability release.

Bump 0.15.0

---

packages/relay/src/lib/clients/sdkClient.ts
packages/server/tests/acceptance/rpc.spec.ts

Change default max transaction fee 

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.16.0-rc1

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump snapshot version to 0.17.0-snapshot

Bump 0.17.0-snapshot

---

package-lock.json
package.json
packages/relay/src/lib/eth.ts
packages/server/package.json
packages/server/src/validator/constants.ts
packages/server/src/validator/methods.ts
packages/server/src/validator/objectTypes.ts
packages/server/src/validator/types.ts
packages/server/tests/acceptance/erc20.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/acceptance/rpc.spec.ts
packages/server/tests/helpers/prerequisite.ts
packages/server/tests/integration/server.spec.ts

Expand `eth_call` validation to support blockParam object (#817)

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump to version 0.16.0-rc2.  
includes cherry pick of #816

Bump 0.16.0-rc2

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

eth_feeHistory wrongly returns error

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

Cherry pick #840

---

packages/server/src/validator/objectTypes.ts
packages/server/tests/acceptance/rpc.spec.ts

* fix validation for estimateGas
* fix duplication
* fix duplication
Cherry pick #846 into release 0.16.0

Cherry pick #846 - gas_estimate fix

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0-16-0-rc3

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.16.0-rc4
Fixes #
**Checklist**

Bump 0.16.0-rc4

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.18.0-snapshot

Bump 0.18.0 snapshot

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.17.0-rc2

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.17.0 for general availability release

GA release 0.17.0

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump to version 0.17.1

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.18.0-rc1
Fixes #
**Checklist**

Bump 0.18.0-rc1

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.19.0-SNAPSHOT
Fixes #
**Checklist**

Bump 0.19.0-SNAPSHOT

---

packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/precheck.ts

- Added InteractingEntity as a label/dimension to metrics collected for the consensues node, that way we can make a breakdown of costs by Smart Contract, etc..
Fixes # [906](https://github.com/hashgraph/hedera-json-rpc-relay/issues/906)
**Checklist**

Add InteractingEntity label to ConsensusNode Metrics

---

packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/precheck.ts

Cherrypicking commit 6b557cb into 0.18 release branch

Add InteractingEntity label to ConsensusNode Metrics (#910)

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.18.0 for GA release

GA 0.18.0 release

---

package-lock.json
package.json
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/helpers/prerequisite.ts

Bump network-node version to `0.35.0-alpha.6`
Bump mirror-node version to `0.75.0-rc3`
Update packages
Fixes #
**Checklist**

Bump Image Versions and Update Packages

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

On `estimateGas` we're checking only the account's existence, so we can cache if the account has been found. On `getTransactionByHash` we can use the same cached account because there we are using only the `evm_address` value which is immutable.
Fixes #915 
**Checklist**

Cache the account mirror node query on  `estimateGas` and `getTransactionByHash`

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump to version 0.20.0-snapshot

Bump 0.20.0-snapshot

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0.19.0-rc1

---

packages/relay/src/lib/eth.ts

Cherry pick #966 and #964 into release/0.19 in order to create an rc2.

Cherry pick 966 964

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump 0-19-0-rc2

---

packages/relay/src/lib/eth.ts
packages/server/src/server.ts

Fix the logs by
- Add the cached value
- Move request id to start of server error log message
Fixes #952 
**Checklist**

Improve cache log and server error log

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json

Bump version to 0.19.0 for GA release

Bump 0.19.0

---

README.md
docs/configuration.md

- Add a configuration document at `docs/configuration.md`
- highlight individual package values
- highlight test configs
- Updated main README with link to configuration document
Fixes #954 
**Checklist**

Add Configurations documents

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump 0.21.0-SNAPSHOT
Fixes #
**Checklist**

bump 0.21.0-SNAPSHOT

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.20.0-rc1
Fixes #
**Checklist**

Bump 0.20.0-rc1

---

packages/relay/src/lib/poller.ts
packages/relay/tests/lib/poller.spec.ts

This PR adds unit test to the poller class.
This PR modifies the relay test suite by adding the poller.spec.ts.
Fixes #941

941 add unit tests for the poller class

---

package-lock.json
package.json
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/acceptance/rpc_batch1.spec.ts
packages/server/tests/helpers/prerequisite.ts

There is a bug with `eth_getBalance` returning wrong balances. This happens because the number or BigNumber that's being calculated exceeds `MAX_SAFE_INTEGER` and calculation comes out wrong. We need to use data type that allows to do some basic calculation without exceeding `MAX_SAFE_INTEGER`, BigInt allows that.
Fixes #992 
**Checklist**

Fix `eth_getBalance` returning wrong balance

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.20.1
Fixes #
**Checklist**

Bump 0.20.1

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Created release candidate.

---

docs/openrpc.json

Add `eth_getStorageAt` in openrpc doc

---

docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump PR for release.
Fixes #1031

Bump PR for release.

---

helm-chart/Chart.yaml

Updated Chart.yaml

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/tests/lib/eth.spec.ts

Uses the axios controller abort to cancel requests on timeouts.
Fixes #1065

Added the abort controller to cancel requests.

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump version to 0.21.1

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/server/package.json
packages/ws-server/package.json

- cherry pick #1082 
- bump 0.21.2
Fixes #
**Checklist**

Cherry Pick HttpAgent and Bump 0.21.2

---

packages/relay/src/lib/clients/sdkClient.ts

- Add original error message in SDKCLient constructor
Cherry pick #1091 
- Add original error message in SDKCLient constructor
Fixes #
**Checklist**

Restore dropped SDKClient error message (#1091)

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.21.3
Fixes #
**Checklist**

Bump 0.21.3

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.22.0-rc1

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.23.0-SNAPSHOT

---

.github/workflows/acceptance.yml
package.json
packages/relay/src/lib/eth.ts
packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/clients/servicesClient.ts
packages/server/tests/contracts/openzeppelin/IERC165.json
packages/server/tests/contracts/openzeppelin/IERC165.sol
packages/server/tests/contracts/openzeppelin/IERC20.json
packages/server/tests/contracts/openzeppelin/IERC20.sol
packages/server/tests/contracts/openzeppelin/IERC20Metadata.json
packages/server/tests/contracts/openzeppelin/IERC20Metadata.sol
packages/server/tests/contracts/openzeppelin/IERC721.json
packages/server/tests/contracts/openzeppelin/IERC721.sol
packages/server/tests/contracts/openzeppelin/IERC721Enumerable.json
packages/server/tests/contracts/openzeppelin/IERC721Enumerable.sol
packages/server/tests/contracts/openzeppelin/IERC721Metadata.json
packages/server/tests/contracts/openzeppelin/IERC721Metadata.sol

Cherry pick PR 1012 into 0.22 release

Cherry pick PR 1012 into 0.22 release

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.22.0-rc2

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.21.4

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

GA Version 0.22.0

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.22.1

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/openrpc.spec.ts

Cherry-Pick PR 1115

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.22.2

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/package.json
packages/ws-server/package.json

- Bump #1152 
- bump 0.22.3
Fixes #
**Checklist**

Cherry pick 1152 and bump

---

packages/relay/src/index.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/acceptance/rpc_batch2.spec.ts
packages/server/tests/integration/server.spec.ts
packages/server/tests/postman.json

Update eth_estimateGas to handle invalid to and value
Fixes #1155 
**Checklist**

Update eth_estimateGas to handle invalid to and value

---

packages/relay/tests/lib/eth.spec.ts

eth_estimateGas fixes.
Fixes #1106
**Checklist**

Eth estimate gas fixes

---

packages/relay/tests/lib/eth.spec.ts

Cherry-Pick of PR 1175 into `release/0.23` branch

Cherry-Pick: Updated eth_estimateGas bad input tests (#1175)

---

.github/workflows/test.yml
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/constants.ts
packages/relay/tests/lib/sdkClient.spec.ts

Add caching logic to getTinyBarGasFee()

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/tests/lib/eth.spec.ts

Cherry-Pick: resolveEntityType error  handling  improvement  inside promises  (#1216)

---

packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/acceptance/rpc_batch1.spec.ts
packages/server/tests/clients/relayClient.ts

Return meaningful JSON RPC errors (#1213)

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump PR 0.23.0-rc2

---

Dockerfile

- Update docker file base image to bullseye-slim
- Update node version to latest LTS 18.16
- Update copy to take only necessary files
Fixes #1195 
**Checklist**

Update dockerfile build based on debian

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.23.1

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version  0.23.2

---

packages/relay/src/lib/constants.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

Add cache support for eth_getBlockTransactionCountByNumber and eth_getBlockTransactionCountByHash

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump Relay Version to 0.23.3

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.23.4

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump versions 0.23.5

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/errors/MirrorNodeClientError.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/helpers.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts
packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts

Cherry-Pick: Return correct error for rate limit (#1269)

---

README.md
docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.24.0-rc1

---

docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.25.0-SNAPSHOT

---

docker-compose.yml
docs/openrpc.json
helm-chart/Chart.yaml
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.24.0
Fixes #
**Checklist**

Bump 0.24.0

---

packages/server/src/server.ts
packages/ws-server/src/webSocketServer.ts

Add unhandledRejection and uncaughtException server logs
Fixes #1301 
**Checklist**

Add processs unhandledRejection and uncaughtException server logs

---

scripts/.bump-version.js

Fixes The updated helm chart directory declaration in the script.

Updated to reflect new directory structure.

---

README.md
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json
scripts/.bump-version.js

Bump 0.25.0 rc1

---

packages/relay/src/lib/precheck.ts

Catch predefined error on balance check
Fixes #1341 
**Checklist**

Catch JsonRpcError on balance check

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts
packages/relay/tests/lib/precheck.spec.ts

Handle max pagination
- throw on max page
- update tests
Fixes #1343 
**Checklist**

Handle max pagination

---

charts/hedera-json-rpc-relay-websocket/templates/deployment.yaml
charts/hedera-json-rpc-relay/templates/deployment.yaml

Add terminationGracePeriodSeconds to chart deployment resource
Fixes #1349 
**Checklist**

Add terminationGracePeriodSeconds to chart deployment resource

---

packages/server/tests/acceptance/index.spec.ts
packages/server/tests/helpers/prerequisite.ts

Bump images for acceptance tests to the newest ones.
Fixes #
**Checklist**

Bump Acceptance Tests Node Images

---

README.md
charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.26.0-rc1
**Related issue(s)**: #1387

bump version 0.26.0-rc1

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.27.0-SNAPSHOT
**Related issue(s)**: #1387

bump version 0.27.0-SNAPSHOT

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.26.0-rc2

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.26.0-rc4

---

packages/relay/src/lib/clients/mirrorNodeClient.ts

Cherry-Pick: 1401 into 0.26
**Related issue(s)**: #1401 
Fixes #
**Checklist**

Cherry-Pick: 1401 into 0.26

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.26.0 GA

---

packages/relay/src/lib/clients/clientCache.ts
packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/relay.ts
packages/relay/src/lib/services/hapiService/hapiService.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/ethGetBlockBy.spec.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts
packages/relay/tests/lib/openrpc.spec.ts
packages/relay/tests/lib/precheck.spec.ts
packages/relay/tests/lib/sdkClient.spec.ts

Cherry pick 1245 into 0.26 release

---

.github/workflows/release-production.yml
README.md

Cherry-pick PR #1408 into release/026

Cherry Pick 1408 into release 0.26 - Enable chart deploy on github workflow (#1408)

---

package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

upgrade axios and axios-retry dependencies to latests versions
Fixes #1415
**Checklist**

upgrade axios and axios-retry dependencies to latests versions

---

.github/workflows/release-automation.yml

Cherry pick 1258
#1258 
Fixes #
**Checklist**

Cherry pick: 903 automate branch tag (#1258)

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.26.1
#1387
Fixes # 
**Checklist**

bump version 0.26.1

---

package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

cherry-pick: upgrade axios and axios-retry dependencies to latests versions (#1412)
#1387

cherry-pick: upgrade axios and axios-retry dependencies to latests versions (#1412)

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

bump version 0.26.2

---

packages/server/src/server.ts
packages/server/tests/integration/server.spec.ts

Update server to support cors preflight check (#1433)

---

packages/relay/src/lib/clients/clientCache.ts
packages/server/tests/integration/server.spec.ts

cherry-pick: Fix clientCache metric collection (#1432)

cherry-pick: Fix clientCache metric collection (#1432)

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump version 0 26 3

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.27.0-rc1

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docs/openrpc.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump version 0.28.0-SNAPSHOT

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump PR 0.27.0-rc2

---

package-lock.json
packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/relay.ts
packages/relay/tests/helpers.ts
packages/relay/tests/lib/eth.spec.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts
packages/relay/tests/lib/openrpc.spec.ts
packages/server/src/server.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/acceptance/ws/subscribe.spec.ts
packages/ws-server/src/webSocketServer.ts

Improve logging for easier troubleshooting
- Exchange `requestId` for `requestIdPrefix` to reduce number of calls to `formatRequestIdMessage()`
- Set logger name for poller and subImpl loggers
- add request id log to ws-server, distinguishing connection id and request id
Fixes #1218 
**Checklist**

Improve logging across classes

---

package-lock.json
packages/relay/src/lib/errors/MirrorNodeClientError.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts
packages/server/tests/acceptance/erc20.spec.ts
packages/server/tests/acceptance/index.spec.ts

Handles CONTRACT_REVERT properly be returning the message from the contract to the provider.
Fixes #1398 
**Checklist**

Handles CONTRACT_REVERT properly be returning the message.

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump 0.27.1
Fixes #1459
**Checklist**

Bump PR 0.27.1

---

dapp-example/package.json
dapp-example/tests/e2e/bootstrap.js
tools/web3js-example/package.json
tools/web3js-example/scripts/deployContract.js

This pull request involves the elimination of hethers' usages throughout the codebase.
Fixes #1524 
**Checklist**

Removes hethers since it is deprecated

---

docs/diagrams/hapi-service-diagram.md
docs/diagrams/hbar-limiter-diagram.md
docs/diagrams/operation.md
docs/diagrams/project-overview-diagram.md

This PR adds some diagrams explaining the way relay works, HAPI service class works and Hbar limiter.
Fixes #
**Checklist**

Add couple of diagrams

---

README.md
charts/hedera-json-rpc/dashboards/JSON RPC Relay (Official)-1689822975711.json
charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json

This PR modifies ... in order to support ...
* Adds grafana dashboard to charts folder
Fixes #1337
**Checklist**

This is the exported JSON from the grafana dashboard

---

packages/relay/src/lib/eth.ts

Adds `typeof` in string property conditional check.
Fixes #1581

Added typeof prefix in conditional.

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

Updated it condition.
Fixes #1581

1581 set typeof in undefined condition

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump PR. 30-SNAPSHOT

---

README.md
charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docker-compose.yml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump PR. 0.29.0-rc1

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth.spec.ts

added null check for non found account for given block in the past
Fixes #1648
**Checklist**

added null check for non found account for given block in the past

---

charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
charts/hedera-json-rpc-relay-websocket/values.yaml
docs/configuration.md
package-lock.json
packages/server/tests/acceptance/ws/subscribe.spec.ts
packages/ws-server/src/webSocketServer.ts

Cherry pick of #1658 into `release/0.30`

Cherry-Pick: Add ping messages to websocket server (#1658)

---

packages/relay/src/lib/eth.ts
packages/server/tests/acceptance/rpc_batch1.spec.ts
packages/server/tests/helpers/assertions.ts

This PR modifies the getTransactionReceipt method in order to support returning type property in the response
Fixes #1647 
**Checklist**

Adds type property to getTransactionReceipt response

---

.eslintrc.js
.husky/pre-commit
package-lock.json
package.json

This PR adds automatically formatting and cleaning code on commit.
Code style is standard for typescript. All files changed prior commit will be formatted.
Fixes #559 
**Checklist**

Automatically formatting and cleaning code on commit

---

packages/server/tests/acceptance/erc20.spec.ts
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/acceptance/rpc_batch2.spec.ts

Fixes eth_estimateGas.  
Fixes #1514
**Checklist**

Applied test fixes.

---

packages/server/tests/acceptance/cacheService.spec.ts
packages/server/tests/acceptance/index.spec.ts

Environment variable fixes 
Fixes #1706

Environment variable fixes.

---

docs/design/debug-api.md

This PR adds design documentation for the debug endpoint. What new methods are going to be introduced and how.
Fixes #1479
**Checklist**

Add Documentation for Debug endpoint

---

.github/workflows/subgraph.yml

Fixing Flacky SubGraph Test
Fixes #1755 
**Checklist**

Fix  Flaky Subgraph Acceptance Test - Adding a sleep to wait for the subgraph to index before running tests

---

.github/workflows/acceptance-workflow.yml
package-lock.json
packages/server/package.json
packages/server/tests/acceptance/conformityTests.spec.ts

This PR fixes the failing API Conformity tests by changing the tag for the execution-apis repo to a commit sha.
Change in the PR:
* Add commit sha of the remote repo to package.json
* Add a timeout within the conformity tests to optimize execution speed within the continuous integration (CI) pipeline
Fixes #1772

Fixes api conformity tests failing in ci

---

packages/relay/src/lib/precheck.ts
packages/relay/tests/lib/precheck.spec.ts

This PR is a follow up on https://github.com/hashgraph/hedera-json-rpc-relay/pull/1637
Adding some more tests as well as fixing the precheck test suite, because it was not running at all due to errors.
Fixes #1631 
**Checklist**

Add more tests and refine Intrinsic gas cost calculation

---

.github/workflows/acceptance-workflow.yml
.github/workflows/acceptance.yml
.github/workflows/charts.yml
.github/workflows/dapp.yml
.github/workflows/dev-tool-test.yml
.github/workflows/postman.yml
.github/workflows/subgraph.yml
.github/workflows/test.yml

This PR updates the github actions to cancel in progress pipelines on the same branch
Fixes #1815 
**Checklist**

Cancel in progress action runs

---

docs/design/debug-api.md
package-lock.json
package.json
packages/server/tests/acceptance/rpc_batch3.spec.ts
packages/server/tests/helpers/assertions.ts

This PR adds acceptance tests to cover the behaviour of the debug_traceTransaction in both positive and negative scenarious:
- Adds positive and negative acceptance tests
- Adds tests brief description in the design document
**Related issue(s):**
**Fixes** 
#1792 
Notes for reviewer:
The ticket for implementing the debug_traceTransaction is: #1477 
Checklist

Add acceptance tests for debug_traceTransaction endpoint

---

dapp-example/package-lock.json
dapp-example/package.json
docs/examples/package.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Upgrading @hashgraph/sdk to 2.36.0 across all packages.
**Related issue(s)**: #1839 
Fixes #
**Checklist**

Upgrading @hashgraph/sdk to 2.36.0 across all packages.

---

dapp-example/package-lock.json
dapp-example/package.json
docs/examples/package.json
package-lock.json
packages/relay/package.json
packages/relay/src/lib/services/debugService/index.ts
packages/server/package.json
packages/server/tests/acceptance/rpc_batch1.spec.ts
packages/ws-server/package.json

Removes only from a test in rpc_batch1 which was added via the PR for #1752

Removes only from test

---

dapp-example/package-lock.json
dapp-example/package.json
docs/examples/package.json
package-lock.json
packages/relay/package.json
packages/relay/src/lib/services/debugService/index.ts
packages/server/package.json
packages/server/tests/acceptance/rpc_batch1.spec.ts
packages/ws-server/package.json

Cherry pick #1845

---

packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/services/debugService/index.ts
packages/relay/tests/lib/services/debugService/debug.spec.ts

Fixing some small issues as per https://github.com/hashgraph/hedera-json-rpc-relay/pull/1745#pullrequestreview-1665024324
Fixes #1477 
**Checklist**

Changes the error to throw for opcode logger

---

package-lock.json
package.json
packages/server/tests/acceptance/index.spec.ts
packages/server/tests/helpers/prerequisite.ts
tools/hardhat-example/package-lock.json
tools/hardhat-example/package.json
tools/subgraph-example/package-lock.json
tools/subgraph-example/package.json

This PR aims to bump the @hashgraph/hedera-local version to it's latest in all places, as well as bumps the image verisons used in the acceptance tests
Fixes #
**Checklist**

Bump Hedera-Local version

---

package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Package lock file fixed by running `npm install`
Fixes #
**Checklist**

fix package-lock.json

---

charts/hedera-json-rpc-relay-websocket/Chart.yaml
charts/hedera-json-rpc-relay/Chart.yaml
docs/openrpc.json
package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

Bump PR 0.37.0-SNAPSHOT 
Fixes #1898

Bump PR 0.37.0-SNAPSHOT

---

packages/server/tests/acceptance/estimateGasPrecompile.spec.ts

1600 - Adapted the existing to use deviation and actual gas and added tests for estimateGas with precompiles

---

.github/workflows/acceptance-workflow.yml

Upgraded the CI runner
Fixes #1981

feat: Upgraded CI runner.

---

docs/design/batch-request.md

Including Documentation for Batch Requests including the following topics:
Overview
Goals / Motivation
Configuration
Implementation and Usage
Errors
Metrics
Rate Limits
Tests
Tasks
Fixes #1875
**Checklist**

Design Documentation for Batch Requests

---

packages/server/src/validator/constants.ts
packages/server/src/validator/methods.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts
packages/server/tests/integration/server.spec.ts

Changes validation so endpoint accepts block hash

---

packages/relay/src/lib/eth.ts
packages/relay/tests/helpers.ts
packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
packages/server/src/validator/methods.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts
packages/server/tests/integration/server.spec.ts

This PR modifies:
* Changes validation for getTransactionCount so we support blockHash
* Changes implementation in eth.ts in order to support the block hash and handle incoming requests
* Adds tests for the new logic
Fixes #1856 
**Checklist**

Enables block hash use for getTransactionCount

---

package-lock.json
packages/ws-server/package.json

chore: Reapplying snyk upgrade, pnpm from 8.10.5 to 8.11.0

---

tools/README.md
tools/foundry-example/README.md

Updated to include foundry in README.md and latest open zeppelin version in the foundry example README.md
Fixes #2019
**Checklist**

2019 update included tools to include foundry

---

packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts
packages/server/tests/helpers/utils.ts

Added polling to stabilize tests.
Fixes #2013

test: 2013 add polling to the relay stabilize

---

packages/server/tests/acceptance/htsPrecompile_v1.spec.ts

Added the deploy retry
Fixes #2013

test: Added the deploy retry.

---

packages/relay/src/formatters.ts
packages/relay/src/lib/constants.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_call.spec.ts
packages/relay/tests/lib/formatters.spec.ts

Removed prechecks for non-existing entities.
Fixes #2039 
**Checklist**

fix: Removed prechecks for existing accounts.

---

packages/relay/src/formatters.ts
packages/relay/src/lib/constants.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_call.spec.ts
packages/relay/tests/lib/formatters.spec.ts

* fix: Removed prechecks for existing accounts.
* fix: Updated copyrights
* fix: Updated copyright.
Fixes #2039 
**Checklist**

fix: Removed prechecks for existing accounts. (#2046)

---

package-lock.json
packages/server/package.json
packages/ws-server/package.json

Upgraded koa-router dependency to 12.0.1 to improve performance
Fixes #2064 
**Checklist**

build: Upgraded koa-router dependency to 12.0.1 to improve performance

---

.github/workflows/release-acceptance.yml

WIP.  acceptance release test workflow.
**Related issue(s)**: #1986 
Fixes #

feat: WIP: acceptance release tests workflow.

---

packages/server/src/server.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts

Cherry pick into release.
Fixes #2084

fix: Status Code on Relay Response Logs (#2085)

---

docs/openrpc.json

Update 'openrpc.json' to include WS Servers and eth_subscribe, eth_filter and debug API methods.
Fixes #
You can verify the spec using the following link:
https://playground.open-rpc.org/?schemaUrl=https://raw.githubusercontent.com/hashgraph/hedera-json-rpc-relay/update-spec-docs/docs/openrpc.json
**Checklist**

docs: Update Spec API Docs

---

package-lock.json
package.json
packages/server/tests/helpers/prerequisite.ts

This PR updates local-node to latest version and bumps all used images as well.
Fixes #
**Checklist**

chore: update local node

---

.github/workflows/acceptance-workflow.yml
.github/workflows/manual-testing.yml

Add Manual testing workflow for running acceptance test against chosen tags
Fixes #2092
**Checklist**

feat: Adding manual testing workflow

---

packages/relay/src/lib/eth.ts

cherry-pick #2141
Fixes #
**Checklist**

chore: cherry-pick #2141: adding logs for eth_call size and gas (#2141)

---

tools/subgraph-example/package-lock.json
tools/subgraph-example/package.json

This PR updates the hardhat dependency in subgraph example to fix a failure in CI
Fixes #
**Checklist**

chore: update hardhat version in subgraph example

---

docs/configuration.md
docs/design/eth-subscribe.md

Updated documentation.  Includes design and configuration updates.
**Related issue(s)**: #2117

2117 poll for new heads doc updates

---

docs/openrpc.json
packages/relay/src/lib/services/ethService/ethCommonService/index.ts
packages/relay/tests/lib/eth/eth_feeHistory.spec.ts
packages/relay/tests/lib/eth/eth_getBalance.spec.ts
packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
packages/relay/tests/lib/eth/eth_getBlockTransactionCountByNumber.spec.ts
packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
packages/relay/tests/lib/eth/eth_getTransactionByBlockNumberAndIndex.spec.ts
packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
packages/server/src/validator/types.ts

This PR adds new block aliases - _finalized_ and _safe_ in order to be compliant to Ethereum.
Fixes #2106 
**Checklist**

feat: Adds missing block aliases

---

packages/relay/src/lib/poller.ts

Added metric for polling.  
**Related issue(s)**: #2117

feat:  Added metric for newHeads.

---

package-lock.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

cherry pick #2237 
Fixes #
**Checklist**

chore: cherry-pick: update hashgraph/sdk to 2.43.0  (#2237)

---

docs/openrpc.json
packages/relay/src/index.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/services/ethService/ethCommonService/index.ts
packages/relay/tests/lib/eth/eth_getLogs.spec.ts
packages/server/tests/acceptance/rpc_batch1.spec.ts

Cherry-pick of #2236  into release branch `0.44` for `0.44.2` deployment
Fixes #
**Checklist**

chore: cherry-pick #2236 into release 0.44

---

packages/server/tests/acceptance/rpc_batch2.spec.ts

fix: test fix.  Now consider gas price deviation in estimateGas.

---

packages/relay/tests/lib/subscriptionController.spec.ts
packages/ws-server/src/controllers/eth_subscribe.ts
packages/ws-server/src/controllers/eth_unscribe.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/subscriptions/handlers.ts
packages/ws-server/src/utils/connectionLimiter.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/utils/counters.ts
packages/ws-server/src/utils/formatters.ts
packages/ws-server/src/utils/utils.ts
packages/ws-server/src/utils/validators.ts
packages/ws-server/src/webSocketServer.ts
packages/ws-server/tsconfig.json

This PR aims to refactor the `package/ws-server` folder, breaking down the main `webSocketServer.ts` file into smaller programs within their respective folders.
**Related issue(s)**: #2182 
Fixes #
**Checklist**

fix: refactor websocket folders

---

packages/server/tests/acceptance/ws/getBlockByNumber.spec.ts
packages/ws-server/src/controllers/eth_getBlockByNumber.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/webSocketServer.ts

This PR adds support for eth_getBlockByNumber to the WS server and a suite of acceptance tests
Fixes #2306 
**Checklist**

feat: added support for eth_getBlockByNumber to the WS server (#2306)

---

packages/server/tests/acceptance/ws/blockNumber.spec.ts
packages/ws-server/src/controllers/eth_blockNumber.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/webSocketServer.ts

- This PR adds support for eth_blockNumber to the WS server and acceptance test to cover the feature
Fixes #2270 
**Checklist**

feat: added support for eth_blockNumber to the WS server (#2270)

---

packages/server/tests/acceptance/ws/getBalance.spec.ts
packages/ws-server/src/controllers/eth_getBalance.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/webSocketServer.ts

This PR adds support for eth_getBalance to the WS server along with its acceptance tests
Fixes #2280
**Checklist**

feat: added support for eth_getBalance to the WS server (#2280)

---

packages/server/tests/acceptance/ws/getStorageAt.spec.ts
packages/ws-server/src/controllers/eth_getStorageAt.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/webSocketServer.ts

This PR adds support for eth_getStorageAt to the WS server along with its acceptancetests
Fixes #2277 
**Checklist**

feat: added support for eth_getStorageAt to the WS server (#2277)

---

packages/server/tests/acceptance/ws/getTransactionCount.spec.ts
packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
packages/server/tests/helpers/utils.ts
packages/ws-server/src/controllers/eth_getTransactionCount.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/webSocketServer.ts

Implements `eth_getTransactionCount`
Fixes #2275

feat: getTransactionCount.

---

packages/server/tests/acceptance/ws/getLogs.spec.ts
packages/server/tests/acceptance/ws/getTransactionCount.spec.ts
packages/ws-server/src/controllers/eth_getLogs.ts
packages/ws-server/src/controllers/eth_getTransactionCount.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/webSocketServer.ts
test-results.02088f1d2a29bfef82062b5ed525526f.xml

This PR adds support for eth_getLogs to WS server along with its acceptance test
Fixes #2281
**Checklist**

feat: added support for eth_getLogs to the WS server (#2281)

---

packages/server/tests/acceptance/ws/call.spec.ts
packages/ws-server/src/controllers/eth_call.ts
packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/src/webSocketServer.ts

This PR adds support for eth_call to the WS server along with its acceptance tests
Fixes #2278 
**Checklist**

feat: added support for eth_call to the WS server

---

docs/design/eth-subscribe.md

feat: newHeads documentation update.
**Related issue(s)**: #2117 
Fixes #
**Checklist**

fix:  Fix to eth_subscribe.md

---

packages/ws-server/src/webSocketServer.ts
packages/ws-server/tests/acceptance/blockNumber.spec.ts
packages/ws-server/tests/acceptance/call.spec.ts
packages/ws-server/tests/acceptance/estimateGas.spec.ts
packages/ws-server/tests/acceptance/gasPrice.spec.ts
packages/ws-server/tests/acceptance/getBalance.spec.ts
packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
packages/ws-server/tests/acceptance/getCode.spec.ts
packages/ws-server/tests/acceptance/getLogs.spec.ts
packages/ws-server/tests/acceptance/getStorageAt.spec.ts
packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
packages/ws-server/tests/acceptance/subscribe.spec.ts
packages/ws-server/tests/helper/index.ts

This PR adds acceptance test coverage for stand web socket in WS server
Fixes #2316 
**Checklist**

feat: added acceptance test coverage for standard web socket (#2316)

---

docs/design/eth-subscribe.md

Cherry-Pick of PR #2230 into Release `0.46` branch
Fixes #
**Checklist**

fix:  Fix to eth_subscribe.md (#2230)

---

dapp-example/package-lock.json
dapp-example/package.json

Cherry-pick of #2308 into release `0.46`
Fixes #
**Checklist**

chore: Cherry pick into 0-46 #2308

---

packages/ws-server/src/webSocketServer.ts
packages/ws-server/tests/acceptance/blockNumber.spec.ts
packages/ws-server/tests/acceptance/call.spec.ts
packages/ws-server/tests/acceptance/estimateGas.spec.ts
packages/ws-server/tests/acceptance/gasPrice.spec.ts
packages/ws-server/tests/acceptance/getBalance.spec.ts
packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
packages/ws-server/tests/acceptance/getCode.spec.ts
packages/ws-server/tests/acceptance/getLogs.spec.ts
packages/ws-server/tests/acceptance/getStorageAt.spec.ts
packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
packages/ws-server/tests/acceptance/subscribe.spec.ts
packages/ws-server/tests/helper/index.ts

Cherry pick of #2340  into release `0.46`
Fixes #
**Checklist**

chore: Cherry pick 0 46 #2340

---

docs/configuration.md
packages/relay/src/lib/poller.ts
packages/ws-server/src/controllers/eth_subscribe.ts

Now defaults to true.
Fixes #2350 
**Checklist**

fix: Now sets the WS_NEW_HEADS_ENABLED to true by default.

---

tools/truffle-example/package-lock.json

Rebuilt package-lock.json
Fixes #2342

fix: rebuilt package-lock.json

---

grafana/dashboards/websocketServer/webSocketServer.json

Adding a web socket dashboard.
Fixes #2355

feat: Adding websocket grafana dashboard to the relay repository.

---

package-lock.json
package.json

Remove specific version of NX dependency override. is working now without it.
Fixes #1636 
**Checklist**

chore: Remove specific version of NX dependency override. is working now.

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_call.spec.ts
packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
packages/server/tests/acceptance/rpc_batch2.spec.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts

Cherry Pick #2377  on `release/0.46` branch in preparations for `0.46.1` release
Fixes #
**Checklist**

chore: Cherry pick #2377 on `0.46` release

---

docs/live-events-api.md

Websocket documentation updates.
Fixes #2117

feat: Websocket documentation updates.

---

docs/openrpc.json

This PR fixes #2399.
Fixes #
**Checklist**

docs: include block range limit in `eth_getLogs` spec

---

.github/workflows/test.yml

Handle memory issues in CI
Fixes #2262

fix: Re-submitting the memory handling

---

packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/errors/SDKClientError.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts

Cherry-pick of PR #2419 on branch `release/0.46` in preparations for `0.46.4` release.
Fixes #
**Checklist**

fix: moved deleteFile() logic to the eth_sendRawTransaction level (#2419)

---

Dockerfile

Revert docker update to allow image to build.

chore: Revert synk PR #2408.  Docker image won't build.

---

Dockerfile

Revert node update to allow docker image to build.

chore: Revert synk PR #2408.  Docker image won't build. (#2428)

---

packages/ws-server/src/controllers/eth_blockNumber.ts
packages/ws-server/src/controllers/eth_call.ts
packages/ws-server/src/controllers/eth_estimateGas.ts
packages/ws-server/src/controllers/eth_gasPrice.ts
packages/ws-server/src/controllers/eth_getBalance.ts
packages/ws-server/src/controllers/eth_getBlockByHash.ts
packages/ws-server/src/controllers/eth_getBlockByNumber.ts
packages/ws-server/src/controllers/eth_getCode.ts
packages/ws-server/src/controllers/eth_getLogs.ts
packages/ws-server/src/controllers/eth_getStorageAt.ts
packages/ws-server/src/controllers/eth_getTransactionByHash.ts
packages/ws-server/src/controllers/eth_getTransactionCount.ts
packages/ws-server/src/controllers/eth_getTransactionReceipt.ts
packages/ws-server/src/controllers/eth_sendRawTransaction.ts
packages/ws-server/src/controllers/helpers.ts
packages/ws-server/src/utils/utils.ts
packages/ws-server/tests/helper/index.ts

This PR cherry picked PR#2444 to 0.47
Fixes #
**Checklist**

chore: cherry-picked PR#2444

---

packages/relay/src/lib/eth.ts

This PR adds an extra debug level log to expose contract call response for eth_call requests
Fixes #2441
**Checklist**

chore: added a debug level log to expose contract call response for eth_call requests (#2441)

---

.github/workflows/image-build.yml
Dockerfile

added CI build test
Fixes #1871 
when I did one of the offending changes commits it did fail as expected:
**failed build:**
https://github.com/hashgraph/hedera-json-rpc-relay/actions/runs/8973110170/job/24642544534?pr=2456
**after reverting the offending commit:**
**Checklist**

feat: added CI build test

---

packages/relay/src/formatters.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
packages/relay/tests/lib/formatters.spec.ts

Applied fix using trimPrecedingZeros.
Fixes #2451

fix: Applied fix using trimPrecedingZeros.

---

packages/ws-server/src/controllers/index.ts
packages/ws-server/src/utils/constants.ts
packages/ws-server/tests/acceptance/web3ClientVersion.spec.ts

Cherry-Pick for #2486 
Fixes #
**Checklist**

chore: Cherry pick 2486

---

packages/ws-server/src/controllers/index.ts
packages/ws-server/tests/acceptance/validations.spec.ts
packages/ws-server/tests/helper/index.ts

fix: added support for undefined param requests
Cherry pick #2494
Fixes #
**Checklist**

chore: cherry pick 2494

---

packages/relay/src/lib/eth.ts
packages/relay/src/lib/types/IFeeHistory.ts
packages/relay/src/lib/types/ITransactionReceipt.ts

cherry picked #2265 
Fixes #
**Checklist**

chore: cherry picked 2265

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
packages/server/tests/acceptance/rpc_batch2.spec.ts

chore: cherry picked 2492

---

packages/relay/src/formatters.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
packages/relay/tests/lib/formatters.spec.ts

Cherry pick #2499 
Fixes #
**Checklist**

chore: cherry picked 2499

---

packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/tests/lib/eth/eth_call.spec.ts
packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts

Cherry pick #2523
Fixes #
**Checklist**

chore: cherry pick 2523

---

packages/ws-server/src/controllers/eth_subscribe.ts
packages/ws-server/src/utils/utils.ts
packages/ws-server/tests/acceptance/subscribe.spec.ts
packages/ws-server/tests/unit/utils.spec.ts

Cherry pick #2521 
Fixes #
**Checklist**

chore: cherry pick 2521

---

.github/workflows/release-acceptance.yml
.github/workflows/release-automation.yml
.github/workflows/release-production.yml

fix: Updated release flows to setup-node and setup make before calling npm ci

---

.github/workflows/release-acceptance.yml
.github/workflows/release-automation.yml
.github/workflows/release-production.yml

Cherry pick release automation fixes into the release branch
**Related issue(s)**: #2560 
Fixes #
**Checklist**

fix: 2560 include workflow updates in release branch

---

packages/relay/src/lib/clients/sdkClient.ts
packages/server/tests/acceptance/rpc_batch1.spec.ts

Cherry pick https://github.com/hashgraph/hedera-json-rpc-relay/pull/2566
Fixes #
**Checklist**

chore: cherry pick PR#2566

---

packages/ws-server/tests/acceptance/batchRequest.spec.ts
packages/ws-server/tests/acceptance/blockNumber.spec.ts
packages/ws-server/tests/acceptance/call.spec.ts
packages/ws-server/tests/acceptance/estimateGas.spec.ts
packages/ws-server/tests/acceptance/gasPrice.spec.ts
packages/ws-server/tests/acceptance/getBalance.spec.ts
packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
packages/ws-server/tests/acceptance/getCode.spec.ts
packages/ws-server/tests/acceptance/getLogs.spec.ts
packages/ws-server/tests/acceptance/getStorageAt.spec.ts
packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
packages/ws-server/tests/acceptance/newFilter.spec.ts
packages/ws-server/tests/acceptance/rateLimiter.spec.ts
packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
packages/ws-server/tests/acceptance/subscribe.spec.ts
packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
packages/ws-server/tests/acceptance/validations.spec.ts
packages/ws-server/tests/acceptance/web3ClientVersion.spec.ts
packages/ws-server/tests/helper/index.ts

This PR filterred acceptance tests that were included in release testing.
Fixes #2576 
**Checklist**

fix: filtered acceptance tests for release testing

---

packages/relay/src/formatters.ts

Fix txn v format
**Related issue(s)**: #2500 
Fixes #

fix: Set the correct txn v value.

---

grafana/dashboards/websocketServer/webSocketServer.json
package-lock.json
packages/ws-server/src/metrics/wsMetricRegistry.ts

Building out WebSocket Server Grafana
**Related issue(s)**: #2373 
Fixes #
**Checklist**

fix: Added panels.

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/tests/lib/eth/eth_getLogs.spec.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts
packages/server/tests/acceptance/rpc_batch1.spec.ts

Cherry pick #2616 
Fixes #
**Checklist**

chore: cherry pick PR#2616

---

.github/workflows/acceptance-workflow.yml
.github/workflows/dapp.yml
.github/workflows/dev-tool-workflow.yml
.github/workflows/postman.yml
.github/workflows/pr-label-milestone-check.yml
.github/workflows/release-acceptance.yml
.github/workflows/release-automation.yml
.github/workflows/release-production.yml
.github/workflows/subgraph.yml
.github/workflows/test.yml
Dockerfile
README.md

fix: Upgrade Node version to 20
Fixes #2224 

fix: Upgrade to node 20.

---

packages/relay/src/formatters.ts
packages/relay/tests/lib/formatters.spec.ts

**Related issue(s)**: 2500
Fixes #

fix: String preceding zeros from signature key values.

---

packages/server/src/server.ts

fix: debug_traceTransaction not working when we don't pass tracerConfig

---

packages/relay/src/lib/services/cacheService/cacheService.ts
packages/relay/src/lib/services/ethService/ethFilterService/index.ts

Cherry pick PR #2668 
Fixes #2668

fix: Adds usage of internal cache for getFilterChanges (#2668)

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/server/tests/acceptance/rateLimiter.spec.ts
packages/server/tests/acceptance/rpc_batch2.spec.ts

Cherry picked [PR#2730](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2730) to release/0.51
Fixes #
**Checklist**

chore: cherry picked PR#2730

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/eth.ts
packages/server/tests/acceptance/rateLimiter.spec.ts
packages/server/tests/acceptance/rpc_batch2.spec.ts

Cherry picked https://github.com/hashgraph/hedera-json-rpc-relay/pull/2714 to release/0.52
Fixes #
**Checklist**

chore: cherry picked PR#2714

---

packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/hbarlimiter/index.ts
packages/relay/tests/lib/hbarLimiter.spec.ts

Add first round solution to preemtively limit HBAR based on callDataSize
Fixes #
**Checklist**

feat: added preemtiveCheck for HBAR ratelimit

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/ethGetBlockBy.spec.ts

* chore: populate synthetic transaction hashes
* chore: fix naming
* chore: rename tests
* chore: remove .only
* chore: rename test
* chore: remove code duplication in the test
---------
Fixes #
**Checklist**

fix: populate synthetic transactions on `getBlock...` routes (#2784)

---

dapp-example/package-lock.json
dapp-example/package.json
package-lock.json
package.json
packages/relay/package.json
packages/server/package.json
packages/ws-server/package.json

This PR bumps local-node and sdk version everywhere. That should fix issues like #2434 
Fixes #2792 
**Checklist**

chore: update local-node and sdk

---

.github/workflows/dapp.yml

This PR migrates the `gh-docker-logs` action to the step-security maintained version
Fixes #2716 
**Checklist**

chore: migrate gh-docker-logs to step-security maintained version

---

charts/hedera-json-rpc/dashboards/webSocketServer.json

Added requests panels to the websockets dashboard
**Related issue(s)**: #2654

feat: Added request panels to the websocket dashboard.

---

packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/hbarlimiter/index.ts

**Description**: 
This small PR added more logs to HBARLimit class
Fixes #2736
**Checklist**

fix: added logging to HBARLimit class

---

package-lock.json
packages/server/package.json
packages/server/tests/helpers/utils.ts

This PR replaces the heap snapshot logic imported from `heapdump` with v8's `writeHeapSnapshot` and removes the unnecessary `heapdump` dependency which also causes the CI to fail sometimes due to the updated node version used in the CI.
Example logs from CI failure due to the `heapdump` dependency:
```bash
npm error code 1
npm error path /runner/_work/hedera-json-rpc-relay/hedera-json-rpc-relay/node_modules/heapdump
npm error command failed
npm error command sh -c node-gyp rebuild
npm error make: Entering directory '/runner/_work/hedera-json-rpc-relay/hedera-json-rpc-relay/node_modules/heapdump/build'
npm error   CXX(target) Release/obj.target/addon/src/heapdump.o
npm error make: Leaving directory '/runner/_work/hedera-json-rpc-relay/hedera-json-rpc-relay/node_modules/heap …
```

chore: remove unnecessary heapdump dependency

---

packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/errors/MirrorNodeClientError.ts
packages/relay/src/lib/eth.ts
packages/relay/tests/lib/errors/JsonRpcError.spec.ts
packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
packages/relay/tests/lib/formatters.spec.ts

chore: cherry picked PR#2834

---

packages/relay/src/lib/eth.ts
packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts

chore: cherry picked #2854

---

dapp-example/package-lock.json
dapp-example/package.json
package-lock.json

Cherry picked PR #2871 to release/0.54

chore: cherry picked #2871

---

.github/workflows/foundry.yml

ci: Updating the actions in the workflow to use the step-security version.
Fixes #2905 
**Checklist**

ci: Updating the workflows/actions to use the step-security version.

---

.github/workflows/acceptance-public.yml
.github/workflows/acceptance-workflow.yml
.github/workflows/acceptance.yml
.github/workflows/manual-testing.yml
.github/workflows/release-acceptance.yml
.github/workflows/test.yml

Updating several workflow actions to use the step-security version of the action.
Fixes #2904 
**Checklist**

ci: Updating actions to use step-security version 

---

docs/design/hbar-limiter.md

Adds a high-level flow diagram of how the limiter works in the existing design doc for the HBar limiter redesign.
Fixes #2968

docs: Add high-level flow diagram of the redesigned hbar limiter

---

.github/workflows/dev-tool-workflow.yml
.github/workflows/pr-label-milestone-check.yml

Updating our actions to pin full-length commit shas as checkout versions.
Fixes #2977
**Checklist**

ci: Updating workflow actions to use full commit sha.

---

packages/relay/src/lib/eth.ts

This is just the fix of a typo in the logged messages.
Fixes #3130 
**Checklist**

fix: Spelling fix in the logged messages.

---

packages/server/tests/acceptance/conformityTests.spec.ts
packages/server/tests/acceptance/data/conformity-tests-batch-5.json

Add tests for:
- 'eth_accounts'
- 'eth_coinbase'
- 'eth_gasPrice'
- 'eth_getUncleByBlockHashAndIndex'
- 'eth_getUncleByBlockNumberAndIndex'
- 'eth_getUncleCountByBlockHash'
- 'eth_getUncleCountByBlockNumber'
- 'eth_getWork'
- 'eth_hashrate'
- 'eth_maxPriorityFeePerGas'
- 'eth_mining'
Fixes #2725
**Checklist**

chore: add another batch of conformity tests

---

charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
charts/hedera-json-rpc/dashboards/webSocketServer.json

The HBar Rate Limiter counter panel had to be updated to reflect the ongoing Rate Limiter work.
Fixes #3145 
**Checklist**

feat: Updated dashboards due to on going HBar Rate Limiter work.

---

.github/workflows/release-integration.yml

This PR aims to fix an issue with the github workflow: `.github/workflows/release-integration.yml`
Currently its unable to upload the docker image due to missing permissions.
Fixes #3165 
**Checklist**

ci: Fixing workflow permissions for uploading docker images.

---

README.md
docs/testing-guide.md

docs: Add `testing-guide.md` to document testing best practices

---

.github/CODEOWNERS
.github/workflows/dapp.yml

Update per Q3 audit findings
Relates to #2732 
**Checklist**

ci: Update per Q3 audit findings

---

.github/workflows/flow-pr-title-check.yml

Fix check for forked repository on PR
Fixes #3223 
**Checklist**

ci: Fix check for forked repository on PR

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/tests/lib/mirrorNodeClient.spec.ts

chore: cherry picked #3254
Fixes #3254
**Checklist**

chore: cherry picked #3254 to release/0.56

---

.github/workflows/acceptance.yml
package.json
packages/relay/src/lib/constants.ts
packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
packages/relay/src/lib/services/hbarLimitService/index.ts
packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
packages/server/tests/acceptance/hbarLimiter.spec.ts

cherry picked #3252 to release/0.60
Fixes #3252
**Checklist**

chore: cherry pick #3252 to release/0.60

---

package-lock.json
package.json

The current version of local node is not the latest one.
Fixes #3243
**Checklist**

build(deps): bump `hedera-local` version from 2.32.2 to 2.32.5

---

packages/relay/src/lib/clients/mirrorNodeClient.ts
packages/relay/src/lib/clients/sdkClient.ts
packages/relay/src/lib/db/repositories/hbarLimiter/evmAddressHbarSpendingPlanRepository.ts
packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/services/hbarLimitService/index.ts
packages/relay/src/lib/services/metricService/metricService.ts

This PR sets debug level for improved visibility and easier troubleshooting in eth_sendRawTransaction
Fixes #3352 
**Checklist**

chore: set debug level for improved visibility and easier troubleshooting in eth_sendRawTransaction

---

packages/relay/src/lib/relay.ts

The rpc_relay_operator_balance metric was not reporting any value on Testnet because, in some cases, the account balance returned from the Mirror Node was a BigNumber object. Since the Prometheus client’s set() method only accepts standard JavaScript numbers, this led to errors and prevented the metric from being collected.
This PR updates the collect() method in the initOperatorMetric function to detect and convert BigNumber objects to JavaScript numbers, ensuring proper metric collection.
Fixes #3544
**Checklist**

fix(metrics): handled BigNumber values in operator balance metric

---

tools/whbar-hardhat-example/README.md

Add note to the WHBAR doc.
Fixes #3517
**Checklist**

feat: update `WHBAR` readme

---

packages/relay/tests/lib/utils.spec.ts

This PR addresses technical debt by adding test coverage for the arrangeRpcParams method, specifically for the special case of traceTransaction.
Fixes #3608

test: Add test coverage for traceTransaction parameter parsing logic

---

.github/workflows/image-build.yml
.github/workflows/release-integration.yml
.github/workflows/release-production.yml
Dockerfile

This PR fixes Docker image building after we migrated to Hiero. It looks like an issue with Docker images upstream. See for example https://github.com/docker/buildx/issues/314. In addition, as recommended by CI team, we also improved Docker cache usage, and remove build tools from the final image as this may cause problems.
Moreover, remove unused `OWNER` environment variable.
Fixes #3629.
**Checklist**

chore: fix Docker `libc-bin` issue

---

dapp-example/docker-compose.yml
docker-compose.yml
tools/subgraph-example/docker-compose.yml

**Description**
Updates the docker-compose.yml files in this repository to set specific image commit shas.
Closes #3638

chore: Update docker images to use specific commit shas as versions

---

.github/workflows/flow-pr-title-check.yml

Updates uses: step-security/conventional-pr-title-action to fix bug in 3.2.0
Fixes #3669
**Checklist**

fix: Update flow-pr-title-check.yml

---

packages/relay/src/lib/eth.ts
packages/relay/src/lib/services/contractService/ContractService.ts
packages/relay/src/lib/services/contractService/IContractService.ts
packages/relay/tests/lib/eth/eth_estimateGas.spec.ts

Moves estimateGas and getStorageAt to ContractService
Fixes #3571

refactor: moves estimateGas and getStorageAt to ContractService

---

README.md

docs: edited the badge and its link

---

packages/relay/package.json
packages/relay/src/index.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/services/ethService/blockService/BlockService.ts
packages/relay/src/lib/services/ethService/blockService/IBlockService.ts
packages/relay/tests/assertions.ts
packages/relay/tests/lib/eth/eth_getBlockReceipts.spec.ts
packages/relay/tests/lib/ethGetBlockBy.spec.ts

This PR makes improvement to the getBlockReceipts in order to boost performance. It also adds support for synthetic transactions
Fixes #3596

chore: Improves performance and adds synthetic transaction support to getBlockReceipts

---

dapp-example/src/components/AccountActivationForm.js

Added a check to ensure the amount is greater than zero, preventing transfers with invalid or zero amounts.
It's a community bug already fixed, but has been hanging out for a while. The user's PR https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/3588.
All credits are to @mdqst. Thank you for the great work!
Fixes #3794
**Checklist**

feat: add check for positive amount in dapp example

---

packages/relay/src/lib/dispatcher/rpcMethodDispatcher.ts

This PR promotes the request payload log entry to `INFO`.
Fixes #3948.
**Checklist**

feat: display request payload in log level `INFO`

---

.github/scripts/check-pr.js
.github/workflows/pr-label-milestone-check.yml

This PR uses Node's native `fetch` in the PR check workflow script and removes the `axios` dependency. It includes other improvements such as output with colors to highlight log messages, and collect all errors at once for better feedback.
In the workflow itself, the `axios` dependency is no longer installed. Additionally, the workflow uses Node 22 given it's the active version.
Fixes #3924.
N/A
N/A

chore: use Node's native `fetch` in PR check workflow

---

.husky/commit-msg
.husky/pre-commit
package.json

This PR removes the usage of the deprecate husky.sh file, in order to remove deprecation warnings and ensure that husky works properly
Fixes #4147

chore: removes deprecated husky lines

---

docs/openrpc.json
packages/relay/src/index.ts
packages/relay/src/lib/eth.ts
packages/relay/src/lib/services/ethService/ethFilterService/FilterService.ts
packages/relay/src/lib/services/ethService/ethFilterService/IFilterService.ts
packages/relay/tests/lib/openrpc.spec.ts

This PR improves the OpenRPC spec by including `errors` (and removing `result`) for those methods that always return "Unsupported Method".
Fixes #4173.
N/A
N/A

docs: indicate proper error codes for unsupported methods

---

.github/dependabot.yml

Need to restrict the npm weekly update group to patches only since the number of updated packages is very large and multiple minor updates can cause compatibility issues which are hard to isolate in very large dependabot PRs.
Fixes #4221 
1.
2.
3.
N/A
N/A

chore: refine npm weekly group updates

---

package-lock.json
packages/relay/package.json
packages/relay/src/lib/clients/cache/localLRUCache.ts
packages/ws-server/package.json
packages/ws-server/src/service/subscriptionService.ts

Bump lru-cache version.
`LimitedByCount` and `LimitedByTTL` are missing in the latest version, so we have to define our interface.
Fixes #4184
1.
2.
3.
N/A
N/A

build(deps): bump lru-cache from 7.14.0 to 11.1.0

---

packages/relay/src/lib/errors/JsonRpcError.ts
packages/relay/src/lib/precheck.ts
packages/relay/src/lib/services/ethService/transactionService/TransactionService.ts
packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
packages/relay/tests/lib/openrpc.spec.ts
packages/relay/tests/lib/precheck.spec.ts
packages/server/tests/acceptance/rpc_batch3.spec.ts

This PR refactors the `precheckSendRawTransactionCheck` method in the Precheck class for improved efficiency and code cleanliness:
- Reorders prechecks to perform cheaper validations first (before network calls)
- Simplifies the balance check logic by removing unnecessary object wrapping
- Removes unused parameters and excessive trace logging
- Renames variables for better clarity (e.g., `mirrorAccountInfo` to `signerAccountInfo`)
- Enhances error messages with more specific details (e.g., including transaction type in unsupported transaction errors)
Fixes #3721
N/A
N/A

refactor: optimize precheckSendRawTransactionCheck for improved efficiency and code cleanliness
