hiero-ledger/hiero-json-rpc-relay

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/relay/tests/test.env
- packages/server/tests/server.spec.ts
Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>
- Retrieve latest block number from the mirror node service
- Update `MIRROR_NODE_URL` in `test.env` to use `http`
Fixes #28 
- I have added `http` scheme to `test.env` file in order to connect properly to the local mirror node service, otherwise if its omitted, mirrorNodeClient instance uses `https` by default which points to invalid local mirror node URL
- With the above change, the test case `'baseUrl is exposed and correct'` in `mirrorNodeClient.spec.ts` was failing because it expects the production mirror node url to contains `https` scheme. So I removed the protocol scheme from the url before MirrorNodeClient is instantiated in order to test the same functionality. …
> Implement eth_blockNumber

- .prettierrc
- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/src/server.ts
Support block tag in APIs where tags like 'latest' can be substituted for numbers.
Fixes #90 
**Checklist**
> Support block tags in 5 APIs

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
The block tag fix introduced a regression where block numbers could
be requested by hex string.
Fixes #96 
**Checklist**
> Fix regression on hex block numbers

- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/mirrorNode.ts
- packages/relay/src/lib/model.ts
- packages/relay/tests/lib/eth.spec.ts
Previewnet testing highlighted scenarios where the r and s signatures were not set, as well as the fact that transactions in blocks weren't getting set.
- Guard against unset r and s signatures
- Replace async foreach with simple for and async to ensure transactions are set
- Split block caching logic out from Block Model
Fixes #97 
The Block caching logic should see an update that queries the mirror node based on transaction hash.
The exact response for a duplicate transaction needs to be considered.
**Checklist**
> Fix blocks transactions and r and s signatures assignments

- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/model.ts
- packages/relay/tests/lib/eth.spec.ts
Bring the getBlockBy... apis into compliance
* always use hex string instead of numbers
* use full hashes
* supply required fields
Fixes #99 
**Checklist**
> Bring getBlockBy... into execution-api schema compliance

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
Contract Calls were failing with insufficient fees and were blocking token transfers
- Add cost query logic
- Set query payment to this amount
Fixes #107 
We could explore setting this as a max or even less but lets start here to unblock us.
Test against preview net with local instance
**Checklist**
> Add cost call to avoid insufficient fee issue

- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/model.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/src/server.ts
- packages/server/tests/server.spec.ts
Fixes #
https://github.com/hashgraph/hedera-json-rpc-relay/issues/20
**Checklist**
> eth_getLogs

- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/mirrorNode.ts
- packages/relay/src/lib/relay.ts
- packages/server/src/server.ts
- packages/server/tests/acceptance.spec.ts
Improve server logging and metrics and minor issues noted from logging
- Add `latency` to server metrics
- Simplify metrics by removing single label options
- Move result conversion logic into `eth` and out of `server`
- Reduce verbosity of `mirrorNode` class 
- Add `Mirror` prefix to mirror node REST API calls
- Add `setTransactionId` to `CostQuery` to workaround `Query.PaymentTransactionId was not set duration execution` error for `CostQuery`
Fixes #131 
**Checklist**
> Improve server logging and metrics

- docker-compose.yml
Removes duplicate restart policy entry in the docker-compose file.
Fixes: #153 
**Checklist**
> chore: remove duplicate restart policy from docker-compose

- .github/workflows/release-production.yml
- Use explicit package name instead of full org path
- Move docker build flow above npm package in terms of priority
Fixes #159 
**Checklist**
> Remove org path from artifact build command

- package-lock.json
- package.json
- packages/relay/package.json
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/server/package.json
- packages/server/tests/acceptance.spec.ts
When updating the `getFeeWeibars()` to utilize the network as a backup flow to retrieve fees when the mirror node returns none, we regressed and lost the exchangerate retrieval logic.
- Restore exchange rate retrieval logic
- Move fee calculation to SDKClient
- Update sdk version to support added subtype and avoid error `(BUG) SubType.fromCode() does not handle code: 5`
Fixes #162 
Tested against previewnet
Again this PR would benefit from integration tests on SDKClient which are yet to come
**Checklist**
> Fix fallback gas fee calculation logic

- package-lock.json
- packages/server/package.json
- packages/server/tests/acceptance.spec.ts
Current acceptance test axios mirror node client and SDK clients always point locally.
- Add logic to configure SDK network accordingly
- Add logic to pick up MIRROR_NODE_URL environment variable
- Add axios-retry package to allow for retries since Mirror node won't immediately get info
Fixes #169 
**Checklist**
> Expand acceptance test to query external nodes

- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Given the fees don't change much we should cache the result for some time
- Add a cache key for feeHistory
- Add tests
Fixes #174
Tested local instance against previewnet
**Checklist**
> Cache eth_feeHistory inner value

- packages/server/src/server.ts
Capture latency correctly in prom-client
- remove latency from counter
- add latency to histogram
Fixes #176 
Tested against previewnet and wallet
Example output
```
rpc_relay_method_response_hist_bucket{le="0.005",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.01",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.025",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.05",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.1",method="eth_blockNumber",status="200"} 0
rpc_relay_method_response_hist_bucket{le="0.25",method="eth_blockNumber",status …
```
> Fix latency metric capture logic

- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Release 0.1 is missing cache logic for gas calls.
- Add cache for feeHistory
- Add cache for gasPrice
Related to #174 
**Checklist**
> Add gas cache logic to release 0.1

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/relay.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/server.spec.ts
Make startup logs more informative to relay configuration
- Add log for mirror node endpoint
- Add log for consensus node endpoint
- Add response log for Mirror Node calls
- Simplify mirror error response handling
- Remove getLogs server tests as it's not properly set up to work without proper mirror node mocking. COverage already in eth.spec.ts and acceptance tests
Fixes #186 
Could add sdkclient response calls but might need a refactor to make it easier and in one place like i did for acceptance tests.
Also generally SDKCLient calls pas or fail, they don't do supported errors
**Checklist**
> Improve startup logs

- packages/server/tests/acceptance.spec.ts
Work around for `eth_getBalance` results for primary account check
- Updated tests to check for a minimum
- Increase timeout period
- Do a local node restart to ensure there's a clean up of resources prior to a start
Workaround for #192 
Coverage exists via the secondary account check and contract balance check. This is simply test logic failure
**Checklist**
> Workaround for varying eth_getBalance acceptance test result on primary account

- .github/workflows/release-production.yml
- docker-compose.yml
- helm-chart/Chart.yaml
- helm-chart/values.yaml
- package.json
- packages/relay/package.json
- packages/server/package.json
- packages/server/tests/acceptance.spec.ts
- Bump release to 0.1.0
- Add exit command to acceptance test to ensure completion
- Cherry pick docker version fix on acceptance tests
Fixes #201 
**Checklist**
> Bump release to 0.1.0

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Signed-off-by: Mitchell Martin <mitch@swirldslabs.com>
Return the [proper transactionRoot](https://eth.wiki/json-rpc/API#:~:text=%22transactionsRoot%22%3A%20%220x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421%22%2C) if no transactions exist (instead of blockhash). 
Fixes #179
**Result with correct transactionsRoot**:
```
curl -X POST http://localhost:7546 \
-H 'Content-Type: application/json' \
-d '{"id":"2","jsonrpc":"2.0","method":"eth_getBlockByNumber","params":[21370223,true]}' --silent | jq
{
"result": {
"timestamp": "0x0",
"difficulty": "0x0",
"extraData": "0x",
"gasLimit": "0x0",
"baseFeePerGas": "0x0",
"gasUsed": "0x0",
"logsBloom": "0x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
> Fix transactionsRoot return value in case of empty transactions array

- .github/workflows/release-production.yml
Improve release git action
- Split docker and npm artifact out into separate jobs
- Fix npm package name in upload step
Fixes #204 
**Checklist**
> Improve release git action flow

- packages/server/tests/acceptance.spec.ts
- packages/server/tests/utils.ts
Add tests for the method `eth_getTransactionReceipt` for:
- Negative test for Legacy transaction - contains `value`, `gasPrice`, `gasLimit`, `to`, `nonce`
- Legacy 155 transaction - contains `value`, `gasPrice`, `gasLimit`, `to` and `chainId`, `nonce`
- London transaction - contains `value`, `maxPriorityFeePerGas`, `maxFeePerGas`, `gasLimit`, `to`, `chainId`, `nonce` and `type=2`
- Negative test for Legacy 2930 transaction - contains `value`, `gasPrice`, `gasLimit`, `to`, `chainId`and `type=1`
Fixes #
**Checklist**
> Acceptance tests for eth_getTransactionReceipt

- packages/relay/src/index.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/src/server.ts
Improve the transfer only gas cost.  If no data is detected return 21k
gas, which is the base tx fee.
for #166
**Checklist**
> Improve transfer-only gas estimate

- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/relay.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/relay/tests/lib/net.spec.ts
- packages/relay/tests/lib/web3.spec.ts
- packages/server/src/server.ts
- packages/server/tests/acceptance.spec.ts
Currently most logs and metrics focus on the `server` and `eth` classes.
This currently results in leaked info, verbose logs and little insight as to sdkClient and mirrorNode clients.
- Add loggers to sdkClient and mirrorNode clients
- Log responses with response codes
- Manage `NOT_SUPPORTED` errors from network
- Simplify stack trace error message since most client info isn't needed and shouldn't leak into `eth` and `server` logs
- Add a Histogram to capture sdkClient and mirrorNode clients responses
- Add a Gauge to track operator account costs to support alerting
Fixes #206 
**Checklist**
> Improve client logs and capture client metrics

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/src/server.ts
In some test suites we recreate client instances causes failures when registering a metric
- Add logic to clear metrics from registry before creating
Fixes #228 
**Checklist**
> Add logic to clear metric from registry before create

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/relay.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/clients/mirrorClient.ts
- packages/server/tests/clients/servicesClient.ts
Improve acceptance test runs
- Update `rpc.spect.ts`
- differentiate logs
- increase account1 balance to afford other transactions
- log configurations
- display test expense
- Shorten client logs
- Fix missed metric removal logic
- Trim `OPERATOR_ID_MAIN`
- Add timeout reset on mirror client
- add operator balance check
Fixes #243 
**Checklist**
> Improve acceptance tests run against remote instances

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/helpers/assertions.ts
`block.mixHash`, `block.receiptsRoot` and `block.stateRoot` should return hexes of 32byte formats
- Update `eth.ts` to use 32 bytes format
- Update `eth.spec.ts` to use 32 bytes format
- Updated `assertions`  to use 32 bytes format
Fixes #256 
**Checklist**
> Fix block root properties default hash formats

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/helpers/assertions.ts
There was a regression that lost the use of the `EthImpl.zeroHex8Byte`
Restore this
- Update `eth.ts` to use `EthImpl.zeroHex8Byte`
- Update `eth.spec.ts` to use `EthImpl.zeroHex8Byte`
Fixes #149 
**Checklist**
> Fix nonce zerohexbytes regression

- packages/relay/src/lib/clients/mirrorNodeClient.ts
Improve 500 response handling
- Update `MirrorNodeClient` to check for valid error response and handle absence
Fixes #261 
Flow now correctly displays
```
err: {
"type": "Error",
"message": "connect ECONNREFUSED 127.0.0.1:5551",
"stack":
Error: connect ECONNREFUSED 127.0.0.1:5551
at MirrorNodeClient.handleError (.../hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:106:27)
at MirrorNodeClient.<anonymous> (.../hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:94:22)
at Generator.throw (<anonymous>)
at rejected (.../hedera-json-rpc-relay/packages/relay/dist/lib/clients/mirrorNodeClient.js:25:65)
at processTicksAndRejections …
```
> Improve MirrorNodeClient 500 handling

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
`eth-getLogs` logic was grouping transactions via `contractId-timestamp`.
This resulted in logs getting missed since the contractId of logs from called contracts differ from the caller
- Update `eth_getLogs` call to group log results via timestamp to determine unique executions
- Update integration tests
- Updated acceptance test image versions
Fixes #268
**Checklist**
> 268 fix get logs

- README.md
- packages/relay/src/lib/errors.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/clients/mirrorClient.ts
- packages/server/tests/clients/relayClient.ts
- packages/server/tests/helpers/assertions.ts
Adds a precheck for `chainId` in `eth_sendRawTransaction`. If the `chainId` in the submitted transaction is different than the one specified in the relay environment an error is thrown: `-32000: ChainId not supported`
Fixes #:
https://github.com/hashgraph/hedera-json-rpc-relay/issues/129
**Checklist**
> ChainId precheck

- packages/relay/src/lib/errors.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>
Fixes #127 
**Checklist**
> Add gas precheck to eth_sendRawTransaction

- packages/relay/src/lib/errors.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/clients/relayClient.ts
- packages/server/tests/clients/servicesClient.ts
- packages/server/tests/helpers/assertions.ts
* Add balance precheck
* Add optional chaining to `getTransactionByHash` for null value of `contractResult.to` causing "multiple done() method invoked" error in acceptance tests
* Refactor `jsonRpcError` assertion to accept predefined error object
Fixes #130 
**Checklist**
> Add balance precheck to eth_sendRawtransaction

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/src/lib/relay.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/clients/relayClient.ts
Improve logging metrics and error handling
- Update balance metric to show operator id
- Fix some logging issues
- Add api callerName to sdkClient metrics to allow for cost per API analysis
- Fix issues around contract results revert and empty results scenarios from mirror node
Fixes #272 
**Checklist**
> Improve logging, metrics and error handling

- package-lock.json
- packages/relay/package.json
- packages/relay/src/lib/clients/sdkClient.ts
- packages/server/package.json
- packages/server/tests/acceptance/rpc.spec.ts
Support `eth_sendRawTransaction` for large Ethereum TXs
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/15
**Checklist**
> Implement eth_sendRawTransaction for large Ethereum TXs

- helm-chart/templates/deployment.yaml
- helm-chart/templates/secret.yaml
- helm-chart/values.yaml
Cleanup the way CHAIN_ID is set and transported into the k8s deployments.  Hex numbers are often converted (or attempted to be converted) and this makes the code return 0xNaN as the CHAIN_ID.  Moving away from setting this in a k8s secret because there is less conversion/encoding.
Fixes #300
> Helm chart chain id fix

- dapp-example/tests/support/bootstrap.js
Add backup logic to generate keys as part of the flow
Fixes #319 
**Checklist**
> Add backup logic to generate keys as part of the flow

- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/model.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/helpers/assertions.ts
Move uints back to hex strings
Fixes #302
**Checklist**
> Align receipt with execution apis

- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/clients/servicesClient.ts
> HTS acceptance tests

- README.md
Readme update to use the helm repo instead of the existing helm-charts directory.  Helm repo allows for multiple versions to be stored.
> readme updated with new instructions for installing the helm chart

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/337
**Checklist**
> Align log with execution apis

- README.md
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/clients/relayClient.ts
- packages/server/tests/clients/servicesClient.ts
- packages/server/tests/helpers/assertions.ts
Signed-off-by: Ivo Yankov <ivo@devlabs.bg>
Adjust the acceptance tests so that they run consistently against Testnet and Previewnet.
Some tests were failing with error `-32009: Gas price too low` due to a higher gas price on the public networks than the default hardcoded one that is used when testing against the local node.
When testing against Previewnet it turned out that the `chainId` value in the README was incorrect.
Fixes #340 
**Checklist**
> Ensure acceptance tests run on previewnet/testnet

- dapp-example/tests/e2e/index.spec.js
Signed-off-by: Anton Rusev <anton.rusev.code@gmail.com>
Fixes #347 
**Checklist**
> Metamask window does not popup on DApp tests

- README.md
- docs/rpc-api.md
The Relay currently doesn't have a quick reference of support endpoints and request steps.
An Open RPC spec will be added for greater detail but a simple table with basic information may be useful
Add an `rpc-api.md` to highlight
- types of methods
- basic request and response structure
- endpoint table
Fixes #137 
**Checklist**
> Add RPC API endpoint table

- package.json
- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/clients/servicesClient.ts
The acceptance tests suite is large.
In non-local envs this case result in expensive tests
- Add a `@release` tag to core happy path tests
- Add npm run command support to kick off filtered tests 
Fixes #
**Checklist**
> Add release acceptance tests tag support

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/helpers/assertions.ts
Cherry-pick #338 to release/0.4
Update transaction response integers to be hexadecimal like ethereum execution apis schema
Fixes #338 
**Checklist**
> Align transaction with ethereum execution apis (0.4)

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
CHerry-pick #337 to release/0.4
Update log response integers to be hexadecimals
Fixes #337 
**Checklist**
> Align log with execution apis (0.4)

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/erc20.spec.ts
* 
Cherry pick #375 
When a from value is in the eth_call params, set it to the senderId.
Fixes #373 
**Checklist**
> Support 'from' in 'eth_call' (0.4)

- docs/openrpc.json
Adds the `blockHash` filter for eth_getLogs in `openrpc.json`
Fixes #376 
**Checklist**
> Document the blockHash filter for eth_getLogs

- .github/workflows/postman.yml
- packages/server/tests/postman.json
Postman newman tests can be used to make multipl quick rpc calls to an endpoint.
The current solution is missing a few consensus node hitting calls
- Add `eth_gasPrice`
- Add `eth_feeHistory`
- Update `postman.json` to use `baseUrl`
- Add github action to run newman script
Fixes #392 
**Checklist**
> Increase newman postman tests coverage

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/index.spec.ts
`eth_getCode` makes a request to the mirror node. In the case of an empty result (`0x`) or if the contract has not yet been propagated to the mirror node the bytecode is retrieved from consensus.
Fixes #27 
**Checklist**
> Query mirror node for deployed_bytecode in eth_getCode

- packages/server/tests/acceptance/rpc.spec.ts
Fixing two tests with these changes. Another one was fixed here https://github.com/hashgraph/hedera-sdk-js/pull/1224. 
Logic behind fix for test: `should call eth_feeHistory with updated fees`
In the before hook, we are feeding default fees to the mirror node. So that we know how many blocks we should take and where to expect those fees. But if there is discrepancy in the blocks, the first element in this array is taken from the consensus node, not from the mirror node. This is the reason sometimes this value in the first index is wrong.
Logic behind fix for test: `should call eth_feeHistory with newest block > latest`
By the time we're requesting the last block, it's already ahead by one. So we were excepting it to be 10 ahead, but it's actually 11 ahead on rare …
> test: Acceptance tests seems inconsistent

- tools/README.md
> Add comparison analysis table for supported tool

- packages/relay/src/lib/eth.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/helpers/assertions.ts
Fix issues with values returned from `getBlocks`: `timestamp` and `gasLimit`.
- Changes `timestamp` logic to be always the start of the period, returned by the mirror node at `/api/v1/blocks/:hashOrNumber`
- Changes `gasLimit` to be hardcoded as 15000000
- Returns the `gas_used` field from `/api/v1/blocks/:hashOrNumber` as `gasUsed` instead of calculating the gas sum of all contract results in the block.
Fixes an issue, described in a comment in [414#issuecomment-1207980112](https://github.com/hashgraph/hedera-json-rpc-relay/issues/414#issuecomment-1207980112)
**Checklist**
> Resolve issues with some fields in eth_getBlock

- docker-compose.yml
- docs/openrpc.json
- helm-chart/Chart.yaml
- package-lock.json
- packages/relay/package.json
- packages/server/package.json
- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/htsPrecompile.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- Bump 0.6.0-rc1
- Add waits in acceptance tests to make sure mirror node has account info
Fixes #
**Checklist**
> Bump 0.6.0-rc1

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/server/src/server.ts
- packages/server/tests/helpers/assertions.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/postman.json
Add trace id to error response messages.  
There is no obvious place to return the trace id when the call is successful without changing the schema.
Fixes #431 
**Checklist**
> add trace id to error response messages

- helm-chart/environments/minikube.yaml
- helm-chart/templates/configmap.yaml
- helm-chart/templates/deployment.yaml
- helm-chart/templates/service.yaml
- helm-chart/values.yaml
This PR
* Adds support for YAML and JSON annotations on the service
* Includes readiness and liveness probes to the deployment
* Updates to the configmap `config.HEDERA_NETWORK` logic and coinciding values.yaml comments
* Removed top-level `secrets.` from value.yaml, this was not ever being called or used
Fixes #
```
Deployment templating:
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: test-hedera-json-rpc-relay
labels:
app:  hedera-json-rpc-relay
helm.sh/chart: hedera-json-rpc-relay-0.7.0-SNAPSHOT
app.kubernetes.io/name: hedera-json-rpc-relay
app.kubernetes.io/instance: test
app.kubernetes.io/version: "0.7.0-SNAPSHOT"
app.kubernetes.io/managed-by: Helm
spec:
replicas: 1
selector:
matchLabels:
app.kubernetes.io/name: …
```
> Health checks svc annotations

- .github/workflows/acceptance.yml
- dapp-example/src/components/ContractInteractions.js
- dapp-example/tests/e2e/index.spec.js
- dapp-example/tests/support/bootstrap.js
- package.json
- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/htsPrecompile.spec.ts
- packages/server/tests/acceptance/htsPrecompile_v1.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/helpers/prerequisite.ts
- Split acceptance tests into separate jobs
- Add a timeout to ensure local-node has started up first
Fixes #514 
Fixes #520
**Checklist**
> Split acceptance tests into separate jobs

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- tools/hardhat-example/test/rpc.js
`eth_getBalance` currently uses the consensus nodes to retrieve balance since mirror node only update balance every 15 mins.
With mirror node fix to update on transfers relay can now point to mirror node
- Update `eth_getBalance` logic to call Mirror Node /api/v1/accounts` endpoint and extract balance
- Fix metric discrepancy on `resolvedCost`
- Update sdkClient flow to remove unnecessary error check since default is UNKNOWN
Fixes #448 
**Checklist**
> Update eth_getBalance to use mirror node

- packages/relay/src/lib/clients/sdkClient.ts
Log details about the file created for callData when calling a transaction. 
Fixes #540 
**Checklist**
> Log fileId and file size for callData

- packages/relay/src/lib/clients/sdkClient.ts
Cherry pick changes for logging calldata information to release/0.8
Fixes #540 
**Checklist**
> 540 capture calldata cp

- packages/relay/src/lib/eth.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
Currently we are returning the long-zero address in the from field.  We need to return the evm address for the account if one exists.
Fixes #505
> return the evm address in the from field when calling getTransactionByHash

- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/helpers/prerequisite.ts
Bump 
- services 0.3
- mirror 0.65.0-beta1
Fixes #543 
**Checklist**
> Bump services 0.30 and mirror 0.65.0-beta1

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
Update eth_transactionaccount to use mirror node
Cherry pick #552 to release 0.8
Addresses #550 
**Checklist**
> Update eth_transactioncount  to use mirror (0.8)

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/precheck.spec.ts
Cherry pick https://github.com/hashgraph/hedera-json-rpc-relay/pull/535 to release/0.8
nonce precheck logic is currently missing some logic and logs
- add log to show nonce value to help better inform WRONG_NONCE errors observed
- Update RESOURCE_NOT_FOUND error to allow for resource details
- Add nonce precheck test cases for better coverage
- break out account check from nonce check
- add account check tests cases
- simplify nonce precheck logic
- clean up orphaned references observed
Fixes #534 
**Checklist**
> update nonce precheck logic (0.8)

- docker-compose.yml
- docs/openrpc.json
- helm-chart/Chart.yaml
- package-lock.json
- packages/relay/package.json
- packages/server/package.json
Bump 0.8.0-rc2
Fixes #
**Checklist**
> Bump 0.8.0-rc2

- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/server.ts
Initialise Koa server in Koa Json RPC class, no need to be separate.
Fixes #530 
**Checklist**
> Improve Koa and KoaJsonRpc classes

- .github/workflows/acceptance.yml
- package.json
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/hbarlimiter/index.ts
- packages/relay/tests/lib/hbarLimiter.spec.ts
- packages/server/tests/acceptance/rateLimiter.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- Adds unit tests with 100% coverage for new HBAR Rate Limit functionality
- Move all rate limit acceptance tests in one file
Fixes #582 
**Checklist**
> Unit tests for HBAR Rate limit

- package-lock.json
- packages/relay/package.json
- packages/relay/src/lib/clients/sdkClient.ts
- packages/server/package.json
Add TransactionRecordQuery calls to capture fail transaction costs
- update `executeTransaction` catch with `TransactionRecordQuery` logic
- update `executeGetTransactionRecord` catch with `TransactionRecordQuery` logic
Fixes #592 
**Checklist**
> Add TransactionRecordQuery calls to capture failed transaction costs

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Return `EthImpl.emptyBloom` if `receiptResponse.bloom == EthImpl.emptyHex` when returning `eth_getTransactionReceipt` response
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/599
**Checklist**
> Handle empty hex bloom in eth_getTransactionReceipt

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Return `0x0` when contract result query returns  `null` for `gas_used`
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/606
**Checklist**
> Handle null `gas_used` from contract results

- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/helpers/prerequisite.ts
Bump local node images for acceptance tests 0.31.A
- `NETWORK_NODE_IMAGE_TAG` & `HAVEGED_IMAGE_TAG` to `0.31.0-alpha.3`
- `MIRROR_IMAGE_TAG`  to `0.66.1`
Fixes #618 
**Checklist**
> Bump local node acceptance test images for 0.31.A

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/hbarlimiter/index.ts
- packages/relay/tests/lib/hbarLimiter.spec.ts
- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/koaJsonRpc/lib/RpcError.ts
- packages/server/src/ratelimit/index.ts
- packages/server/src/server.ts
Add logging and metrics to rate limit logic
- Add log to user method limit
- Add log to budget limit
- Add metric to method limit
- Capture methodName in user method limit
Fixes #621 
**Checklist**
> Add logging and metrics to rate limit logic

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Update eth_getCode to handle call to iHTS address.
This will support eth dev tool calls to `address(0x167)`
- Add catch case for contract type and `address(0x167)`
- Add test cases
Fixes #628 
Q: Should I add support for `address(0x168)` and `address(0x169)` precompiles
Code would become
```
if (address === EthImpl.iHTSAddress || address === EthImpl.iExchangeRateAddress || address === EthImpl.iPrngAddress) {
this.logger.trace(`${requestIdPrefix} precompile case, return ${EthImpl.invalidEVMInstruction} for byte code`);
return EthImpl.invalidEVMInstruction;
}
```
Ans: We'll leave it till it's requested. Would also be better once Mirror EVM Archive Node is functional …
> Update eth_getCode to handle call to iHTS address

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/server/src/koaJsonRpc/index.ts
- packages/server/tests/acceptance/rateLimiter.spec.ts
If env variable `LIMIT_DURATION` is not set, rate limit duration is NaN and can't reset. Now defaults to `60000 ms`, if it's not set.
Fixes #623 
**Checklist**
> Fix rate limit not reseting

- packages/relay/src/index.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/openrpc.spec.ts
Fix eth_getTransactionByBlockHashAndIndex and eth_getTransactionByBlockNumberAndIndex transaction index param not being converted from hex to decimal when querying the mirror node
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/634
**Checklist**
> Fix transaction index param

- .github/workflows/dapp.yml
- dapp-example/.gitignore
- dapp-example/src/App.js
- dapp-example/src/components/AssociateHTSTokensForm.js
- dapp-example/src/contracts/HederaTokenService.json
- dapp-example/tests/e2e/index.spec.js
- dapp-example/tests/support/bootstrap.js
> Add a HTS token association example to DApp example

- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/errors/MirrorNodeClientError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/server/src/server.ts
- packages/server/tests/clients/relayClient.ts
- packages/server/tests/helpers/assertions.ts
1. Better handle timeout errors - Currently any error that does not have a `response` property is handled as `unknownServerErrorHttpStatusCode` (567), but `axios` provides `error.code` that indicate (I'm assuming server side errors) for example `ECONNABORTED` for timeouts. Handling those errors as `unknownServerErrorHttpStatusCode` would sometimes result in test passing for the wrong reason, because other errors, like `no mock for ... detected` would also fail with status code `567`. Also update the tests to check the error message.
2. There were couple of cases when `404 not found` responses were not handled correctly and resulted in the code breaking because it was trying to access properties of `null` values. For example here …
> Better error handling

- package-lock.json
- packages/relay/package.json
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Replace `js-cache` with `lru-cache`. A cache object that deletes the least-recently-used items with customisable options.
Options currently set during initialization are:
- `max` - The maximum number (or size) of items that remain in the cache (assuming no TTL pruning or explicit deletions).
- `ttl` - Max time to live for items before they are considered stale.
Fixes #658 
**Checklist**
> Replace js-cache with lru-cache

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
> Use evm_address from mirror node query of recently deployed contracts to populate the transaction receipt result

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
It seems occasionally `transaction_index` can be undefined from mirror node.
Currently the relay throws errors in this case.
While we figure out why
- add logic to manage undefined transaction_index
- add tests
Fixes #
**Checklist**
> Add logic to handle missing transaction index

- package-lock.json
- package.json
- packages/relay/package.json
- packages/server/package.json
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/helpers/prerequisite.ts
Bump image versions for tests and sdk versions
- hedera-local - 2.1.3
- lerna - 6.0.3
- sdk - 2.18.6
- mirror node - 0.67.3
Fixes #
Mirror node image above 0.67.3 is not working.
Network image 0.32.0-alpha.4 is not working.
**Checklist**
> Bump test images version and SDK version

- packages/server/src/server.ts
- packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
- packages/server/tests/acceptance/htsPrecompile/tokenManagement.spec.ts
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/helpers/prerequisite.ts
- Bump network node image version to `0.32.0`
- Bump mirror node image version to `0.69.0`
- Fix health/readiness always `DOWN`
- `setApproveForAll` action is not working with this image.
- `updateTokenInfo` tests changed to update only token info, not token keys.
Fixes #716 
Fixes #720 
Should we delay this PR until all issues with test are resolved and new images are available or merge it and open new issues to track and fix all pending tests ?
**Checklist**
> Bump Test Images version

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Handle the case when the state_changes field returned as an empty array. 
Fixes #732
> Handle empty state_changes array in contract details

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Return 32 byte 0 string when the returned state_changes array is empty.  This is similar behavior to other test chains.
Fixes #732
> Return 32 byte 0 on empty state_changes array

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Checks if `to` parameter is passed in `eth_call` method, before checking it's length. 
Fixes #742 
**Checklist**
> Check `to` parameter in `eth_call` method

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Changes behaviour of `eth_getLogs` to add topics in the parameters passed to the mirror node, only if they exist and are not undefined or null.
Fixes #711
**Checklist**
> Events not returned on getPastEvents call

- packages/server/tests/helpers/assertions.ts
- packages/server/tests/helpers/nodeCheck.ts
- packages/server/tests/integration/server.spec.ts
- tools/subgraph-example/README.md
Adds custom messages in cases with multiple expect/asserts for better traceability
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/774
**Checklist**
> Add custom error message for better traceability for multiple asserts

- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/koaJsonRpc/lib/RpcResponse.ts
- packages/server/tests/clients/relayClient.ts
- packages/server/tests/helpers/prerequisite.ts
- packages/server/tests/integration/server.spec.ts
Currently we return 200 status code in most cases. This PR updates the relay to return the appropriate codes:
InternalError => 500
InvalidParams (JsonRpc request params) => 400
MethodNotFound or UnsupportedMethod => 400
RateLimit => 429
JsonRpcError =>  500 for InternalError, 400 for the rest
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/751
**Checklist**
> Return appropriate http codes

- packages/relay/src/lib/eth.ts
Remove cache on getBalance, when account doesn't exist, because after HIP 583 we can create accounts via metamask, which asks for balance, before creation and can get stuck on 0.
Fixes #815
**Checklist**
> Fix cache on getBalance

- package-lock.json
- package.json
- packages/relay/src/lib/eth.ts
- packages/server/package.json
- packages/server/src/validator/constants.ts
- packages/server/src/validator/methods.ts
- packages/server/src/validator/objectTypes.ts
- packages/server/src/validator/types.ts
- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/helpers/prerequisite.ts
- packages/server/tests/integration/server.spec.ts
Expand `eth_call` validation to support `blockParam` object, introduced with [EIP-1898](https://eips.ethereum.org/EIPS/eip-1898). The Graph is passing blockHash as parameter and currently validations only accepts `blockNumber` or `tag`. More info can be found in this issue from this [comment](https://github.com/hashgraph/hedera-json-rpc-relay/issues/626#issuecomment-1383554578) onwards.
Fix some minor intermittent bugs in ERC20 tests.
Bump network images to `0.33.2` and mirror-node images to `0.72.0`.
Fixes #816 
**Checklist**
> Expand `eth_call` validation to support blockParam object

- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/helpers/prerequisite.ts
Bump acceptance test node images to:
- Network node: 0.35.0-alpha.1
- Mirror node: 0.73.0-rc1
Fixes #
**Checklist**
> Bump acceptance test node images

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Do not make additional calls to the mirror node unnecessarily when `showDetails` parameter is false.  The transaction hash is already available in the result set from the first call to retrieve contractResults.
In the example in issue #827, the block contained 100 contract results.  Iterating over them when details were not asked for was needlessly costly.
Fixes #840 and #827 (the particular use case in this issue)
**Checklist**
> Remove unnecessary call when details not requested

- packages/server/src/validator/objectTypes.ts
- packages/server/tests/acceptance/rpc.spec.ts
Fixes bug with validations when using the relay with metamask or foundry, which resulted in returning and error when making queries to `eth_estimateGas`.
Fixes #
**Checklist**
> Fix validations for estimateGas

- packages/relay/src/lib/eth.ts
- packages/server/src/validator/objectTypes.ts
- packages/server/src/validator/utils.ts
- packages/server/tests/acceptance/rpc.spec.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/integration/validator.spec.ts
MM seems to send a null data param in the transaction object.
We should not be validating in that case.
- Expand trace logs to `eth.estimateGas()` to highlight param
- Add nullable concept to validation object params and set data in transaction object to nullable
- Expand `predefined.INVALID_PARAMETER` logs to make failures easier to troubleshoot
- Updated and expanded tests to confirm `isValidAndNonNullableParam` logic
- Updated RPC tests impacted by addition of value to the log
Fixes #836 
**Checklist**
> Add nullable check to estimateGas validation

- docs/openrpc.json
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/helpers/assertions.ts
Response from `eth_feeHistory` is a object with several properties, one of which is `gasUsedRatio`. Until now it was returned as array of string (hex encoded integer), which seems to be wrong as tools like Foundry are expecting array of numbers. More so providers like Alchemy and Infura are also returning array of integers.
Fixes #835 
Resolves #834 
**Checklist**
> Return array of numbers in `eth_feeHistory` response

- docker-compose.yml
- docs/openrpc.json
- helm-chart/Chart.yaml
- package-lock.json
- packages/relay/package.json
- packages/server/package.json
Bump version to 0.16.0 for general availability release
> ga release for 0.16.0

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
> eth_feeHistory invalid cached response

- package-lock.json
- packages/server/package.json
- packages/server/src/formatters.ts
- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/rateLimit/index.ts
- packages/server/src/server.ts
This PR modifies rate limited logs in order to include the requestId in a standard log message.
Adds a Koa requestId package that supports storing the requestId in the application context.
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/pull/885
Notes for reviewer:
Provides the request ID in the logs right as the rateLimit for a given IP is triggered, in the standard log format.
Existing tests cover rateLimited requests.
> 865-update-logs-and-metrics.  Added the requestId to the server context.

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
While deploying contracts with truffle, I've noticed that there multiple requests for the same block number, which makes requests for gasPrice and contract results for this block. When this requests is with the same block number, there is no need to call the mirror-node every time, we can just cache it after the first attempt.
**Solution**:
Trace all requests from getBlockByNumber and cache where possible.
Fixes #905
**Checklist**
> Add cache to eth_getBlockByNumber

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
This PR changes the current `eth.ts` behaviour in `getTransactionFromContractResult` and `getTransactionByHash` to return `0x0` instead of `null` when `v` is `null`
Fixes #916 
**Checklist**
> Change `v` field in `eth_getTransactionByHash` and `eth_getBlockByHash` to be zeroHex instead of `null`

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/integration/server.spec.ts
Added LRU in memory cache to mirrorNodeClient --> getContractResult method, so when calling /contracts/results/ of the mirror node the relay can save the response on cache for subsequent uses by both getTransactionByHash and getTransactionReceipt
Fixes #900 
**Checklist**
> Add cache to Mirror Node Client getContractResult method.

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
Adding validation for checking if From is a valid account address and To is a valid contract or HTS address
Fixes #984 
We are only checking if the "From" address is valid if is different from blank, since there are some Acceptance Tests that imply that "From" could be missing and still expect a response from eth_call
https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/server/tests/acceptance/rpc_batch3.spec.ts#L124
While doing some research and tests, "From" field is indeed [optional](https://docs.alchemy.com/reference/eth-call), however if is included and is invalid, we get the error from consensus node that we are trying to avoid with this PR/Improvement.
**Checklist**
> Check for Valid To and From Addresses on eth_call

- packages/server/tests/acceptance/ws/subscribe.spec.ts
- packages/ws-server/src/webSocketServer.ts
Handles `JSON.parse(msg.toString('ascii'))` Exception, so the ws-server does not crash due to an invalid request that is not a parseable JSON.
Return INVALID_REQUEST that is existing in current JsonRpcError Collection
```json
{
"code": -32600,
"name": "Invalid request",
"message": "Invalid request"
}
```
Fixes #985 
**Checklist**
> Invalid Json Crashes WS-Server Fix

- docker-compose.yml
- docs/openrpc.json
- helm-chart/Chart.yaml
- package-lock.json
- packages/relay/package.json
- packages/server/package.json
- packages/ws-server/package.json
bump version 0.20.0 for GA release
https://github.com/hashgraph/hedera-json-rpc-relay/issues/1010
> GA release 0.20.0

- packages/server/tests/acceptance/ws/subscribe.spec.ts
Acceptance Tests for eth_subscribe, connect, disconnect, subscribe, unsubscribe and multiple subscriptions at once
Fixes #944 
Right now that latest test case is failing, due to what I believe is a [bug](https://github.com/hashgraph/hedera-json-rpc-relay/issues/988), will work on that and update the PR.
**Checklist**
> Acceptance Tests for eth_subscribe, connect, disconnect, subscribe, unsubscribe and multiple subscriptions at once

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/helpers/prerequisite.ts
With the extension of state endpoint in the mirror-node, we can now fetch and return not only the current state, but older. This PR makes the necessary changes to enable this and removes the usage of the old endpoint as it is no longer needed.
Bump mirror-node version, because the needed change for this feature is in 0.77
Fixes #790 
**Checklist**
> Enable `eth_getStorageAt` to return older state

- scripts/.bump-version.js
Originally the script was bumping files using `js-yaml` library, but that was re-creating the whole file and using its own standards as to where to use ' " or nothing, and in order to avoid unintended changes we decided to use regex and replace for all files, so we don't modify unintended fields on yaml files
Fixes #
Script was used to modify the files on this 2 PRs:
RC:
```
npm run bump-version --semver=0.20.0-rc1 --snapshot=false
```
https://github.com/hashgraph/hedera-json-rpc-relay/pull/1002
Snapshot:
```
npm run bump-version --semver=0.21.0-SNAPSHOT --snapshot=true
```
https://github.com/hashgraph/hedera-json-rpc-relay/pull/1000
> bump-version script improvements

- packages/server/tests/acceptance/rpc_batch3.spec.ts
This PR updates the rcp_batch3.spec, "007 'data' from request body with wrong encoded parameter" to use an invalid address in the "wrong encoded parameter" as the old address on previewnet was getting used accumulating a balance.
> Test fix for release 0.21.0-rc1.  Updated test to use invalid account

- package-lock.json
- package.json
- packages/server/package.json
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/helpers/prerequisite.ts
This PR bumps acceptance test network image to `0.37.0-alpha.0` and mirror-node images to `0.78.0-beta.1` . 
Also bump local-node and sdk packages
Fixes #
**Checklist**
> Bump Acceptance Tests network images

- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/errors/SDKClientError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
This PR adds a new mirror node request method, to get transaction by transaction id. This way we can get the contract revert reason. Log this error in the relay log. This makes debugging easier as developers won't have to query manually the mirror-node for every failed test.
Fixes #
Before:
```
[2023-04-10 13:05:35.167 +0000] DEBUG (consensus-node/64638 on Georgis-MacBook-Pro-4.local): [Request ID: dc1a5684-a602-43ed-8151-07c42e79f3d1] 0.0.2@1681131924.595436653 eth_sendRawTransaction EthereumTransaction record status: CONTRACT_REVERT_EXECUTED (33), cost: 0.568 ℏ
[2023-04-10 13:05:35.934 +0000] ERROR (relay-eth/64638 on Georgis-MacBook-Pro-4.local): [Request ID: dc1a5684-a602-43ed-8151-07c42e79f3d1] Failed sendRawTransaction …
```
> Extract and Log Contract Revert Reason

- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/errors/SDKClientError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
Cherry-picks: 
https://github.com/hashgraph/hedera-json-rpc-relay/pull/1043
> Cherrypick - Extract and Log Contract Revert Reason (#1043)

- packages/server/tests/acceptance/rpc_batch1.spec.ts
---------
Cherry pick #1050 
* changed the hardcoded value of "blocksBehindLatest" from 40 to 10, since is enough for the purpose of the test and gives higher chances that even if the tests and the hardware used to run the tests improves in the future, the test will continue to work.
* adding comments to change
* further improve test to fetch from beginning in case currentBlock is less than 10
* avoid double call of eth_blockNumber
Fixes #
**Checklist**
> RPC API Batch 1 - Acceptance Test - Improvement (#1050)

- packages/relay/src/lib/clients/mirrorNodeClient.ts
Currently the axios requests don't utilize HTTP configurations that may help increase performance
- Add env config for keepAlive. Set in httpsAgent and httpsAgent.
- Add env config for keepAliveMsecs. Set in httpsAgent and httpsAgent.
- Add env config for maxSockets. Set in httpsAgent and httpsAgent.
- Add env config for maxTotalSockets. Set in httpsAgent and httpsAgent.
- Add env config for timeout. Set in httpsAgent and httpsAgent.
Fixes #1081 
**Checklist**
> Add http Agent support with Keep Aiive configs

- packages/server/src/validator/objectTypes.ts
- packages/server/tests/acceptance/ws/subscribe.spec.ts
- packages/server/tests/integration/validator.spec.ts
- packages/ws-server/src/webSocketServer.ts
Added objectTypes ethSubscribeLogsParams that contains the logic for validation of ethSubscribe method logs params.
Unit tests for new validation ObjectType
Acceptance test for new validations
Fixes #1045 
**Checklist**
> Sanity check of ethSubscribe Logs Params

- packages/relay/src/lib/clients/sdkClient.ts
SDKClient drops the original error message message.
- Add original error message in SDKCLient constructor
Fixes #1090
Prior to fix
```
err: {
"type": "SDKClientError",
"message": "",
"stack":
Error:  at SDKClient.<anonymous> (./hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:82:40)
at Generator.next (<anonymous>)
at ./hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:27:71
at new Promise (<anonymous>)
at __awaiter (./hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:23:12)
at SDKClient.executeQuery (./hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:54:90)
at SDKClient.<anonymous> (./hedera-json-rpc-relay/packages/relay/dist/lib/clients/sdkClient.js:252:25) …
```
> Restrore dropped SDKClient error message

- helm-chart/templates/deployment.yaml
- helm-chart/values.yaml
Currently liveness and readiness probes where missing default seconds
To the liveness and readiness probes
- Add initialDelaySeconds
- Add periodSeconds
- Add timeoutSeconds
- Add failureThreshold
Fixes #1092 
**Checklist**
>  Add default seconds to liveness and readiness probes

- docs/configuration.md
- docs/examples/.env.mainnet.sample
- docs/examples/.env.previewnet.sample
- docs/examples/.env.testnet.sample
- packages/relay/src/lib/relay.ts
This PR modifies `docs/configuration.md` in order to support devs who would like to configure the RPC relay server for testnet
* Use lowercase values for `HEDERA_NETWORK` config property (uppercase results in [this error](https://stackoverflow.com/q/76069712/194982)
* Added a sample complete `.env` file required to connect to Hedera Testnet
* N/A
* [internal discussion](https://swirldslabs.slack.com/archives/C0361991PGD/p1682042148026939)
**Checklist**
- tested manually
> docs: changed HEDERA_NETWORK values to lowercase + sample for testnet

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
CHerry pick #1122 
Expand eth_call mirror node consensus retry scenarios
- Move consensusNode call in catch out to apply to all error cases 
- Split mirror node call case into separate method with catch including consensus call 
- Add toNullableBigNumber to manage value conversion 
- Add getCappedBlockGasLimit to manage block gas limit max
Fixes #
**Checklist**
> Cherry-pick: Expand eth_call mirror node consensus retry scenarios (#1122)

- packages/relay/src/lib/errors/MirrorNodeClientError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
This PR adds a temporary workaround for empty response from mirror-node `eth_call`. If `result: 0x` is returned, we fallback to consensus-node.
Fixes #1130 
**Checklist**
> Add `eth_call` workaround for mirror-node empty response

- packages/relay/src/lib/errors/MirrorNodeClientError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
> Cherry-Pick: Add `eth_call` workaround for mirror-node empty response (#1132)

- .github/workflows/subgraph.yml
This PR adds a new step in the subgraph CI workflow, which generates the necessary types before starting the graph node and deploy the subgraph.
Also there is a bug in node version 18.16 (latest) which is being used here. This results in hardhat not being able to download the compiler and exiting with exitcode 0. More info [here](https://github.com/NomicFoundation/hardhat/issues/3877)
Fixes #1143 
**Checklist**
> Fix flaky subgraph test

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/tests/lib/errors/JsonRpcError.spec.ts
- packages/relay/tests/lib/formatters.spec.ts
This PR modifies ... in order to support ...
- refactor: use `REQUEST_ID_STRING` from `constants` instead of replicating
- test: added test for `JsonRpcError` constructor
- N/A
- Should be better for code coverage, as `JsonRpcError` was previously only tested directly
**Checklist**
> refactor: use REQUEST_ID_STRING from constants instead of replicating

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
`undefined` values for `transaction_index` in the Mirror NOde contracts results results in errors
- Add logic to handle null or undefined for contract results details
- Add tests
Fixes #1151 
**Checklist**
> Add logic to manage undefined transaction index

- packages/relay/src/lib/clients/mirrorNodeClient.ts
refactored how the allowedErrorStatuses work, since they were not actually working as it was intended, so this will improve the number of retries we perform against mirror node
Fixes #1154 
**Checklist**
> Axios Retries against mirror node refactored

- packages/relay/tests/lib/eth.spec.ts
Fix eth_estimateGas calls that are missing items
- Updated error `32008` (code revert) for `32602` (invalid input)
- Update gas value from `EthImpl.gasTxHollowAccountCreation` to `EthImpl.gasTxBaseCost` where there's an invalid account
- Add a test for hollow accounts
Fixes #1174 
**Checklist**
> Updated eth_estimateGas bad input tests

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/ws-server/src/webSocketServer.ts
Handle valid evm contract address considerations as part of entity resolution
- Add path to MirrorNodeClient retry log
- Conditionally add `this.getTokenById()` to `resolveEntityType()` only if address is of long zero type
- Move requestId to add of `resolveEntityType()` parameters
- Added test for to verify token is only called for long zero address
Fixes #1156 
**Checklist**
> Add resolve type consideration for tokens

- docs/openrpc.json
This PR modifies `docs/openrpc.json` in order to support users of the [OpenRPC spec file](https://spec.open-rpc.org/) contained in this repo + users using the OpenRPC playground.
* Adds a server section to the spec file. [Ref](https://spec.open-rpc.org/#server-object)
* Uses this to specify the public endpoints for Mainnet, Testnet, and Previewnet via Hashio, plus localhost (for those running the relay server locally)
* Intent is that user can copy one of these URLs into the `Enter a JSON-RPC server URL` field within the inspector section of the OpenRPC playground
N/A
This is what the newly added section looks like:
Or you can try it out yourself: [With change](https://playground.open-rpc.org/?schemaUrl=https://raw.githubuserco …
> feat: add server section to openrpc spec

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/ws-server/src/webSocketServer.ts
Handle valid evm contract address considerations as part of entity resolution
- Add path to MirrorNodeClient retry log
- Conditionally add `this.getTokenById()` to `resolveEntityType()` only if address is of long zero type
- Move requestId to add of `resolveEntityType()` parameters
- Added test for to verify token is only called for long zero address
---------
Fixes #1156
> Add resolve type consideration for tokens (#1158)

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/eth.spec.ts
resolveEntityType uses promises, if the promises  returned an  exception,  it  was  not  being bubbled/propagated, but  instead  it  was  crashing  the  app,  the  most  common  case  is  when  the  mirror  node  returns  a  504  (timeout).  now  its  returning  null
Fixes #1215 
**Checklist**
> resolveEntityType error  handling  improvement  inside promises 

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
MirrorNodeClient.getBlock()
Fixes #1191
> Add cache on MirrorNodeClient.getBlock() (#1192)

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
sdkClient creates dependencies on the constructor that are meant to be used as singletons, this was okay when the sdkClient itself was a singleton, but  now  that  we  are  refreshing the sdkInstance every X amount of  requests  we need to  set create  this instances  only once and re-used  them throughout   the  lifecycle  of the app, for  that  purpose  we  have refactored these dependencies  as  private  static  and only  initialized them  once (when  they  are  undefined)
The following dependencies  were  refactored:
consensusNodeClientHistogramCost
consensusNodeClientHistogramGasFee
operatorAccountGauge
hbarLimiter
Fixes #1248
*First SDK instance created:*
*All other instances:*
**Checklist**
> SdkClient Hbar Limitter Fix

- packages/relay/src/lib/eth.ts
Add request id to `eth.getBlock()` `this.getHistoricalBlockResponse()` call
Fixes #
**Checklist**
> Maintain request id reference for /blocks

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
make accepted error codes from mirror node for eth_call configurable and added initial default ones
Fixes #
Whenever the mirror node returns an acceptedErrorCode  the  mirrorNode  request  will return null, and in response  we will  return empty hex.
**Checklist**
> configurable eth_call accepted errors

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
This PR paginates eth_getBlockByHash requests in order to return all transactions within the specified range
Fixes #1261
One test is failing for me locally which I haven't tracked down why:
```
1) RPC Server
should execute "eth_getTransactionByHash with missing transaction"
Error: Timeout of 5000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
**Checklist**
> Paginate eth_getBlockByHash

- helm-chart/templates/deployment.yaml
- helm-chart/templates/secret.yaml
- helm-chart/values.yaml
This PR is to support the existing secret or configmap for the relay configuration.
The typical usecase is when the sensitive data is stored in the vault software and the k8s secret is generated by external-secret operator.
Fixes #1257 
**Checklist**
> feat(chart): Support an existing secret and configmap

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Occasionally time outs are observed from consensus nodes on contractCallQueries, these weren't being handled
- Add logic to check callResponse in callConsensusNode()
- Add test case
Fixes #1292 
Fixes #1278 
**Checklist**
> Handle invalid call response from consensus node

- packages/relay/src/lib/relay.ts
Fixed collect method, first change a typo of ! for ? and then avoid doing a conversion .toNumber() since the accountBalance type is already a number
Fixes #1307 
After fix:
**Checklist**
> Fix relay operator balance gauge

- packages/relay/src/lib/services/hapiService/hapiService.ts
Set initialErrorCodes to [50] by default if missing
Fixes #1324 
**Checklist**
> Set initialErrorCodes to [50] by default if missing

- packages/relay/src/lib/services/hapiService/hapiService.ts
Set initialErrorCodes to [50] by default if missing**Related issue(s)**:
Fixes #1324
> Set initialErrorCodes to [50] by default if missing (#1325)

- charts/hedera-json-rpc-relay/templates/ingress.yaml
Fix helm chart ingress template.
- Correct `.Values.port` for `.Values.ports`
- Correct `.Vales` spelling for `.Values`
- Move `with` for `.Values.ingress.annotations` to enclose only annotations
- Correct `semverCompare` version from `major>.<minor>.<build>` to `major>.<minor>-<build>` format
Fixes #
**Checklist**
> Fix helm chart ingress template

- package-lock.json
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/relay/tests/lib/net.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/relay/tests/lib/web3.spec.ts
Mirror node calls for account has the unintended effect of getting the page limit of tranactions
- Updated get account call to use `order=desc` and `limit = 1`
- Updated spect ts
- Add missing mocks in some spec tests
Fixes #1339 
**Checklist**
> Optimize mirror node get accounts call with limit

- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/server.ts
Simplify relay E2E latency calculation
- move E2E log into single handler
- centralize happy path in server.ts
- update error flows in index.ts for clear messages
Fixes #1348 
**Checklist**
> Reorganize latency calculation logic

- .github/workflows/acceptance.yml
- .github/workflows/dapp.yml
- dapp-example/src/components/ActivateHollowAccountForm.js
- dapp-example/src/components/AssociateHTSTokensForm.js
- dapp-example/src/components/TransferHTSTokensForm.js
- dapp-example/tests/e2e/specs/index.spec.js
- package.json
Simplify DApp tests
- Add `await` on transfer tx
- Update gas limites on acitvate hollow account form and transfer token form
- Add retries on tests
- Reduce timeout time on tests
- Reorder DApp tests
- Main account creates 2 hollow accounts up front and funds them 
- both account perform a transfer and associate to token 2
- contract creation is done once
- Update acceptence test name on Precompile calls workflow
Fixes #1368 
**Checklist**
> Simplify DApp tests layout

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
performCallBlockParamChecks latest block check was not handling the response correctly
- Update logic to check for correct mirror node schema on blocks
- Update test case to verify for error thrown
Addresses #1297 
**Checklist**
> Fix performCallBlockParamChecks latest block check

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/server/src/server.ts
Adding bigger buckets to JSON RPC method statusCode latency so we are aware of timeouts surpassing 30 seconds and above.
Fixes #1378 
**Checklist**
> Adding bigger buckets to JSON RPC method statusCode latency

- charts/hedera-json-rpc-relay/templates/cronjob.yaml
This PR modifies the newman cronjob test
* Removes init container, volume and volume mounts
* Utilized a single container to run this test
Fixes #
Running in integration as `cronjob.integration-json-rpc-relay-test`.  The integration cronjob was edited to test the updated jobspec and then a manual job was created using ` k create job --from=cronjob/integration-json-rpc-relay-test -n integration $NAME`
**Checklist**
> Simplify this down to one container and the built-in wget

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
This PR removes the from check when we call `eth_call`. More context: 
Now with the archive node, we are using only the mirror-node for `eth_call` and since there are already existing checks for the from field, we don't need to check it with a mirror-node call.
Previously we needed to check to avoid unnecessary consensus node, if the from field doesn't exist. But now we can make calls to mirror node with wrong from field without any issues as in the `evm` it doesn't matter if it exists.
Fixes #1346 
**Checklist**
> Remove `from` check from `eth_call` prechecks

- docs/configuration.md
- packages/server/src/koaJsonRpc/index.ts
- packages/server/tests/integration/server.spec.ts
Add optional flag for request id
- Update config docs
- Add `REQUEST_ID_IS_OPTIONAL` env config consideration
- Add logic to allow missing field if config is set and to set id as 0 to avoid failing response checks
Touches on #1385 
**Checklist**
> Add optional flag for request id

- docs/configuration.md
- packages/server/src/koaJsonRpc/index.ts
- packages/server/tests/integration/server.spec.ts
Cherry-pick: Add optional flag for request id (#[1386](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1386))
> Cherry-pick: Add optional flag for request id (#1386)

- packages/relay/src/lib/clients/clientCache.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/relay.ts
- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/ethGetBlockBy.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
Centralize caching logic for client calls
- Add a `clientCache class that encapsulates LRU implementation
- Update mirrornode and sdkclient calls
- create instance in relay and pass it along
- add metrics to capture cache hits to observe
Fixes #1116 
**Checklist**
> Add clientCache to centralize cache

- .github/workflows/release-automation.yml
Added automated release branching support through a new github workflow to
- create a `release/{currentRelease}` branch if it doesn't and bump to `rc1` if new
- tag the new rc
- automatically create a github pre-release
- open a new pr on main to bump the snapshot version
Addresses #903 
**Checklist**
> 903 automate branch tag

- packages/relay/src/formatters.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/formatters.spec.ts
- added `parseNumericEnvVar` to `packages/relay/src/formatters.ts` which handles edge cases like empty strings, undefined, and other non-numeric values
- modified `Overrideable options used when initializing.` section of `packages/relay/src/lib/eth.ts` to make use of `parseNumericEnvVar`
- added units tests for `parseNumericEnvVar`
- Fixes [#1409 fix: caching of block number](https://github.com/hashgraph/hedera-json-rpc-relay/issues/1409)
- See #1409
**Checklist**
> fix: parsing of numeric env vars

- dapp-example/tests/e2e/specs/index.spec.js
- package-lock.json
- package.json
- packages/server/tests/acceptance/index.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
Currently in the acceptance tests try catch logic is used, however we do not check whether an error is actually thrown and we enter the catch. Therefore, this PR changes the logic so we take the maximum of the chai library in order to make the tests effective and intuitive
**What is included**
1. Added chai as promised library for testing on promises
2. Replaced try catch with suitable chai methods, which detect if an error is not thrown
3. Added missing semicolons
4. Replaced some uses of let with const
5. Removed the unnecessary use of Assertions
> Fixes try catch tests and remove unecessary asseritons

- packages/server/src/server.ts
- packages/server/tests/integration/server.spec.ts
Relay currently doesn't support CORS preflight check
- Move cors set first in server to ensure all responses have the appropriate headers
- Update tests for easier validations
- Update test for HTTP OPTIONS request and validation of correct response headers
Fixes #1423 
**Checklist**
> Update server to support cors preflight check

- packages/relay/src/lib/clients/clientCache.ts
- packages/server/tests/integration/server.spec.ts
Fix clientCache metric collection
- Convert metric from Counter to Gauge since values can also decrease
- Add tests in `server.spec.ts` to ensure metrics and health endpoints are functional
Fixes #1431 
**Checklist**
> Fix clientCache metric collection

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
This PR reduces `eth_sendRawTransaction` latency by reducing the number of requests and simplifying precheck.
Now we make 1 less request to the mirror node and 1 less request to consensus node. This reduces both hbar cost and latency. Performance test was done and metrics we collected by prometheus, by average transactions now take 10% less.
Also remove the FileAppendTransaction getReceipt, as transaction in hedera are executed in the order they are received, so we know that the next one will be executed after this one, no need to wait.
Also remove the getReceipt for file
Fixes #1443 
**Checklist**
> Improve `eth_sendRawTransaction` latency by simplifying precheck

- packages/relay/src/lib/clients/clientCache.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/clients/clientCache.spec.ts
---------
Cheery Pick #1469 
Fix boolean `false` issue on cache
- Expand metrics to manage set scenarios also
- Ensure all metrics have calling method
- Update cacheClient to manage where the cached value is false and not treat it as undefined
Fixes #
**Checklist**
> Improve handling of boolean cache retrieval and metric labels (#1469)

- tools/README.md
After some extended testing, it turns out that the relay is supporting almost all scenarios when using Remix IDE.
The only ones that are not supported is debug operations and more specifically `debug_traceTransaction`.
Error thrown from Remix IDE:
`Returned error: {"jsonrpc":"2.0","error":"The method \"debug_traceTransaction\" does not exist / is not available.","id":3852726872457090}`
Fixes #1492 
**Checklist**
> Add Remix IDE in tools Readme.md

- package-lock.json
- packages/relay/package.json
- packages/ws-server/package.json
Bumping up hashgraph sdk version to **v2.30.0**
Fixes #1525 
[Release version](https://github.com/hashgraph/hedera-sdk-js/releases/tag/v2.30.0)
**Checklist**
> Bumping up hashgraph sdk version

- package-lock.json
- package.json
- packages/server/package.json
- packages/ws-server/package.json
Bumping up @hashgraph/hedera-local version across packages to latest 2.11.0
Fixes #1528 
[Release version v2.11.0](https://github.com/hashgraph/hedera-local-node/releases/tag/v.2.11.0)
**Checklist**
> Bumping up hedera-local version to latest v2.11.0

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
The relay caches non-existing contracts or deleted ones, which is a problem when we redeploy contracts via create2.
Fixes #1533 
**Checklist**
> Returned bytecode is incorrect after selfdestruct and recreation via create2

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
refactor getContractByteCode to set cost based on the sdk assessment using getCost method
Fixes #1523 
Did not include a test case, since if every tests we already have continues to work as expected, there should not be an issue, also, testing this overlaps with testing the sdk itself, which is outside the relay and is already tested by the sdk test suites
**Checklist**
> refactor getContractByteCode to set cost based on the sdk assessment

- packages/relay/src/lib/clients/mirrorNodeClient.ts
This change has already been tested by tuning the value of these properties directly using the config map, however, once in a while (presumably when new changes in infrastructure are roll out) these config maps reset to their defaults and its necessary to tune them manually again, but once we know that a configuration is better than other we should productize these changes into code defaults to simplify properties management.
**Related issue(s)**:  #1120 
Fixes #
These changes were already tested on both `testnet` and `mainnet` and noticeable improvements were observed.
**Checklist**
> Increase default number of sockets for mirror node client to 300

- package-lock.json
- packages/relay/src/lib/eth.ts
- packages/relay/tests/assertions.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
- packages/server/tests/helpers/assertions.ts
This PR modifies the eth.spec.ts file where it removes try catch logic which does not work properly in some cases
Fixes #1438
- Remove try catch logic from eth.spec.ts
- Fix some tests in eth.spec that were not working properly
- Add assertions class in relay folder
- Rename assertRejection file in the server so it is more descriptive and clear
**Checklist**
> 1438 update trycatch test logic in ethspects

- packages/relay/src/lib/clients/mirrorNodeClient.ts
Productize mirror node configuration to keep alive by default
Fixes #1565 
This has already been tested on `testnet`  and helped a lot with `latency` issues that were being experienced at the moment of the change.
**Also:** literature usually recommends setting to keepAlive when calling many times the same downstream service.
> keepAlive [<boolean>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) Keep sockets around even when there are no outstanding requests, so they can be used for future requests without having to reestablish a TCP connection. Not to be confused with the keep-alive value of the Connection header. The Connection: keep-alive header is always sent when using an agent …
> Productize mirror node configuration to keep alive by default

- packages/server/tests/acceptance/rateLimiter.spec.ts
- packages/server/tests/acceptance/ws/subscribe.spec.ts
- packages/server/tests/helpers/assertions.ts
This PR improves testing in rateLimiter.spec and subscribe.spec, as well as improving the assertPredfeinedJsonRPC assertion
Fixes #1440 
- Removes try catch logic in rateLimiter.spec and subscribe.spec files
- Fixes some linting issues
**Checklist**
> Improves few tests and an assert method

- packages/relay/src/formatters.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/src/lib/relay.ts
- packages/relay/tests/assertions.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/ethGetBlockBy.spec.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
The formatting method should be in `formatters.ts`, also tests are missing. The issue has been followed up by [PR](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1506).
Fixes #1593 
**Checklist**
> Refactor `EthImpl.formatContractResult()`

- Dockerfile
This PR modifies the `Dockerfile` to simplify the OS package installation and update steps and to prevent an issue with permissions, that occurred, because the node build step was performed as `root` instead of `node` 
* Modify Dockerfile
Fixes #1605 
**Checklist**
> Refactor and cleanup Dockerfile

- packages/relay/src/formatters.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
This PR fixes estimateGas, because in some cases it throws `Unable to parse JSON`. Ethereum tools are passing `value` and `gasPrice` fields as hex, but mirror-node is expecting int. To fix this we need to format properly this fields. Additional checks and more careful formatting is needed for the value to avoid losing accuracy.
Fixes #1613 
**Checklist**
> Fix `eth_estimateGas` transaction values formatting

- package-lock.json
- package.json
Override dev dep nx to 16.5.5 to fix build process on mac os m1
Fixes #1633 
**Checklist**
> Override dev dep nx to 16.5.5 to fix build process on mac os m1

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/server/src/validator/methods.ts
- packages/server/src/validator/utils.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/integration/server.spec.ts
This PR modifies the validations used for eth_getBalance endpoint as well as the getBalance method itself in order to allow the user to get balance by block hash.
- Add possibility for multiple validations with | e.g not only blockNumber or blockHash, but both at the same time
- Add change so blockDiff can be calculated correctly even if blockHash is passed to getBalance
- Add unit and acceptance tests
- Fix tests after the change
Fixes #1614 
**Checklist**
> Fix eth_getBalance to accept hash

- docs/openrpc.json
- packages/relay/src/lib/model.ts
This PR sets default values for withdrawals and withdrawalsRoot in block in order to conform to the Ehtereum JSON RPC Schema for getBlockByHas and getBlockByNumber methods
Fixes #1620 
**Checklist**
> Adds withdrawals and withdrawalsRoot properties with default values

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
Removed 400 from acceptedErrorCodes for GET_ACCOUNTS_BY_ID_ENDPOINT path, added UT to verify that errors are being thrown for both 400 and 500 error status codes
**Related issue(s)**:  #1276 
Fixes #
This replaces [PR 1649](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1649)
And [PR 1366](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1366)
**Checklist**
> Removed 400 AcceptedErrorCodes from MirrorNodeClient for GET_ACCOUNTS_BY_ID_ENDPOINT path

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
When trying to fetch the balance for accounts that does not exists and a block number in the past 15 minutes is provided, there was a null check missing that provoked a unexpected error `500` be returned instead of the expected `0x0` response.
This PR adds the check and missing unit test.
**Related issue(s)**: #1648
Fixes #1670 
**Checklist**
> eth_getBalance not found account for past 15 minutes block in the past read null fix

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Cherry-pick of #1671 into `release/0.30`
> Cherry pick 1671 - eth_getBalance Null fix for past blocks within 15 minutes of latest

- packages/relay/src/lib/constants.ts
- packages/server/tests/acceptance/ws/subscribe.spec.ts
- packages/ws-server/src/webSocketServer.ts
Fixes the address validation logic before creating a subscription through `eth_subscribe`. It now checks if the address is of an existing contract or token. This makes it possible to subscribe to `transfer` and `approve` events generated by HTS tokens.
Fixes #1602
> Support synthetic logs in eth_subscribe

- packages/server/src/koaJsonRpc/index.ts
- packages/server/tests/integration/server.spec.ts
Add request-id as part of all response headers
Fixes #1629 
**Checklist**
> Add request-id as part of all response headers

- packages/relay/src/formatters.ts
- packages/relay/src/lib/model.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/formatters.spec.ts
This PR modifies the formatContractResult method used in getTransactionByHash, getTransactionByBlockHashAndIndex and getTransactionByBlockNumberAndIndex and getBlock by adding new objects for the different types of ethereum transactions, namely 155 transaction, 2930 transactions and 1559 transactions. This is needed in order to conform to the [JSON-RPC ethereum schema](https://ethereum.github.io/execution-apis/api-documentation/) and return only the needed fields for each type of transactions. 
E.g Currently, for 155 and 2930 we return maxPriorityFeePerGas and maxFeePerGas with null values, which is not correct in regards to the JSON-RPC ethereum specs.
Fixes #1657 #1656 
**Checklist**
> Adds new types of transactions

- packages/relay/src/lib/clients/cache/localLRUCache.ts
- packages/relay/src/lib/services/cacheService/cacheService.ts
- Adds a Counter metric to `CacheService`, which counts the the calls to every method of the class, separated by labels for `callingMethod`, `cacheType` and `called method`.
- Removes the same metrics from `localLRUCache`.
Fixes #
**Checklist**
> Add metrics to CacheService

- .github/workflows/subgraph.yml
This PR fixes failing subgraph tests by bumping time between starting graph node and deploying subgraph from 10 to 20 seconds.
Fixes #
**Checklist**
> Fix failing subgraph CI

- packages/server/tests/acceptance/cacheService.spec.ts
- packages/server/tests/acceptance/index.spec.ts
Sets mirror node version and default value for the redis server in the acceptance tests.
Fixes #1706
> Environment variable fixes.

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Fixed Null exception for transaction receipts field `type`
Fixes #1733 
**Checklist**
> Fixed Null exception for transaction receipts

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Addresses Issue [1738](https://github.com/hashgraph/hedera-json-rpc-relay/issues/1738) by formatting `gas` field before sending the tx data to the **mirror-node contracts/call** endpoint.
Mirror node is expecting a decimal number, and relay is getting a Hex string of the number.
Fixes #1738 
I've verified and there are no other fields that need correct transformation from hex string to decimal number.
(see doc [api of mirror node](https://testnet.mirrornode.hedera.com/api/v1/docs/#/contracts/contractsCall))
**Checklist**
> Fix: eth_estimateGas Errors when providing `gas` field

- packages/server/tests/acceptance/rpc_batch1.spec.ts
Test update. Removes synthetic transactions in the relay query response before evaluating against the mirror node response.
Fixes #1579
> Removed synthetic transactions from test set.

- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/cacheService/cacheService.ts
- packages/relay/tests/lib/ethGetBlockBy.spec.ts
- packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
- Refactored getBlock and eth_getTransactionReceipt to use Shared Cache when working with synthetic receipts for HTS transactions.
- Added Unit Tests where needed.
Fixes #1599
Fixes #1627
**Checklist**
> Usage of Shared Cache for Synthetic transaction receipts

- packages/server/tests/acceptance/index.spec.ts
Set the mirror node tag version to 0.87.0
Fixes #1706
> Set the mirror-image-tag to 0.88.0 from main

- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/helpers/prerequisite.ts
- tools/subgraph-example/hardhat.config.ts
- tools/subgraph-example/package-lock.json
- tools/subgraph-example/package.json
- tools/subgraph-example/scripts/erc20-transfer.ts
- tools/subgraph-example/scripts/erc721-mint.ts
- tools/subgraph-example/scripts/manage-gravatar.ts
- tools/subgraph-example/test/expected.json
Wrong intrinsic gas is calculated by eth_sendRawTransaction precheck in all cases. For example deploying [this](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/tools/hardhat-example/contracts/Greeter.sol) greeter contract takes around 79-80k gas, but relay calculates that it needs at least 160k. This results in error throw in the relay even before the transaction reaches consensus node.
This bug didn't surface until now, because we've used hardcoded values for estimateGas, now that we have precise calculation of estimate gas from the mirror-node it appears that relay calculations were wrong.
Calculation done according to Hedera [docs](https://docs.hedera.com/hedera/core-concepts/smart-contracts/gas-and-fees#gas-fees)
Removed estimateGas workaround for the …
> Fix Wrong Intrinsic gas cost in `eth_sendRawTransaction` precheck calculation

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/server.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
- packages/server/tests/clients/relayClient.ts
Stopped treating CONTRACT_REVERT as ERROR, MirrorNode returns 400 status, but is a valid and expected response. returning 200 status code on the relay and logging accordingly to avoid false error positives
Return 200 instead of 400 on Relay HTTP Status Code Response
Removed Error Logs from:
1. mirrorNodeClient.ts
2. server.ts
Fixes #1616
Fixes #1596
Fixes #1707 
**Example Response:**
**Checklist**
> Stop treating CONTRACT_REVERT as ERROR

- packages/server/tests/acceptance/index.spec.ts
Bumps the container image versions for the mirror and consensus nodes, for release 0.33.0.  Issue # 1773
Fixes #
> Bump mirror and node container images.

- docs/openrpc.json
- packages/relay/src/lib/model.ts
This PR fix the `withdrawalsRoot` value setting it to `0x0000000000000000000000000000000000000000000000000000000000000000`.
That parameter is not a `QUANTITY` but a `DATA` of 32 Bytes, so it cannot be `0x0` or some libraries, i.e., [ethers-rs](https://github.com/gakonst/ethers-rs) fail to parse the JSON result of operations related to blocks, like `eth_getBlockByNumber`, `eth_getBlockByHash`, etc.
N/A
I discovered the problem while playing with ethers-rs. This is an example of the error, fixed after updating the `withdrawalsRoot` parameter:
```
Error: MiddlewareError { e: MiddlewareError(JsonRpcClientError(SerdeJson { err: Error("invalid length 1, expected a (both 0x-prefixed or not) hex string or byte array containing 32 …
```
> Fix `withdrawalsRoot`

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth.spec.ts
Fix timestamp from hex to decimal when querying the mirror node
**Related issue(s)**:  #1798 
Fixes #1835 
**Checklist**
> Fix timestamp from hex to decimal when querying the mirror node

- docs/openrpc.json
- packages/relay/src/lib/model.ts
- packages/relay/tests/assertions.ts
- packages/relay/tests/lib/formatters.spec.ts
For compatibility with foundry forge command, we are modifying the block response to have withdrawalsRoot as a long 32Bytes hex 0 and signed transactions to have both yparity and v values.
Changes to the unit tests that were affected
**Related issue(s)**: #1797 
Fixes #1824 
Fixes #1800 
**After the Fix:**
**Checklist**
> Foundry Forge Create Contract Fix

- packages/server/tests/acceptance/index.spec.ts
Upgrading Network node to version '0.42.6' and mirror-node to '0.90.0'
**Related issue(s)**: #1839 
Fixes #
**Checklist**
> Acceptance Tests: Upgrading Network node to version '0.42.6' and mirror-node to '0.90.0'

- packages/relay/src/lib/poller.ts
Potential build fix.  Issue: #1865   Docker image build started failing due to a NodeJS.Timer vs NodeJS.Timeout class type issue.  This PR addresses that.
Fixes #
> Set type of Poller.ts interval to any to get a docker image built.

- packages/relay/src/lib/poller.ts
This PR fixes the issue with the dockerbuild by casting the interval in the pooler as a Timeout.
Fixes #
**Checklist**
> Fix Poller in docker build

- .github/workflows/charts.yml
upgrading chart-testing-action to 2.6.1 due to an issue on CI tests for charts, due to a cosign update that is making it impossible to verify. 
Fixes #
**Checklist**
> upgrading chart-testing-action to 2.6.1

- packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/acceptance/ws/subscribe.spec.ts
Increasing some delays on the acceptance tests that are the most flaky.
Changing web-socket ping verification to be 2 or more, since sometimes is 2 and other 3.
Adding some delays right before calling balanceOf / eth_getBalance.
Adding some delays were needed
Reduced Flakyness Tests on rpc_batch1, rpc_batch2, tokenCreate and subscribe tests
Fixed Gas issue with TokenCreate Test.
Fixes #1913 
** On the screenshot above everything passed at first try, however there are still some lingering flaky-ness on subscribe tests: "release captures transfer events" and  "release captures approve and transferFrom events"
see this [issue](https://github.com/hashgraph/hedera-json-rpc-relay/issues/1919) for follow-up
**Checklist**
> Acceptance Tests TokenCreate Fix and Reliability Improvements

- package-lock.json
- packages/relay/package.json
Bumped up to hashgraph sdk version 2.37.0 to avoid linux library issues.
> Upgrade @hashgraph/sdk from 2.32.0 to 2.37.0

- packages/server/src/server.ts
- packages/server/tests/acceptance/htsPrecompile/tokenCreate.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/acceptance/ws/subscribe.spec.ts
Hardcoded a fix for `eth_estimateGas` due to Metamask sending `0x` on `data` field instead of `0x0` or not sending the field at all. `0x` is equivalent to `null` or not sending the field.
Fixes #1935 
**Checklist**
> HotFix to allow Metamask to unblock Send Token Flow

- packages/server/src/server.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
Hardcoded a fix for eth_estimateGas due to Metamask sending 0x on data field instead of 0x0 or not sending the field at all. 0x is equivalent to null or not sending the field.
Fixes #1935
This has already been deployed and is working on `testnet` and `mainnet` as a HotFix on version `0.36.2`. 
see this [PR](https://github.com/hashgraph/hedera-json-rpc-relay/pull/1936)
**Checklist**
> eth_estimateGas Fixed for MetaMask issue #1935

- packages/relay/src/lib/eth.ts
Improving log message to include `callData` (input) as well as the e.message (error reason) with all instances of eth_call fallback on consensus node (git unsupported calls)
Fixes #1940 
This is an example of the logs produced by the change:
```
[Request ID: daf5090c-d1a4-43b5-a2b2-5f519b09ea2f] Unsupported mirror node eth_call request, retrying with consensus node. details: {"to":"0x00000000000000000000000000000000000b2ad5","data":"0x01ffc9a780ac58cd00000000000000000000000000000000000000000000000000000000","gas":400000,"value":null,"estimate":false} with error: "Precompile not supported for non-static frames"
```
**Checklist**
> Improve logs message when falling back to consensus node due to unsupported calls

- packages/relay/package.json
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth.spec.ts
Removing cache for dev mode if blockNumberOrTagOrHash is explicitly 'latest' or 'pending'
[Relay "getBalance" returns incorrect, cached response#1827](https://github.com/hashgraph/hedera-json-rpc-relay/issues/1827)
> Removing cache for getBalance in dev mode and 'blockNumberOrTagOrHash' is explicit

- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
Add Rate Limits to batch request itself
Fixes #1880 
**Checklist**
> Add Rate Limits to batch request itself

- k6/src/scenarios/test/eth_estimateGas.js
Improving eth_estimateGas test to not rely on hardcoded contracts or values. but use the same greeter that is deployed as part of prep step.
Fixes #
**Checklist**
> K6 Perf Test - Fix eth_estimateGas

- packages/server/tests/acceptance/rpc_batch3.spec.ts
Due to Hardcoded values on `gasPrice` some tests `beforeAll` steps are failing to deploy contracts and thus all the tests on that suite also fail or are skipped. 
this small improvement, fixes this issue.
This issue is only happening on HashIO or production environments (`previewnet` or `testnet`) since when the tests are run on a local node environment, the gasPrice does not fluctuate.
Fixes #
**Checklist**
> Acceptance Tests Improvement

- packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
Acceptance tests fix after hedera-local-node upgrade to use 0.94.1 version of mirror-node, 
changes include Gas verification exclusion, one update and disable of 2 tests due to a found regression on mirror-node (edge case)
Fixes #
**Checklist**
> fix: Acceptance tests fix after hedera-local-node upgrade to use 0.94.1 version of mirror-node

- package-lock.json
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
This PR modifies the current eth_call behavior when no gas is provided in the call object.
We are currently setting incorectly a default gas value, when non is provided. Which is not correct, when the call needs more than the provided. 
It's also not needed, because mirror-node is already doing this internally, if non is provided.
Fixes #2050 
Example case:
So let’s say you have a contract with method which does some action, and this is estimated to consume 1 milion gas (for example).
If you do eth_call and in the transaction object you specify gas, we will redirect this gas to the mirror node and your call will succeed or fail depending, whether this gas is higher or lower than 1 milion.
If you don’t specify gas, in the relay …
> fix: remove unneeded applying of gas on

- tools/hardhat-example/.env.example
- tools/hardhat-example/hardhat.config.js
- tools/hardhat-example/package-lock.json
- tools/hardhat-example/package.json
- tools/hardhat-example/scripts/deployContract.js
- tools/hardhat-example/scripts/showBalance.js
- tools/hardhat-example/scripts/transferHbars.js
- tools/hardhat-example/test/rpc.js
- tools/hardhat-example/test/simple-vault.js
Fixes 
- #2054.
> The Hardhat example does not provide instructions nor setup to verify the contract. It would be useful to devs to have an end-to-end solution to build, test, deploy and verify their smart contracts on Hedera.
This PR adds instructions to setup the verification of deployed smart contracts in a custom Sourcify instance. To do so, it includes a new `env` key to set up the user private key on _testnet_ and updates Hardhat dependencies. More specifically, `ethers.js`
There are breaking changes when migrating `ethers.js` _v5_ to _v6_ (this is because we had to update `hardhat-toolbox` for the custom verification to work).
- `getBalance` needs to be invoked from the `provider`
- Use `target` instead of `address` to get the address of a contract
- Use …
> docs: add verification instructions in Hardhat example

- charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
- charts/hedera-json-rpc-relay/templates/configmap.yaml
Both the relay and websockets support using a standalone (Hedera) network to run test relays with.
Between helm and the SDK the formatting would get updated before being passed into the relay code, this is when the issue would arise.
```
> start
> npx lerna exec --scope @hashgraph/json-rpc-server -- npm run start
lerna notice cli v7.3.0
lerna info versioning independent
lerna notice filter including "@hashgraph/json-rpc-server"
lerna info filter [ '@hashgraph/json-rpc-server' ]
lerna info Executing command in 1 package: "npm run start"
> @hashgraph/json-rpc-server@0.35.2 start
> node dist/index.js
[2023-11-13 23:11:19.995 +0000] INFO (relay/64 on test-hashio-7b585746d6-kchmx): Configurations successfully loaded
/home/node/app/node_modules/@hashgraph/sdk/lib/client/NodeClie …
```
> fix: formatting on standalone networks

- packages/server/tests/acceptance/rpc_batch3.spec.ts
disabled tests that were causing nonce out of sync, temporary workaround while network node 0.47.0 is fully released
Fixes #
**Checklist**
> fix: nonce out of sync, temporary workaround while network node 0.47.0 is released

- packages/server/src/server.ts
Fixed regression where the status code returned by the relay was correctly tracked and observed on metrics but not on logs.
This was making it hard to troubleshoot and correlate the logs with the metrics
Fixes #2084 
After Fix:
**Checklist**
> fix: Status Code on Relay Response Logs

- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
Adding support for eth_call historical blocks, also for receiving a blockHash in the format: { "blockHash": "<blockHash>" } or BlockNumber in the format: { "blockNumber": "0x0" }
Also allow 1 retry to mirror node, due to possible 504 or timeout when querying historical blocks
Fixes #2119 
**Checklist**
> fix: add support for `eth_call` Historical Blocks

- .github/workflows/release-integration.yml
- .github/workflows/release-production.yml
- Fix network issue with docker/setup-buildx-action@v2 plugin by adding network=host fix that is working on `helm` charts.
- Add workflow_dispatch to `Release Integration Environment` WF, so is easier to test future changes on any branch on the integration WF.
Fixes #
**Checklist**
> fix: Network issue with docker/setup-buildx-action@v2 plugin on release integration GH WF

- Dockerfile
After the update to 18.19.1 version of node, the docker build process broke, both for production and integration release workflows.
This PR reverts that upgrade to unblock the release process.
Fixes #
The release integration and also production release process broke due to the following auto update of node version:
https://github.com/hashgraph/hedera-json-rpc-relay/pull/2120
After reverting was able to get the pipeline to succed:
https://github.com/hashgraph/hedera-json-rpc-relay/actions/workflows/release-integration.yml
**Checklist**
> fix: reverting node:18.18.2-bullseye-slim to unblock release process

- packages/relay/src/lib/eth.ts
adding logs for eth_call size and gas
Fixes #
This is how the logs look like:
```
[2024-02-23 00:21:55.278 +0000] TRACE (relay-eth/936 on Admins-Laptop.local): [Request ID: 42b67952-6968-4d1d-a566-a61e6986a0f7] call({to=0x5555555555555555555555555555555555555555, from=0xf66068b5f4b589b2e43b6b4b158851ef472610c6, data=0x5c36b186, gas=0x7530, ...}, blockParam=latest)
[2024-02-23 00:21:55.279 +0000] TRACE (relay-eth/936 on Admins-Laptop.local): [Request ID: 42b67952-6968-4d1d-a566-a61e6986a0f7] call data size: 10, gas: 0x7530
```
**Checklist**
> adding logs for eth_call size and gas

- Dockerfile
Cherry pick 2140
Fixes #
**Checklist**
> fix: cherry-pick #2140 reverting node:18.18.2-bullseye-slim to unblock release process

- docs/openrpc.json
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
- packages/server/src/validator/methods.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/integration/server.spec.ts
This pull request introduces a modification to the relay validator, enabling it to accommodate block hashes within the context of the getStorageAt endpoint. The primary focus of this update is to align the functionality with the underlying logic, which inherently supports block hashes.
Additionally, new tests were added, including adjustments to existing tests to ensure consistency.
Fixes #2107
**Checklist**
> fix: Enables getStorageAt to accept blockHashes

- packages/relay/src/lib/eth.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- resolved long zero addresses to EVM addresses for the following RPC endpoints:
- `eth_getTransactionByBlockHashAndIndex`
- `eth_getTransactionByBlockNumberAndIndex `
- `eth_getBlockByHash`
- `eth_getBlockByNumber`
- fixed unit tests where necessary
Fixes #2128 
**Checklist**
> fix: resolved evm addresses for `from` and `to` addresses in returned transactions

- packages/relay/src/lib/clients/cache/ICacheClient.ts
- packages/relay/src/lib/clients/cache/localLRUCache.ts
- packages/relay/src/lib/clients/cache/redisCache.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/cacheService/cacheService.ts
- packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
- Added method interface `mSet` for ICacheClient
- Implemented method on both cache clients: Redis and Local
- Added method mSet to cache service
- Refactored method `filterAndPopulateSyntheticContractResults` to use mSet instead of set.
Fixes # 
**Checklist**
> fix: HotFix for using mSet instead of Set for redis cache when storing synthetic transactions

- packages/relay/src/lib/clients/cache/ICacheClient.ts
- packages/relay/src/lib/clients/cache/localLRUCache.ts
- packages/relay/src/lib/clients/cache/redisCache.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/cacheService/cacheService.ts
- packages/relay/tests/lib/services/cacheService/cacheService.spec.ts
Cherry-Pick of HotFix https://github.com/hashgraph/hedera-json-rpc-relay/pull/2197
Fixes #
**Checklist**
> fix: HotFix for using mSet instead of Set for redis cache

- packages/relay/src/formatters.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- added a quick helper method to convert the long zero gas value to a decimal value and revert it back to a hexadecimal value. This ensures that the gas value remains intact during the trimming process.
- fixed corresponded unit test
Fixes #2174
**Checklist**
> fix: trimmed preceding zeros for gas value (#2174)

- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR introduces a check method, `isLegacyUnprotectedEtx()`, within the `precheck` class and utilized it in `precheck.chainId()`, allows for compatibility with pre EIP 155 transactions (`chainId=0x0`, default `v = {27, 28}`). Additionally, the PR added new UT coverage for the update and resolves any related UT issues.
Fixes #2201 
**Checklist**
> fix: added support for legacy pre EIP 155 transactions with no chainID (chainId=0x0)

- package-lock.json
- packages/relay/package.json
- packages/server/package.json
- packages/ws-server/package.json
This PR updates the `@hashgraph/sdk` to 2.43. This includes an update to protobufs that supports `hedera-services` 0.48
Fixes #
**Checklist**
> chore: update hashgraph/sdk to 2.43.0 

- docs/openrpc.json
- packages/relay/src/index.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR removes the block range limit, _e.g._, 1000, when the filter in the `eth_getLogs` contains a single address (the optional `address` param might be either a string or an addresses array).
This change allows consumers to query all the log entries of the given address. For now, we permit only a single address, but in the future we might relax this constraint as well.
The block range validation is also used in `eth_newFilter`, but it should not be affected by this change.
Fixes #2175 
It also fixes function type signatures, _i.e., use `string[]` instead of `[string]`.
**Checklist**
> feat: remove block range limit in `eth_getLogs` when filtering with a single address

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/tests/lib/sdkClient.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR adds a private function,`deleteFile()` within the `sdkClient` class. This function attempts to remove the `fileId` file that is generated during `CONTRACT_CREATE` transactions if the contract's bytecode is greater than 5KBs. `deleteFile()` is included in the `finally` block of the `sdkClient.executeTransaction()` function. This ensures that the created file is deleted regardless of whether the transaction succeeds or fails.
This PR also adds new UT coverage for `deleteFile()`
Fixes #2190
**Checklist**
> feat: added deleteFile() method to delete files from the network

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_getCode.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionCount.spec.ts
The `blockParam` parameter for the `getCode()` method is currently validated exclusively by the [validateParam()](https://github.com/hashgraph/hedera-json-rpc-relay/blob/main/packages/server/src/validator/utils.ts#L4) method at the server-level. However, it is necessary to extend this validation to the relay-level as well.
This PR adds a parameter validation step for the `blockParam` parameter in the `getCode()` method. It also includes UTs to ensure coverage of the new validation check.
Fixes #2130
**Checklist**
> feat: added  parameter check on block param for getcode()

- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/poller.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/ws/sendRawTransaction.spec.ts
- packages/server/tests/acceptance/ws/subscribe.spec.ts
- packages/server/tests/acceptance/ws/subscribeNewHeads.spec.ts
- packages/ws-server/src/controllers/eth_sendRawTransaction.ts
- packages/ws-server/src/controllers/eth_subscribe.ts
- packages/ws-server/src/controllers/eth_unscribe.ts
- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/src/utils/counters.ts
- packages/ws-server/src/utils/formatters.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/src/utils/validators.ts
- packages/ws-server/src/webSocketServer.ts
This PR adds support and test coverage for `eth_sendRawTransaction(signedTransaction)` endpoint to the websocket server.  
This PR also slightly modify utils functions in ws-server package to better suit the new API
Fixes #2282
**Checklist**
> feat: integrated eth_sendRawTransaction to websocket server

- packages/server/tests/acceptance/ws/getTransactionByHash.spec.ts
- packages/ws-server/src/controllers/eth_getTransaction.ts
- packages/ws-server/src/controllers/eth_sendRawTransaction.ts
- packages/ws-server/src/controllers/helpers.ts
- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/src/utils/validators.ts
- packages/ws-server/src/webSocketServer.ts
This PR adds support and test coverage for `eth_getTransactionByHash(txHash)` endpoint to the websocket server.
This PR also slightly modify utils functions in ws-server package to better suit the new API
Fixes #2273 
**Checklist**
> feat: added support for getTransactionByHash endpoint in the WS server (#2273)

- dapp-example/tests/e2e/specs/index.spec.js
- packages/server/tests/acceptance/ws/getBlockByHash.spec.ts
- packages/ws-server/src/controllers/eth_getBlockByHash.ts
- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/src/utils/validators.ts
- packages/ws-server/src/webSocketServer.ts
- adds support for eth_getBlockByHash to the WS server and a suite of acceptance tests
- adds a util function to validate blockhash
Fixes #2272
**Checklist**
> feat: added support for eth_getBlockByHash to WS server (#2272)

- packages/server/tests/acceptance/ws/blockNumber.spec.ts
- packages/server/tests/acceptance/ws/call.spec.ts
- packages/server/tests/acceptance/ws/getBalance.spec.ts
- packages/server/tests/acceptance/ws/getBlockByHash.spec.ts
- packages/server/tests/acceptance/ws/getBlockByNumber.spec.ts
- packages/server/tests/acceptance/ws/getLogs.spec.ts
- packages/server/tests/acceptance/ws/getStorageAt.spec.ts
- packages/server/tests/acceptance/ws/getTransactionByHash.spec.ts
- packages/server/tests/acceptance/ws/getTransactionCount.spec.ts
- packages/server/tests/acceptance/ws/getTransactionReceipt.spec.ts
- packages/server/tests/acceptance/ws/sendRawTransaction.spec.ts
- packages/ws-server/src/controllers/eth_blockNumber.ts
- packages/ws-server/src/controllers/eth_call.ts
- packages/ws-server/src/controllers/eth_estimateGas.ts
- packages/ws-server/src/controllers/eth_gasPrice.ts
- packages/ws-server/src/controllers/eth_getBalance.ts
- packages/ws-server/src/controllers/eth_getBlockByHash.ts
- packages/ws-server/src/controllers/eth_getBlockByNumber.ts
- packages/ws-server/src/controllers/eth_getCode.ts
- packages/ws-server/src/controllers/eth_getLogs.ts
- packages/ws-server/src/controllers/eth_getStorageAt.ts
- packages/ws-server/src/controllers/eth_getTransactionByHash.ts
- packages/ws-server/src/controllers/eth_getTransactionCount.ts
- packages/ws-server/src/controllers/eth_getTransactionReceipt.ts
- packages/ws-server/src/controllers/eth_sendRawTransaction.ts
- packages/ws-server/src/controllers/eth_subscribe.ts
- packages/ws-server/src/webSocketServer.ts
This PR add a validate solution which utilizes the param validator from relay-server package to validate params coming into WS server. Fix acceptance tests.
- This PR also group the common params used for the handlers into a `sharedParams` object so it can be used among the handlers
Fixes #2311
**Checklist**
> feat: added param validator to WS server (#2311)

- docs/openrpc.json
This PR includes more details on how the `eth_getLogs` behaves when a single address argument is used.
Fixes #2326.
Fixes #
**Checklist**
> docs: improve openrpc limit docs for `eth_getLogs`

- packages/server/src/validator/objectTypes.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
This PR allows nullable value for `transaction.to` in Transaction object. It also adds a couple of acceptance unit tests to cover the update/
Fixes #2314 
**Checklist**
> fix: allows nullable value for `transaction.to` (#2314)

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
- packages/server/tests/clients/relayClient.ts
Removing `name` field from RPC Error when returning `execution revert` error from `eth_call` due to not being compatible with thegraph node, since it does not maps to their RPC Error structure.
Fixes #2330
**Checklist**
> fix: Removing `name` field from RPC Error when returning Execution Revert on `eth_call`

- packages/server/src/validator/objectTypes.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
fix: allow nullable value for `transaction.to` (#2314)
Fixes #2314
> fix: allows nullable value for `transaction.to` (#2314) (#2319)

- Dockerfile
Revert "[Snyk] Security upgrade node from 18.18.2-bullseye-slim to 18.20.1-bullseye-slim"
Due to it is breaking the buildx process on CI.
Fixes #
**Checklist**
> chore: Revert SNYK #2298 on 0.46 branch 

- packages/ws-server/tests/acceptance/estimateGas.spec.ts
Cannot reproduce.  Updated test to use the websocket provider to deploy the contract.
Fixes #2331
> feat: Updated to deploy the contract using a websocket provider.

- packages/ws-server/tests/acceptance/estimateGas.spec.ts
Cherry-pick of #2332 into release `0.46` branch
Fixes #
**Checklist**
> chore: Cherry pick 0 46 2332

- packages/ws-server/src/controllers/eth_subscribe.ts
- packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
- fixed setting WS_NEW_HEADS_ENABLED true as default logic 
- added a warning log if WS_NEW_HEADS_ENABLED is "false"
Fixes #2360 
**Checklist**
> fix: fixed setting WS_NEW_HEADS_ENABLED true as default logic (#2360)

- packages/ws-server/src/utils/connectionLimiter.ts
- packages/ws-server/src/webSocketServer.ts
- added ability to send back to clients the reason on closing at max connection limit
- also remove extra requestId instance
Fixes #2362
**Checklist**
> fix: added ability to send back to clients the reason on closing at max connection limit (#2362)

- packages/ws-server/src/metrics/wsMetricRegistry.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/src/webSocketServer.ts
**Description**: This PR added histograms and counters to capture metric for connection life cycle
Fixes #2352 
**Checklist**
> feat: added histograms and counters to capture metrics for connection life cycle (#2352)

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance.yml
- package.json
- packages/ws-server/tests/acceptance/blockNumber.spec.ts
- packages/ws-server/tests/acceptance/call.spec.ts
- packages/ws-server/tests/acceptance/estimateGas.spec.ts
- packages/ws-server/tests/acceptance/gasPrice.spec.ts
- packages/ws-server/tests/acceptance/getBalance.spec.ts
- packages/ws-server/tests/acceptance/getBlockByHash.spec.ts
- packages/ws-server/tests/acceptance/getBlockByNumber.spec.ts
- packages/ws-server/tests/acceptance/getCode.spec.ts
- packages/ws-server/tests/acceptance/getLogs.spec.ts
- packages/ws-server/tests/acceptance/getStorageAt.spec.ts
- packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
- packages/ws-server/tests/acceptance/getTransactionCount.spec.ts
- packages/ws-server/tests/acceptance/getTransactionReceipt.spec.ts
- packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
- packages/ws-server/tests/acceptance/subscribe.spec.ts
- packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
Currently there are 300+ total acceptance test cases in the WS server, and they all run within one CI task with one instance of localnode. Due to the enormous size of the CI task, the log wouldn't be able to show all the records, and without seeing the full log it's impossible to trace where the task fails. 
This PR attempts to break the one CI task into 3 smaller separate batches. 
Fixes #2382
**Checklist**
> test: broke websocket acceptancetest CI task into smaller separate batches (#2382)

- packages/relay/src/lib/clients/mirrorNodeClient.ts
this PR updated the MIRROR_NODE_RETRY_DELAY to 1800ms to extend the delayed duration between repeated retries to the mirror node
Initially it was discussed to be 2000ms, but 2000ms seems a little bit long so eth_getLogs seems to skip blocks. In anoother way, instead of getting the logs in the consecutive block, with delay being 2000ms, eth_getLogs will jump to the second next block in the specified range. 
Fixes #2371 
**Checklist**
> fix: updated MIRROR_NODE_RETRY_DELAY to 1800ms (#2371)

- packages/relay/tsconfig.json
- packages/server/tsconfig.json
Fixes #2397 
Allowing `"sourceMap": true` to be deployed to production can have the following outcomes:
- Performance impact.  Although minimal, it can still result in data being transferred between client and server.
- More complicated deployment.  Managing and deploying source maps is an additional step in the deployment process
- Cleaner error reporting.  When the application uses error reporting tools.  Source maps may complicate the logging if they aren't integrated correctly with the tools.
> fix: Removed debugger settings.

- docs/configuration.md
- packages/ws-server/src/webSocketServer.ts
- packages/ws-server/tests/acceptance/estimateGas.spec.ts
- packages/ws-server/tests/acceptance/subscribe.spec.ts
- packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
This PR extends the ping interval to 100 seconds in the WS server so the server sends a null response back to client after 100 seconds
misc: renamed one of the test case which was incorrect
Temporarily Fixes #2359
**Checklist**
> fix: extended ping interval to 100s in WS server

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
This PR moves the deleteFile() logic from `hapiService.getSDKClient().executeTransaction()` to `eth_sendRawTransaction`
level to make sure that the consensus node actually finish executing the raw transaction before deleting the created file.
Current E2E test for deleteFile() also works with new logic, so no update has been done.
Fixes #2418
**Checklist**
> fix: moved deleteFile() logic to the eth_sendRawTransaction level (#2418)

- package-lock.json
- package.json
This PR pumps hedera-local to the latest version 2.23.0. This will help unblock https://github.com/hashgraph/hedera-json-rpc-relay/issues/2402
Fixes #2411 
**Checklist**
> chore: bumped hedera-local to 2.23.0

- .github/workflows/acceptance.yml
This PR takes down the `networkTag:0.49.1` for API Batch 1 and Websocket Batch 2 CI tasks because the hedera-local is now updated to a version that supports deterministic deployment transaction.
Fixes #2402
**Checklist**
> ci: removed networkTag for API Batch 1 and Websocket Batch 2 CI tasks (#2402)

- packages/ws-server/src/controllers/eth_blockNumber.ts
- packages/ws-server/src/controllers/eth_call.ts
- packages/ws-server/src/controllers/eth_estimateGas.ts
- packages/ws-server/src/controllers/eth_gasPrice.ts
- packages/ws-server/src/controllers/eth_getBalance.ts
- packages/ws-server/src/controllers/eth_getBlockByHash.ts
- packages/ws-server/src/controllers/eth_getBlockByNumber.ts
- packages/ws-server/src/controllers/eth_getCode.ts
- packages/ws-server/src/controllers/eth_getLogs.ts
- packages/ws-server/src/controllers/eth_getStorageAt.ts
- packages/ws-server/src/controllers/eth_getTransactionByHash.ts
- packages/ws-server/src/controllers/eth_getTransactionCount.ts
- packages/ws-server/src/controllers/eth_getTransactionReceipt.ts
- packages/ws-server/src/controllers/eth_sendRawTransaction.ts
- packages/ws-server/src/controllers/helpers.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/tests/acceptance/blockNumber.spec.ts
- packages/ws-server/tests/helper/index.ts
The response from Websocket connection contains the method field in the JSON response that makes it incompatible with blockchain client frameworks like go-ethereum
This PR modifies JSON responses from WS for all methods except subscription to make it work with client libraries such as go-ethereum
This PR fixes issue  https://github.com/hashgraph/hedera-json-rpc-relay/issues/2440
Fixes #
- it removes `method` from the response
**Checklist**
> fix: removed method attribute in WS response object

- packages/relay/src/lib/poller.ts
- packages/ws-server/src/controllers/eth_subscribe.ts
- packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
This PR fixes setting WS_NEW_HEADS_ENABLED true as default logic at the Relay level, also added an acceptance test to make sure newHeads works even when WS_NEW_HEADS_ENABLED is undefined.
Fixes #
**Checklist**
> fix: fixed setting WS_NEW_HEADS_ENABLED true as default logic at Relay level

- packages/relay/src/lib/poller.ts
- packages/ws-server/src/controllers/eth_subscribe.ts
- packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
This PR cherry picked [PR#2449](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2449) to release 0.47
Fixes #
**Checklist**
> chore: cherry-picked #2449

- packages/server/tests/acceptance/rpc_batch1.spec.ts
Test fix.  Replaces hard coded values that work on local node with values fetched from `eth_getTransactionCount` 
Fixes #2458
> fix: Test fix for nonce values on networks other thant local node.

- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/tests/acceptance/web3ClientVersion.spec.ts
Added the `web3_clientVersion` to the websocket server.
Fixes #2462
> fix:  Added the web3_clientVersion to the websocket server.

- packages/ws-server/src/controllers/index.ts
- packages/ws-server/tests/acceptance/validations.spec.ts
- packages/ws-server/tests/helper/index.ts
The Go-ethereum eth-client package does not include params field in the jsonrpc request object for methods that do not require any params, i.e. eth_chainId, eth_gasPrice, etc. This absence results in undefined `params`, causing errors during server parsing. This PR addresses the issue by resolving undefined `params`, converting them into an empty array to mitigate the problem. Additionally, it adds acceptance tests to ensure coverage of the update.
Fixes #2463 
**Checklist**
> fix: added support for undefined params requests in WS server (#2463)

- charts/hedera-json-rpc-relay/templates/configmap.yaml
fixing Field HEDERA_NETWORK on configMap helm chart template, when is not a string but a json.
Fixes #2497 
**Before Change/Fix:**
help template:
```bash
helm template relay-deploy-test2 charts/hedera-json-rpc-relay --set config.MIRROR_NODE_URL="http://fullstack-deployment-rest" --set config.MIRROR_NODE_URL_WEB3="http://fullstack-deployment-web3" --set config.CHAIN_ID="298" --set config.LOG_LEVEL="debug" --set config.HEDERA_NETWORK='{"0.testnet.hedera.com:50211":"0.0.3"}'  --set image.tag="main" --output-dir out
```
ConfigMap Extract:
```
HEDERA_NETWORK: "[\"0.testnet.hedera.com:50211\":\"0.0.3\"]"
```
helm logs:
```
[2024-05-16 01:36:29.001 +0000] INFO (relay/44185 on Admins-Laptop-3.local): Configurations successfully loaded …
```
> fix: fixing Field HEDERA_NETWORK on configMap helm chart template, when is not a string but a json.

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_getStorageAt.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
This PR refines the syntax to handle the `RESOURCE_NOT_FOUND` error in `eth_getStorageAt`. With this fix, the Relay skips processing when the response from the mirror-node is null and return a 32-byte-zero-hex string instead of throwing error. Acceptance test is added to cover the update.
Fixes #2491
**Checklist**
> fix: removed `RESOURCE_NOT_FOUND` error in eth_getStorageAt when response is null

- packages/relay/src/formatters.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR simply remove the chainId field if the transaction result is a legacy EIP155 transaction whose chainId equals to "0x".
Fixes #2468
**Checklist**
> fix: removed chainId field for legacy EIP155 transactions (#2468)

- charts/hedera-json-rpc-relay/templates/configmap.yaml
Cherry picked #2498 
Fixes #
**Checklist**
> chore: cherry-picked 2498

- packages/relay/src/formatters.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
Cherry picked #2489 
Fixes #
**Checklist**
> chore: cherry picked 2489

- packages/relay/src/formatters.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/formatters.spec.ts
There is inconsistency in `revertReason` field on `eth_getTransactionReceipt`:
- in some transactions, an ASCII-encoded string reason has been returned (e.g. `PRECOMPILE_ERROR`) 
- but in others, a hex-encoded reason has been returned (based on the contract's ABI, e.g. `0xcf4791810000000000000000000000000000000000000000000000000000000000000001`)
There are several tx's, I executed against the testnet to validate the issue:
- ASCII-encoded string reason TX hash - [0xc998ea6b8101b3d5b44acff9af2f478114ce6e74a8221443ec2ecd2f1a045f17](https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0xc998ea6b8101b3d5b44acff9af2f478114ce6e74a8221443ec2ecd2f1a045f17)
- hex-encoded reason TX hash - [0xc363c5e434544e54399a23e92894fdbe50b65a9dc3ad5b1989dd900c33cc44a5](https://testnet.mirrornode.hedera. …
> feat: make `revertReason` consistent on `eth_getTransactionReceipt`

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
- packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
This PR changes the error code for CONTRACT_REVERT error to the value 3 so it can be compatible with ethereum tools like Viem, Hardhat, etc.
**Related issue(s)**: https://github.com/hashgraph/hedera-json-rpc-relay/issues/2522
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/2457
**Checklist**
> fix: updated CONTRACT_REVERT error code to the value `3`

- packages/server/src/validator/objectTypes.ts
- packages/ws-server/src/controllers/eth_subscribe.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/tests/acceptance/subscribe.spec.ts
- packages/ws-server/tests/unit/utils.spec.ts
~~This PR removes param validator that validates unexpected params for eth_subscribe:logs endpoint. This would allow the WS server to ignore invalid params and conform to standard behavior.~~
Updated logic: This PR adds an util method, `constructValidLogSubscriptionFilter()`, to construct a valid log subscription filter from the provided filters, retaining only the 'address' and 'topics' fields while discarding any unexpected. This will prevent unexpected/malicious params from consuming by the Relay.
**Related issue(s)**: https://github.com/hashgraph/hedera-json-rpc-relay/issues/2464
Fixes #2520 
**Checklist**
> feat: added constructValidLogSubscriptionFilter() to discard any unexpected parameters for logs subcription filter object

- packages/ws-server/src/metrics/connectionLimiter.ts
This PR fixes the error returned from websockets being closed to be conformant to json rpc spec re: errors.
https://www.jsonrpc.org/specification#error_object
Fixes #2362
**Checklist**
> fix: ws errors should conform to jsonrpc spec

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
Adds a precheck to `eth_sendRawTransaction` that rejects transactions with `type=3` with a new predefined error:
`UNSUPPORTED_TRANSACTION_TYPE(code: -32611, message: "Unsupported transaction type")`
Fixes #
**Checklist**
> feat: Add precheck for blob transactions

- packages/relay/src/lib/services/ethService/ethCommonService/ICommonService.ts
- packages/relay/src/lib/services/ethService/ethFilterService/index.ts
- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/tests/acceptance/newFilter.spec.ts
- implemented eth_newFilter to WS server
- added acceptance tests to cover new support
Fixes #2552
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/2548
**Checklist**
> feat: implemented eth_newFilter to WS server

- .github/workflows/release-automation.yml
Adding the node install to the workflow.
Fixes #2561
> fix: Adding the node install as now the npm binary is not found.

- .github/workflows/release-automation.yml
Applied the Node.js install right before the npm ci.
Fixes #2561
> fix: 2561 release automation cannot find npm

- .github/workflows/release-production.yml
- scripts/.bump-version.js
This PR updates the github action and version bump script to fix releasing of helm charts when new versions of hedera-json-rpc-relay are published.
* Update github action
* Update version bump script
Fixes #2506 
PR #2549 needs to also be merged to fix missing releases
**Checklist**
> fix: update helm chart release action

- packages/relay/src/lib/clients/sdkClient.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
Currently, when an `eth_sendRawTransaction` request contains a large `callData`, the Relay uses HFS to create a new file to handle the contents of the `callData`. The condition to use HFS is when `callData.length` exceeds the `fileChunkSize` value. However, in the original setup, the condition is evaluated by comparing the entire `ethereumTransactionData` object, not just `ethereumTransactionData.callData`. This leads to the mismatch between the `callData` size and the `fileChunkSize` value, and therefore throw `Null entity ID` error, when the `callData` size falls within the range of 2568 bytes to 5217 bytes, as described in [issue #2563](https://github.com/hashgraph/hedera-json-rpc-relay/issues/2563).
This PR fixes the problem by using `ethereumTransactionData.callData` …
> fix: fixed condition to employ HFS in submitEthereumTransaction()

- packages/ws-server/tests/acceptance/getCode.spec.ts
- packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
The problem described in https://github.com/hashgraph/hedera-json-rpc-relay/issues/2578 was caused by a lack of a certain configurations on GCP. Neccesary configurations were added to the production envionments, so the porblem was resolved. This PR re-includes eth_getCode and eth_sendRawTransaction back to release testing flow
Fixes #2578 
**Checklist**
> test: re-included eth_getCode and eth_sendRawTransaction in the release testing flow

- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth/eth-helpers.ts
- packages/relay/tests/lib/precheck.spec.ts
This PR updates the precheck.spec.ts file to resolve a TypeError occurring in the ethers package when using node version 20. The error arises because the 'from' field in the transaction doesn't match the signer's address.
It also adds return types and JSDoc where missing.
Fixes #2223 
**Checklist**
> fix: unit tests failing in CI

- docs/configuration.md
- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/tests/lib/sdkClient.spec.ts
Adds support for `OPERATOR_KEY_FORMAT`
Fixes #2583
> feat: Added support for OPERATOR_KEY_FORMAT

- charts/hedera-json-rpc-relay/postman.json
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/tests/assertions.ts
- packages/relay/tests/lib/errors/JsonRpcError.spec.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
- packages/relay/tests/lib/eth/eth_common.spec.ts
- packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
- packages/relay/tests/lib/eth/eth_getCode.spec.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/src/server.ts
- packages/server/tests/helpers/assertions.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/postman.json
- packages/ws-server/tests/acceptance/sendRawTransaction.spec.ts
- packages/ws-server/tests/acceptance/subscribe.spec.ts
- packages/ws-server/tests/acceptance/subscribeNewHeads.spec.ts
This PR removes the `name` field in JsonRpcError class to conform to the JSON-RPC 2.0 Specification. Many tests were updated to apply this new changes.
Fixes #2589
**Checklist**
> fix: removed name field in JsonRpcError class

- .github/release.yaml
Added release.yml file to the .github/ folder for auto-generating release notes
Fixes #2602 
**Checklist**
> feat: add release.yml for auto-generating release notes

- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/helpers/assertions.ts
This PR reworks gas comparison logic. Originally, gas price was compared to a hard-coded value, 71 HBARs, which is only true if the environment is local-net or previewnet. The new logic retrieves the expected gas value from the Relay for the comparison so it would be correct in all environments.
Fixes #2610 
**Checklist**
> fix: reworked gas comparison logic

- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/models/IOpcode.ts
- packages/relay/src/lib/clients/models/IOpcodesResponse.ts
- packages/relay/src/lib/services/debugService/IDebugService.ts
- packages/relay/src/lib/services/debugService/index.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/services/debugService/debug.spec.ts
- packages/server/src/server.ts
- packages/server/src/validator/constants.ts
- packages/server/src/validator/methods.ts
- packages/server/src/validator/types.ts
- packages/server/src/validator/utils.ts
- packages/server/tests/helpers/assertions.ts
- packages/server/tests/integration/server.spec.ts
With the implemenation of `/api/v1/contracts/results/{transactionIdOrHash}/opcodes` in the `web3` module of `hedera-mirror-node`, we can now utilise it by extending our support for debugging transactions. 
This PR:
- makes the neccessery changes to the `debug_traceTransaction` endpoint
- adds acceptance tests for calling `debug_traceTransaction` with `TracerType.OpcodeLogger`.
Fixes #2431
**Checklist**
> feat: enhance debug_traceTransaction to work with Opcode Logger

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR addresses the issue of unexpected records being returned from `eth_getLog` requests with zero addresses. The update ensures that if the `address` parameter equals `ZeroAddress`, the call to the mirror node is skipped, and an empty array is returned immediately.
Fixes #2614
**Checklist**
> fix: fixed unexpected returns for eth_getLog requests with zero address

- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/models/IOpcode.ts
- packages/relay/src/lib/clients/models/IOpcodesResponse.ts
- packages/relay/src/lib/services/debugService/index.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/services/debugService/debug.spec.ts
- packages/server/src/server.ts
- packages/server/src/validator/constants.ts
- packages/server/src/validator/methods.ts
- packages/server/src/validator/types.ts
- packages/server/src/validator/utils.ts
- packages/server/tests/helpers/assertions.ts
- packages/server/tests/integration/server.spec.ts
Cherry pick [PR#2480](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2480) and [PR#2628](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2628) to release/0.50
Fixes #
**Checklist**
> chore: cherry picked debug_traceTransaction 

- packages/server/tests/acceptance/rpc_batch3.spec.ts
Initially, batch 3 frequently failed with the `GrpcServiceError: gRPC service failed with status: TIMEOUT` error. This occurred because batch 3 contained consecutive test cases that exhaustively utilized the SDK to retrieve and prepare for testing materials. This PR addresses the issue by reducing the SDK usage and delegating some tasks to the relay in batch 3. This prevents the exhaustive use of the SDK and thereby avoids the GrpcServiceError: gRPC service failed with status: TIMEOUT error.
Fixes #2568
**Checklist**
> fix: reduced the SDK usage in batch 3 to stablize the batch

- charts/hedera-json-rpc-relay/postman.json
- docs/openrpc.json
- packages/relay/src/lib/net.ts
- packages/relay/src/lib/relay.ts
- packages/relay/tests/lib/net.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/postman.json
The `net_version` method previously returned a hexadecimal value for the netVersion, which deviates from the standard behavior adopted by many other services in the industry that return a decimal value. This PR ensures that the `net_version` method returns a decimal value instead of a hexadecimal one. Additionally, associated tests have been also added to verify this change.
This PR also takes the opportunity to add support for the `net()` module to read the chainId from the configuration at launch, rather than requiring it as a passed-in parameter.
Fixes #2629 
**Checklist**
> fix: net_version now reads chainId from config and return decimal value

- package-lock.json
- package.json
- packages/relay/package.json
- packages/server/package.json
- packages/ws-server/package.json
This PR updates mainly SDK version used, because with latest services tag, new transaction was introduced and the sdk version that we use is utilizing older protobufs version
Fixes #2662 
**Checklist**
> fix: issue when trying to perform transaction

- packages/relay/src/lib/services/cacheService/cacheService.ts
- packages/relay/src/lib/services/ethService/ethFilterService/index.ts
Currently, in getFilterChanges we get the filter id from the sharedCache. However, this won't work if the sharedCache option is disabled.
The PR modifies the filterService, so we check if the sharedCache is actually enabled.
Fixes #2646
> fix: Adds usage of internal cache for getFilterChanges

- tools/golang-json-rpc-tests/main.go
eth_getBlockTransactionCountByNumber is not supported in wss. It shuld be treated as such
Fixes #2651 
**Checklist**
> fix:  eth_getBlockTransactionCountByNumber is not supported in wss

- packages/relay/src/formatters.ts
- packages/relay/tests/lib/eth/eth-config.ts
Currently, the `gasPrice` fetched via raw mirror node query is returned denominated in tinybars which leads to misunderstandings by users (and ethereum tools). The more accurate denomination is wei (weibar in hedera context).
Affected RPC endpoints:
```
eth_getTransactionByHash - gasPrice
eth_getTransactionByBlockHashAndIndex - gasPrice
eth_getTransactionByBlockNumberAndIndex - gasPrice
eth_getBlockByNumber - transactions array - gasPrice
eth_getBlockByHash - transactions array - gasPrice
```
**Steps to reproduce**:
Execute a json-rpc-relay request with the following body:
```bash
curl --location 'https://testnet.hashio.io/api' \
--header 'Content-Type: application/json' \
--data '{
"jsonrpc": "2.0",
"method": "eth_getBlockByNumber",
"params": [
"0x5db6f5",
true
],
"id": …
```
> fix: gasprice of transactions denoted in tinybars

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/server/tests/acceptance/rateLimiter.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
This PR is a hotfix for v0.51 that added steps to capture transactionFee in metrics and HBAR limiter class for executeTransaction and deleteFile.
To retrieve the `transactionFee` in `executeTransaction()`, the `getRecord()` method was utilized. The `getRecord()` method exposes and throws errors caused by invalid transactions on the network, which were previously ignored. These errors were typically discovered only after repeated lookups on the mirror node, with `MIRROR_NODE_GET_CONTRACT_RESULTS_RETRIES` (10) multiplied by `MIRROR_NODE_RETRY_DELAY` (2000ms), resulting in a total of 20000ms (20 seconds). This error exposure helps to reduce transaction time and ensures more accurate and secure handling of transactions.
This PR also tweaked and reused …
> fix: captured transactionFee in metrics and HBAR limiter class in executeTransaction and deleteFile

- packages/ws-server/src/webSocketServer.ts
The websockset specific metrics are available on 8547 port, but the relay's metrics are not. The import of the relay is the same as the in the server, but the relay metrics are available in the RPC server but not the websocket server.
**Steps to reproduce:**
1. Run the RPC server.
2. Run the WebSocket server.
3. Look at the metrics at the http://localhost:8547/ end point.
4. Notice the relay metrics are not exposed.
This PR adds a small change to the WebSocket server to collect the relay metrics (same way it is done in the RPC server):
```diff
+ collectDefaultMetrics({ register, prefix: 'rpc_relay_' });
```
Fixes #2694
**Checklist**
> fix: The relay metrics are not exposed in the websocket server

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/hbarlimiter/index.ts
- packages/relay/tests/lib/hbarLimiter.spec.ts
Cherry pick [PR#2751](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2751) - feat: added preemtiveCheck for HBAR ratelimit (#2751) to release/52.0
Fixes #
**Checklist**
> chore: cherry picked PR#2751

- packages/relay/src/lib/clients/sdkClient.ts
Currently, the way `executeTransaction` uses `executeTransactionRecord` results in the transaction fee being captured twice. This PR reorganizes the two methods to prevent this issue.
Fixes #2741
**Checklist**
> fix: reorganized executeTransaction and executeTransactionRecord to avoid capturing metrics twice

- packages/server/tests/acceptance/hbarLimiter.spec.ts
[PR#2751](https://github.com/hashgraph/hedera-json-rpc-relay/pull/2751) added a preemptive check for the HBAR rate limit as a hotfix but did not include E2E test to cover the solution. This PR adds the necessary E2E test to ensure comprehensive coverage.
Fixes #2745
**Checklist**
> test: added E2E test for preemtive rate limit

- package-lock.json
- package.json
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth-config.ts
- packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
- packages/server/package.json
- packages/ws-server/package.json
Currently, we are relying on requests to `eth_getBlockByNumber` to cache all synthetic transactions, which later (for a certain time, not indefinitely) are available when someone makes an `eth_getTransactionReceipt`. However, this results in a poor developer experience because if you want to search only by transaction hash, and you don’t know the block, it’s impossible.
**Solution**:
With the changes introduced in this [EPIC](https://github.com/hashgraph/hedera-mirror-node/issues/8758), it’s now possible to search synthetic contract logs by only knowing the transaction hash. This allows us to make the necessary changes in the relay and support this behavior.
It’s important that we add adequate tests for this as well, including transferring HTS tokens and querying the …
> feat: search contract logs only by transaction hash

- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
- updated `executeTransaction()` so it can perform executeAll() for type FileAppend transactions 
- reused executeTransaction() for fileCreate, fileAppend, and fileDeelete so they can share the same workflow
- improve logging so it can be descriptive for each transactions. Add logs that contain requestId, transactionId, transactionType, transactionCost, gasUsed, etc.
Fixes #2746
**Checklist**
> feat: reused executetransaction for methods in sdkclient and improved logging

- packages/server/tests/helpers/utils.ts
Currently, we could sometimes get false positive detections of memory leaks in the tests.
This PR changes adjusts the `HEAP_SIZE_DIFF_MEMORY_LEAK_THRESHOLD` and `HEAP_SIZE_DIFF_SNAPSHOT_THRESHOLD` to be less sensitive.
**Checklist**
> chore: bump memory leak threshold

- package-lock.json
- package.json
- packages/server/src/validator/methods.ts
- packages/server/src/validator/types.ts
- packages/server/src/validator/utils.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/integration/validator.spec.ts
Currently, when we pass null as a param for getCode or any other endpoint, we do not return a descriptive response to the user. Thus, this PR adds a check in the validator, that throws an error when the param passed is null.
**Files Changed** :
1. `src/validator/utils.ts` - Added a null check for the parameters
2. `rpc_batch2.spec.ts` - Fixed few failing tests
**Type of Change**:
Fixes #2376
> fix: Adds null check for param in validation

- packages/relay/src/formatters.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/formatters.spec.ts
This PR aims to remove redundant logic in the eth_sendRawTransaction, which was responsible for retyring transaction if timeout error occurs. However the underlying problem in the SDK was fixed, therefore this is no longer needed. Removing it to increase readability and maintainability mostly.
Also removed unused methods in the formatter class and added some additional unit tests.
Fixes #2794 
**Checklist**
> chore: Remove and Refactor redundant logic in `eth_sendRawTransaction`

- .github/workflows/dev-tool-test.yml
- .github/workflows/dev-tool-workflow.yml
- tools/golang-json-rpc-tests/.env.example
- tools/golang-json-rpc-tests/.env.sample
- tools/golang-json-rpc-tests/README.md
- tools/golang-json-rpc-tests/main.go
This PR adds:
- ability to run Golang JSON RPC tests against local node,
- execution of Golang JSON RPC tests to `dev-tool-test` workflow.
Closes #2681
**Checklist**
> feat: add Golang tests to workflow

- packages/relay/tests/lib/sdkClient.spec.ts
- packages/relay/tests/lib/services/transactionService/transactionService.spec.ts
-stabilized sdkClient test by bumping total timeout to 30000ms
Fixes #2816 
**Checklist**
> fix: stabilized sdkClient test by bumping total timeout to 30000ms

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/tests/lib/sdkClient.spec.ts
captured and added FileInfo query costs to metrics and hbar ratelimit class
Fixes #2738
**Checklist**
> fix: captured and added FileInfo query costs to metrics and hbar ratelimit class

- packages/relay/src/lib/clients/cache/redisCache.ts
- packages/relay/tests/lib/clients/redisCache.spec.ts
```bash
ERROR (cache-service/7325): Error occurred while setting the cache to Redis. Fallback to internal cache. Error is: Error: ERR value is not an integer or out of range
```
This error is appearing multiple times in the logs of multiple workflows in the CI, right after doing the getAccount query from the mirror node.
After doing some investigation, it looks like when we transform the passed TTL to seconds, it was possible that we get a floating point number (`ETH_GET_TRANSACTION_COUNT_CACHE_TTL: 500`) => which resolves to `resolvedTtl = 0.5`
```typescript
const resolvedTtl = (ttl ?? this.options.ttl) / 1000; // convert to seconds
```
And the `setEx` method of Redis expects an integer, hence why this error is thrown.
This PR:
- modifies the `RedisCache#set` method to …
> fix: error thrown when setting value in redis cache

- .github/workflows/dapp.yml
Bumped up Dapp test timeout as many test runs are now timing out on the current runners.
Fixes #
**Checklist**
> fix: Bump timeout up due to many test runs timing out in the current CI

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance.yml
- .github/workflows/conformity-workflow.yml
- .github/workflows/manual-testing.yml
- package-lock.json
- package.json
- packages/server/package.json
- packages/server/src/validator/constants.ts
- packages/server/src/validator/methods.ts
- packages/server/src/validator/types.ts
- packages/server/tests/acceptance/conformityTests.spec.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/integration/validator.spec.ts
- packages/ws-server/tests/acceptance/subscribe.spec.ts
Currently, our validation process only checks the presence of fields returned by our API, without verifying the format of these fields. This can lead to inconsistencies and potential errors.
Changes introduced:
* Adds separate CI workflow for API conformity
* Pulls the openrpc.json from [execution-apis repo](https://github.com/ethereum/execution-apis/tree/main) in order to validate our response against it
* 
Fixes #2108
> fix: Improve compatibility with standard ethereum tooling

- packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
- packages/relay/src/lib/services/hbarLimitService/index.ts
- packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
Adds a skeleton for the `HbarLimitService` and implements the `shouldLimit` method.
**NOTE:** IP address limiting will be handled in a separate PR after #2867 is merged
Fixes #2865
**Checklist**
> feat: Implement `shouldLimit` method of `HbarLimitService`

- docs/design/hbar-limiter.md
This PR adds a class diagram to the documentation for the database schema of the Hbar Limiter redesign. The diagram provides a visual representation of the classes and their relationships, which are used to manage Hbar spending plans and records.
**Changes**:
- `docs/design/hbar-limiter.md`:
- Wrapped the current diagram into a "Service Layer" section
- Added a new "Database Layer" section with a class diagram for the DB entities + repositories
**Checklist**
> docs: Add class diagram for the database schema of the hbar limiter redesign

- tools/waffle-example/README.md
- tools/waffle-example/test/samplecontract.test.mjs
Enhance the Waffle usage example by adding additional code that demonstrates how Waffle Fixtures can be utilized.
https://github.com/hashgraph/hedera-json-rpc-relay/issues/2882
**Checklist**
> fix: fixtures usage example

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
- .github/workflows/acceptance.yml
- .github/workflows/dapp.yml
- .github/workflows/manual-testing.yml
- .github/workflows/release-acceptance.yml
- .github/workflows/release-production.yml
This PR is addressing the following note:
```
Warning
actions/upload-artifact@v3 is scheduled for deprecation on November 30, 2024. [Learn more.](https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/) Similarly, v1/v2 are scheduled for deprecation on June 30, 2024. Please update your workflow to use v4 of the artifact actions. This deprecation will not impact any existing versions of GitHub Enterprise Server being used by customers.
```
It has addressed the [Breaking Changes](https://github.com/actions/upload-artifact/tree/main?tab=readme-ov-file#breaking-changes) in v4 where is needed:
```
Uploading to the same named Artifact multiple times.
Due to how Artifacts are created in this new version, it is no longer possible to upload to the …
```
> ci: Update actions/download-artifact and actions/upload-artifact to v4

- packages/server/tests/acceptance/conformityTests.spec.ts
Create tests similar to the ones in this [repo](https://github.com/ethereum/execution-apis/tree/main/tests) for the following endpoints
Fixes #2726
**Checklist**
> feat: create second batch of additional conformity tests

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/services/debugService/index.ts
- packages/relay/tests/lib/services/debugService/debug.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
> fix: `debug_traceTransaction` throws 500 for non-existing transaction hashes

- docs/configuration.md
- packages/relay/src/lib/subscriptionController.ts
- packages/relay/tests/lib/subscriptionController.spec.ts
This PR fixes #2926 (_Websocket subscription creates same subscription ID for new connection from same client_) by introducing a new environment variable that allows the JSON-RPC relay provider to choose the desired behavior.
The default value of `WS_SAME_SUB_FOR_SAME_EVENT` is set to `"true"` to match the current default behavior.
Fixes #2926
**Checklist**
> fix: let the provider decide when to reuse an existing subscription ID

- packages/relay/src/lib/eth.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
Currently "latest" and "pending" blocks are not cached, as it should be, since Hedera doesn't have such thing as a pending block. However, the network doesn't support finalized and safe as well, but they are cached and this leads to the issue mentioned below.
Fixes #2916
> fix: bug where finalized and safe tags are cached

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
- .github/workflows/acceptance.yml
- .github/workflows/manual-testing.yml
- .github/workflows/release-acceptance.yml
- .github/workflows/test.yml
Previously the publish-unit-test-result action was updated to use the step-security maintained version of publish-unit-test-result-action. However, the step-security action is a fork of the enricoCI action. This change broke the actionite publish steps.
Fixes: #2941
> ci: Revert breaking change to publish-unit-test-result-action

- packages/server/tests/acceptance/rpc_batch2.spec.ts
Bumped up exchanged value as the HTS token create will take the fee from the value instead of the gas.
Fixes #2951 
**Checklist**
> fix: Bumped up exchanged value 

- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
This PR enables `sendRawTransaction` to retrieve the current `gasPrice` of the network via the mirror node, instead of querying the consensus node for the fee schedule file. By switching to MAPI, the relay operator account can avoid incurring costs associated with MAPI queries.
Fixes #2979 
This PR utilizes the `gasPrice()` method in the `eth.ts` module for `sendRawTransaction` to take advantage of querying the `gasPrice` through the mirror node. If that query fails, it falls back to querying the consensus node for the fee schedule using the `getTinybarGasFee` method in the `sdkClient`.
**Checklist**
> feat: enabled retrieval of network `gasPrice` in `sendRawTransaction` using MAPI instead of HAPI.

- packages/relay/src/index.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/hbarlimiter/index.ts
- packages/relay/tests/helpers.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/hbarLimiter.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
- packages/server/tests/acceptance/hbarLimiter.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
A preemptive rate limit was introduced as a hotfix in version 0.52.1, using a logic that preemptively rate-limited file transactions by comparing a hard-coded amount of tinybars that was assumed to be the cost for `FileCreate` and `FileAppend` transactions. However, this logic was incorrect and the tinybar amount was a random figure agreed among the team for the purposes of the hotfix.
This PR improves the rate-limiting logic by leveraging the [Hedera Fee Calculator](https://hedera.com/fee) to estimate fees for `FileCreate` and `FileAppend` transactions based on a file size of `FILE_APPEND_CHUNK_SIZE` bytes. This approach ensures the estimated fees more closely align with the actual transaction fees charged for these transactions.
Fixes #2921 …
> feat: improved preemtive rate limit for file transactions

- packages/relay/src/lib/eth.ts
This PR simply adds the call.from to the cacheKey in callConsensusNode() as certain requests (e.g., HRC719.isAssociated()) require call.from as an additional specifier to ensure more accurate cached values.
Fixes #2992
**Checklist**
> fix: included `call.from` to the `cacheKey` in callConsensusNode()

- packages/relay/src/lib/db/repositories/hbarLimiter/hbarSpendingPlanRepository.ts
- packages/relay/src/lib/services/hbarLimitService/index.ts
- packages/relay/tests/lib/repositories/hbarLimiter/hbarSpendingPlanRepository.spec.ts
- packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
It's not clear yet if the spending history of the plans is going to be used for anything and it will consume a lot of the cache's memory so it's better to keep it empty for now.
Changes:
- Removed all usages of `HbarSpendingPlanRepository#getSpendingHistory`
- Removed all usages of `HbarSpendingPlanRepository#addAmountToSpendingHistory`
Fixes #2994
**Checklist**
> chore: Disable spending history of HbarSpendingPlans

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
- .github/workflows/conformity-workflow.yml
**Details**:
Updates the OPERATOR_KEY_MAIN environment variable storage to use a masked value.
**Related Issues**:
Fixes: #3011
> ci: Fix issue with github_env echo statements

- .github/workflows/manual-testing.yml
There is an issue in the manual-testing workflow file, the acceptance workflow requires actions: read permissions but its not getting them when manual testing is ran. Initially I thought they were not defined in the acceptance workflow file but everything seems to be fine there so adding permissions here.
Fixes #3017
**Checklist**
> ci: Updating permissions within manual-testing to resolve workflow issue.

- .github/workflows/manual-testing.yml
Currently, the `manual-testing.yml` workflow has regressions in its configurations which causes some of the web-socket server acceptance tests to fail when ran through the Manual Testing job in GitHub.
This PR fixes those failing tests.
Fixes #3028
**Checklist**
> fix: failing websocket tests in manual-testing.yml

- packages/server/src/validator/constants.ts
- packages/server/src/validator/objectTypes.ts
- packages/server/src/validator/types.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/integration/validator.spec.ts
Sometimes when the relay attempts to do a `contract/call` to the mirror node and gets a '400` status assumes a "revert" happenend. see the attached  curl.
[Curl request mirror node contract call.txt](https://github.com/hashgraph/hedera-json-rpc-relay/files/15421908/Curl.request.mirror.node.contract.call.txt)
The actual mirror-node error code is a `BAD REQUEST` due to `contains invalid odd length characters`
but the relay assumes is a REVERT and not only that but returns the whole payload on the error message.
Fixes #2532
**Checklist**
> feat: eth_call revert error message is too long, and should not be a REVERT but a BAD Request Response

- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/services/hbarLimitService/index.ts
- packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
- packages/server/src/validator/constants.ts
- packages/server/src/validator/objectTypes.ts
- packages/server/src/validator/types.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/integration/validator.spec.ts
> chore: merge branch `main` into `2739-Redesign-of-the-hbar-limiter`

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
Fixes #3091
This PR makes the following changes:
- Adds a `maxAttempts` parameter to the acceptance test workflow, so that we can control the number of test retry attempts.
- Updates the public acceptance workflow to set the maxAtempts parameter to 1, ensuring we only do a single acceptance test run against public networks.
> feat: add maxAttempts parameter to the acceptance test workflow

- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/tests/unit/utils.spec.ts
There's a regression in the WS server that breaks the `eth_newFilter` WS endpoint. Essentially, before the data is submitted to the Relay, there’s a step to rearrange the parameters for certain special endpoints that have a different parameter order than others. This step is handled by the `paramRearrangementMap`, but it missed the `newFilter` endpoint, so the parameters weren't ordered correctly, causing the `eth_newFilter` endpoint to fail.
This PR simply adds the `newFilter` method to the `paramRearrangementMap`, fixing the issue.
Fixes #3114 
**Checklist**
> fix: added newFilter to paramRearrangementMap for WS server

- packages/ws-server/src/controllers/index.ts
- packages/ws-server/src/utils/utils.ts
- packages/ws-server/tests/unit/utils.spec.ts
Cherry picked fix from main into the release.
* fix: added newFilter to paramRearrangementMap for WS server
* test: added unit test
---------
Fixes #3117 
**Checklist**
> fix: added newFilter to paramRearrangementMap for WS server (#3117)

- docs/configuration.md
Updates the configuration doc to list the default `LOG_LEVEL` .
-->
Fixes #3131 
**Checklist**
> feat: State the default log level in the documentation.

- packages/relay/src/lib/db/repositories/hbarLimiter/ethAddressHbarSpendingPlanRepository.ts
- packages/relay/src/lib/db/repositories/hbarLimiter/ipAddressHbarSpendingPlanRepository.ts
- packages/relay/src/lib/services/hbarLimitService/index.ts
- packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
- packages/server/tests/acceptance/hbarLimiter.spec.ts
Related issue: #2850 
This PR addresses the following concern:
> Yeah I believe the logic should securely handle checks on both EVM addresses and IP addresses independently, without either depending on the other.
> I thought of a scenario where a random application, like an NFT marketplace or a DEX, submits user requests from the same centralized server (i.e., the same IP address). Users connect to the platform using different wallet accounts (i.e., different EVM addresses), but all requests are submitted to the network under a single IP address. If we only validate based on the IP address, traffic becomes unfair since requests from different users would be dependent on one another. A user might reach the HBAR limit even if they have not made prior calls, simply because …
> fix: do not link IP addresses of general users

- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
- .github/workflows/acceptance.yml
- .github/workflows/manual-testing.yml
- .github/workflows/release-acceptance.yml
- .github/workflows/test.yml
The previous attempt to upgrade to the step-security version of the workflows resulted in an issue as there was mismatch in the inputs between the versions. This should now be resolved and this PR contains the changed inputs as well as the upgrade to the step-security maintained version of the action.
Fixes #2943 
**Checklist**
> ci: Updating workflows/actions to be compatible to and updating to the step-security maintained version.

- packages/config-service/src/services/loggerService.ts
- packages/config-service/tests/src/services/loggerService.spec.ts
Examine the env variable value and mask anything starting with one of the prefixes described in https://github.blog/engineering/platform-security/behind-githubs-new-authentication-token-formats/
**Solution**:
Modify the `maskUp` method in ConfigService to hide secrets that start with known prefixes.
Fixes #3143
**Checklist**
> feat: add env masking for values starting with known secrets prefixes

- .github/workflows/acceptance-workflow.yml
- .github/workflows/charts.yml
- .github/workflows/conformity-workflow.yml
- .github/workflows/dapp.yml
- .github/workflows/dev-tool-workflow.yml
- .github/workflows/flow-pr-title-check.yml
- .github/workflows/image-build.yml
- .github/workflows/postman.yml
- .github/workflows/pr-label-milestone-check.yml
- .github/workflows/release-acceptance.yml
- .github/workflows/release-integration.yml
- .github/workflows/release-production.yml
- .github/workflows/subgraph.yml
Updating several workflows and their permissions per step-security requirements and adding hardend runner to one of the workflows.
Fixes #3121 
**Checklist**
> ci: Updaiting workflow permissions and adding hardend runner per step-security.

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
This PR fixes the issue discussed in the comments of #3115 
Fixes #3115
**Checklist**
> fix: Inconsistent handling of failed EVM transactions

- packages/server/tests/helpers/utils.ts
This PR bumps the memory leak threshold to 4MB to avoid having false-positive detections in PRs
Fixes #3168
**Checklist**
> chore: Bump threshold of memory leak alerts

- .github/workflows/release-production.yml
Added `packages: write` permission per [the github documentation](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-with-a-personal-access-token-classic) May need to modify other files modified by #3124
Relates to #3124
Relates to #3182
> ci(bug): Update permissions in JSON rpc relay for GITHUB_TOKEN

- .github/workflows/flow-pr-title-check.yml
Title check CI job fail for PRs that are from a forked repository due to the lack of the secret.GITHUB_TOKEN. This PR adds an option to skip the check if the PRs are from forked repos.
Fixes #3195 
**Checklist**
> fix: skipped title check CI job for forked PRs

- k6/src/scenarios/test-ws/common.js
- k6/src/scenarios/test-ws/eth_chainId.js
- k6/src/scenarios/test-ws/eth_subscribe_logs.js
- k6/src/scenarios/test-ws/eth_subscribe_newHeads.js
- k6/src/scenarios/test-ws/eth_subscribe_newPendingTransactions.js
- k6/src/scenarios/ws-apis.js
The current report of the k6 performance tests for the WS-server is currently misleading:
- the scenario duration is not correctly captured since the actual duration should be taken from the moment that the JSON-RPC request is sent to the WS server until the moment a message with the JSON-RPC response is received from the WS server. Instead, the `scenarioDurationGauge` is currently only tracking the duration of the request which establishes connection with the WS server and not the actual JSON-RPC request.
Refactor the current tests to capture valid scenario duration metrics in the report (through the `scenarioDurationGauge`)
Fixes #3167
Results after running the WS performance tests against testnet:
```bash …
```
> fix: Wrong metrics in the report of the WS performance tests

- package-lock.json
- package.json
- packages/config-service/src/services/globalConfig.ts
- packages/config-service/tests/src/services/validationService.spec.ts
- packages/server/tests/acceptance/index.spec.ts
The ConfigService was using an all caps version of the `npm_package_version` of the env var definition but in a node context the env var is lowercase: `npm_package_version`.  Nothing was being returned from the `web3_clientVersion` method.
Fixes #3197
Simply changing the case of the env var definition in the `GlobalConfig.ts` class prevents updating conditional logic that already works.  Adding the version number to the root package.json file allows it to be loaded by the `ConfigService.ts` which loads before the acceptance tests framework.
**Checklist**
> fix: Capture the npm_package_version

- package-lock.json
- package.json
- packages/config-service/src/services/globalConfig.ts
- packages/config-service/tests/src/services/validationService.spec.ts
- packages/server/tests/acceptance/index.spec.ts
Cherry-picked fix for the `web3_clientVersion` method.
The ConfigService was using an all caps version of the npm_package_version of the env var definition but in a node context the env var is lowercase: npm_package_version. Nothing was being returned from the web3_clientVersion method.
Fixes #3198 
Simply changing the case of the env var definition in the GlobalConfig.ts class prevents updating conditional logic that already works. Adding the version number to the root package.json file allows it to be loaded by the ConfigService.ts which loads before the acceptance tests framework.
**Checklist**
> fix: 3198 cherry pick npm package version

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/errors/SDKClientError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
- packages/relay/tests/lib/services/metricService/metricService.spec.ts
Currently, we experience the SDk timing out in the CI and on mainnet, eventhough the transactions that fail do not take more than 10 seconds. More info in the issue below
Workaround until  #3118 is solved
> fix: Adds retry to send raw transaction

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/errors/SDKClientError.ts
- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
- packages/relay/tests/lib/services/metricService/metricService.spec.ts
Addresses issue: #3160 
* Adds retry to eth send raw transaction
* Adds mirror node check before retry and expands SDKClientError object to include transactionId
* Adds unit tests
* Adds improvements
* adds relevant comment for hardcoded values
* removes retry and adds mirror node check in the sdk client
* Adds unit tests
* Addresses PR comments
* Changes the error thrown when timeout occurs to SDKClientError
* Ensure other error types are thrown
---------
Fixes #
**Checklist**
> fix: Adds retry to send raw transaction (#3161)

- scripts/.bump-version.js
.bump-version.js script.
The root `package.json` file now needs to be included in the `.bump-version.js` script.
Fixes #3220 
**Checklist**
> fix: Added the root package.json file to the

- packages/server/tests/acceptance/hbarLimiter.spec.ts
This PR adds e2e tests for multiple users across various tiers
Fixes #3068 
**Checklist**
> test: added e2e tests for multiple users across various tiers

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
Cherry-picked PR that fixes a cache key issue.
Fixes #3232
> feat: fix wrong cache key on `eth_getBlockByHash` (#3232)

- packages/config-service/src/services/globalConfig.ts
Restores the behavior of defaulting to true for the env var. 
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/3227
This change was originally made in https://github.com/hashgraph/hedera-json-rpc-relay/pull/2361, but seems to have been lost in https://github.com/hashgraph/hedera-json-rpc-relay/pull/3047 (more specific [at this line](https://github.com/hashgraph/hedera-json-rpc-relay/pull/3047/files#diff-e45c74081ee1bad0af083d6197bf6d533f97228588695bcd20322cca1bcaa142R77))
**Checklist**
> fix WS_NEW_HEADS_ENABLED default

- packages/ws-server/tests/acceptance/getTransactionByHash.spec.ts
Test fix. Ethereum transaction signatures v and s values need to have leading zeros stripped before being evaluated.
Fixes #3239 
Leading zeros on signature r and s values are stripped in the formatters.formatContractResult in the relay before the results are returned. On the mirror node they are stored with the leading zero. e.g.
The transaction hash `0xc5a3df675c99f634d9d81a8092fc65db54d7c28dc21126439329e92598976d2d` on testnet returns a signature s value of:
`0x091027721aff181da255f7bda0cf5b834a0d5099b46dc636b1dbd50a30e33383` from the [mirror](https://testnet.mirrornode.hedera.com/api/v1/contracts/results/0xc5a3df675c99f634d9d81a8092fc65db54d7c28dc21126439329e92598976d2d) node.
The eth_getTransactionReceipt response from …
> fix:  Strip leading zeros in signature v and s values coming from the mirror node, in tests.

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/sdkClient.spec.ts
- packages/relay/tests/lib/services/metricService/metricService.spec.ts
- Modifies EthImpl.sendRawTransaction() to poll the MN for the transaction's validity not only for transactions that were successfully submitted to the network but also in cases of Timeout and ConnectionDropped errors.
- Removes the MN instance in SDKClient.
- Fixes unit tests in eth_sendRawTransaction.spec.ts to align with the new update.
Fixes #3207
- The primary focus is on the `EthImpl.sendRawTransaction`. Please refer to the code comments for a clearer understanding of the rationale behind the changes.
- The sdkClient.ts was only modified to remove the MN instance and update a couple of log message and code comments
**Checklist**
> fix: modified sendRawTransaction to also poll MN for transaction's validity for Timeout and ConnectionDropped error

- .github/workflows/conformity-workflow.yml
- .github/workflows/dapp.yml
- .github/workflows/test.yml
This PR upgrades any leftover references from node version 18, to node version 20.  It updates github workflows and cleans up some leftover commented out code.  
Fixes #3156 
Node version 20 was already referenced in the README.md and in most of the workflows.  The conformity tests had some remaining version 18 references that were updated.
**Checklist**
> chore: Upgrade node version to 20.

- .github/release.yaml
This PR modified the .github/release.yaml to include `internal` and `github_action` labeled PRs
Fixes #3172 
**Checklist**
> fix: updated .github/release.yaml to include `internal` and `github_action` labeled PRs

- docker-compose.yml
This PR adds redis to the docker-compose so that both servers can share the cache among themselves.
Fixes #1869 
Docker Containers up & running :
Environmental variables : 
**Checklist**
> feat: added redis in docker-compose

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
Add counter for active users based on the rate limiter duration period. 
Fixes #3151 
**Checklist**
> chore: add active users counter per rate limiter duration

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
We are getting alerts on intermittent `eth_getTransactionReceipt` calls with a 500 response.  Tracing through the logs we can see that the `getBlockByHash` call is missing a valid hash, right after the call to the mirror node on the `contracts/results` endpoint.  
**Steps to reproduce**:
1. Look through the logs for an `eth_getTransactionReceipt` call with a 500 response.
2. Note the request ID and trace through the logs the path of the request.
3. Notice the call to `getBlockByHash` is missing a valid hash.
```
[34mDEBUG[39m (rpc-server/84 on mainnet-hashio-85fd789b7-twzsv): [36m[Request ID: 51841ec6-3dc9-4dad-af6a-07c4c3f01e02] Validating method parameters for eth_getTransactionReceipt, params: ["0x411f2d52652ad237296f85041e382194d3fd5a7fb006e269975dede4652b70fc"][39m" …
```
> fix: `eth_getBlockByHash` is using invalid cache record

- .github/workflows/acceptance.yml
- package.json
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/services/hbarLimitService/IHbarLimitService.ts
- packages/relay/src/lib/services/hbarLimitService/index.ts
- packages/relay/tests/lib/services/hbarLimitService/hbarLimitService.spec.ts
- packages/server/tests/acceptance/hbarLimiter.spec.ts
This fix allows the HBar Rate Limiter to be disabled by setting the `HBAR_RATE_LIMIT_TINYBAR` to `0`
Fixes #3251 
**Checklist**
> fix: Allow the HBar Rate Limiter to be disabled.

- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR adds a gas deviation to the gas price in the `@release-light` tests, and removes some warnings in the IDE.
Fixes #3259 
**Checklist**
> fix: Added gas deviation to the release-light tests.

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
Cherry pick fix: masks ip address in request details passed as argument to MN client (#3268) to release/0.60
Fixes #3268
**Checklist**
> chore: cherry pick #3268 to release/0.60

- .github/workflows/acceptance-workflow.yml
Workflow permissions should be set to 
```yaml
permissions:
contents: read
checks: write
```
Fixes #3275 
N/A
**Checklist**
> chore: update workflow permissions for github token

- docs/design/sendRawTransaction-fast-return.md
This PR introduces a design document detailing additional aspects of the new feature that allows `eth_sendRawTransaction` to immediately return the transaction hash after passing all prechecks.
More aspects and considerations of the feature are highlighted in the ongoing discussion in https://github.com/hashgraph/hedera-json-rpc-relay/issues/3202. Please feel free to share your insights in the thread if you have any.
Fixes #3281
**Checklist**
> docs: added design docs for eth_sendRawTransaction fast transaction hash return

- package-lock.json
- packages/relay/package.json
- packages/relay/src/lib/clients/sdkClient.ts
- packages/server/package.json
- packages/ws-server/package.json
The Relay server currently lacks visibility into which node account ID a transaction was submitted to when it fails due to an SDK error. With the [recent update](https://github.com/hashgraph/hedera-sdk-js/pull/2631) to the `hedera-sdk-js`, the error object now includes the node account ID for failed transactions. 
This new capability in the Relay's logging system is expected to improve troubleshooting and provide better insights into node-specific transaction failures.
**Solution**:
Update the Relay server's logging system to extract and log the node account ID from the error object provided by the SDK
Fixes #3278 
**Checklist**
> feat: expose node account id in relay logging of failed transactions

- .github/workflows/release-automation.yml
The release-automation.yml workflow uses a release notes generator action that has an equivalent maintained by StepSecurity.
This PR replaces it with the StepSecurity variant.
Fixes #3267 
N/A
**Checklist**
> ci: replace release notes generator action with one maintained by stepsecurity

- docs/openrpc.json
- packages/server/tests/acceptance/conformityTests.spec.ts
- packages/server/tests/acceptance/data/conformity-tests-batch-2.json
- updates conformity test to use relay's openrpc file for methods, which are not tested via ethereum/execution-api repo. We check if result is matching the pattern from our openrpc file;
- there were few methods which were duplicated and update of few patterns.
Fixes #2728
**Checklist**
> chore: extend the format checking via openrpcjson

- .github/scripts/codecov-upload.sh
- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
- .github/workflows/acceptance.yml
- .github/workflows/manual-testing.yml
This PR fixes the Codecov silent fails.
Fixes #3287 
Adding the -Z flag is not needed, because the "--fail-on-error" option is present.
**Checklist**
> ci: Pass CODECOV_TOKEN to acceptance workflow

- .github/workflows/manual-testing.yml
Fixes breaking change in manual-testing.yaml where websocket was split into three batches but the batches were not included in the publish-results needs clause.
Fixes #3306
**Notes for Reviewer**:
> fix: Add websocket-batch-n to needs clause in manual-testing

- packages/relay/src/lib/services/ethService/ethFilterService/index.ts
During debugging of #3030 an inconsistency was found where we automatically refresh the TTL for our filter cache entries for `getFilterChanges` but not for `getFilterLogs`. This PR solves this inconsistency.
#3030
Fixes #3311 
**Checklist**
> fix: added cache refreshing after subsequent getFilterLogs calls for the same filter

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth/eth_estimateGas.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
This PR fixes the case where transactions with a value of 0 would not pass. This is needed because they would pass as valid transactions on the Ethereum network as 0 is a valid value there.
Fixes #3105 
**Checklist**
> fix: let 0 value transactions pass

- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/utils.ts
- packages/server/tests/acceptance/htsPrecompile/precompileCalls.spec.ts
- Added `getContractAddressFromReceipt` method to:
- Detect if a transaction is a token creation call to the HTS system contract by checking function selectors
- Extract the token's EVM address from the call result for HTS token creation transactions
- Return the appropriate contract address in the transaction receipt
- The method checks if the transaction's function selector matches any of the HTS token creation methods defined in `HTS_CREATE_FUNCTIONS_SELECTORS`
- For HTS token creations, extracts the token address from the call_result a.k.a the method response
- For regular contract deployments, returns the original contract address
This change improves compatibility with Ethereum tooling by ensuring that token creation transactions return the correct token address in …
> feat: return hts token address for new fungible token

- .eslintrc.js
- package-lock.json
- package.json
Added a new package eslint-plugin-header that implements a rule to check the presence of a particular header. 
The rule allow for the usage of regex for certain parts of the header. In our case I have added a regex for the line containing dates.
The regex will work for strings with a single date:
```
* Copyright (C) 2024 Hedera Hashgraph, LLC
```
or a dates defining some period
```
* Copyright (C) 2022-2024 Hedera Hashgraph, LLC
```
Fixes #3192 
**Checklist**
> chore: Adds check for license header

- packages/relay/src/lib/eth.ts
Changed method getContractAddressFromReceipt to align with design doc and be more clear
The reason we substring the last 40 characters is the fact that the last 20 bytes are the returned tokenAddress as a response
Fixes #3322 
**Checklist**
> fix: improves getContractAddressFromReceipt

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/eth/eth_sendRawTransaction.spec.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
Added precheck for receiver's account in sendRawTransactionCheck
Fixes #3286
> chore: add precheck for receivers account in sendRawTransactionCheck

- docs/design/hbar-limiter.md
**Description:**
This PR updates the `bar-limiter.md` doc with information and diagrams about how the total spending limit is managed through the `OPERATOR` spending plan.
Fixes #3099
> docs: update `hbar-limiter.md` with information about `OPERATOR` plans

- .github/workflows/release-automation.yml
This PR modifies the release automation script to include additional necessary information in the SNAPSHOT bump PR.
Fixes #3356
**Checklist**
> chore: updated release-automation script to add more information to SNAPSHOT PR

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/debugService/index.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/src/receiptsRootUtils.ts
- packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
Numerous requests for `eth_getBlockByNumber` and `eth_getBlockByHash` have been reported as failing with errors such as `Cannot read properties of null` and `Received an invalid integer type: null`. 
Additionally, `eth_getTransactionReceipt` is also reported to be failing with `Error invoking RPC: Invalid parameter: hashOrNumber`.
These issues stem from regressions in the `getBlock()` method, which lacks adequate null checks in certain areas. This pull request addresses the problem by implementing proper null checks and enhancing fallback mechanisms and error handling.
Partially, the results of contracts and log responses from the Mirror Node occasionally contain undefined fields, such as transaction_index, block_hash, block_number, and log_index. This issue may arise …
> fix: enhanced reliability of eth RPC methods with null checks and retry mechanisms

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/debugService/index.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/src/receiptsRootUtils.ts
- packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR cherry-picks [#3349: Fix: Enhanced reliability of ETH RPC methods with null checks and retry mechanisms](https://github.com/hashgraph/hedera-json-rpc-relay/pull/3349) into release/0.63.
Fixes #3345 
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/3351
**Checklist**
> chore: cherry pick #3349 - fix: enhanced reliability of eth RPC methods with null checks and retry mechanisms to release/0.63

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
This PR enhances the retry mechanisms in getContractResultWithRetry() and getContractResultsLogsWithRetry() by adding polling logic to ensure the retrieval of fully mature records. Additionally, the Relay now implements strict error handling to throw exceptions when immature records are encountered. This approach aims to prevent the `Cannot read properties of null (reading 'xyz')` error caused by improper handling of null checks.
Fixes #3366 
**Checklist**
> fix: added polling logic to ensure the retrieval of fully mature records from MN

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
This PR cherry-picks [#3368 fix: added polling logic to ensure the retrieval of fully mature records from MN](https://github.com/hashgraph/hedera-json-rpc-relay/pull/3368) into release/0.63
Fixes #3366 
**Checklist**
> chore: cherry pick #3368 fix: added polling logic to ensure the retrieval of fully mature records from MN

- tools/blockscout-example/README.md
Example project for hedera-blockscout project deployment.
Fixes #3393 
**Checklist**
> chore: blockscout example project

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
This PR introduces a new predefined error, DEPENDENT_SERVICE_IMMATURE_RECORDS, with the JSON-RPC code `-32015`, mapped to the HTTP status code `503`. This improves error handling for cases where the dependent Mirror Node service returns immature records.
- `-32015`: Chosen as it fits within the JSON-RPC application-defined server error range (-32000 to -32099) and avoids conflicts with existing error codes.
- `HTTP 503`: Represents a temporary unavailability of a dependent service, signaling clients to retry.
Fixes #3392 
**Checklist**
> feat: added DEPENDENT_SERVICE_IMMATURE_RECORDS predefined error for immature records scenarios

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/tests/lib/eth/eth_getBlockByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getBlockByNumber.spec.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionByHash.spec.ts
- packages/relay/tests/lib/eth/eth_getTransactionReceipt.spec.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/src/koaJsonRpc/lib/HttpStatusCodeAndMessage.ts
This PR cherry picks [feat: added DEPENDENT_SERVICE_IMMATURE_RECORDS predefined error for immature records scenarios](https://github.com/hashgraph/hedera-json-rpc-relay/issues/3392) into release/0.64
Fixes https://github.com/hashgraph/hedera-json-rpc-relay/issues/3392
**Checklist**
> chore: cherry pick feat: added DEPENDENT_SERVICE_IMMATURE_RECORDS predefined error for immature records scenarios (#3394)

- packages/relay/src/lib/clients/mirrorNodeClient.ts
This PR enhances logging in the Relay to provide more detailed information when receiving responses from the Mirror Node server. The improved logs include critical context about the Mirror Node call and error-specific details to assist in debugging issues.
Fixes #3421 
**Checklist**
> chore(logging): enhanced logging upon receiving responses from the Mirror Node server

- packages/relay/src/lib/clients/mirrorNodeClient.ts
This PR cherry picked #3422 to release/0.64
Fixes #3421 
**Checklist**
> chore: cherry pick PR#3422 feat(logging): enhanced logging upon receiving responses from the Mirror Node server (#3422) to release/0.64

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/src/lib/services/ethService/ethFilterService/index.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/services/eth/filter.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This pull request improves the eth_getLogs functionality by:
- Introducing a new error: TIMESTAMP_RANGE_TOO_LARGE for handling large timestamp ranges.
- Adding validation to ensure the timestamp range between fromBlock and toBlock is within acceptable limits, 7 days (604800 seconds). (Fixes #3428)
- Ensuring eth_getLogs gracefully handles cases where toBlock is not provided. Without toBlock, the `params.lte` field is omitted, leading to request rejected by MN. To address this, the function now returns an empty response to the client. (Fixes #3430)
Tests and comments have been added to support and clarify these changes.
Fixes #3428
**Checklist**
> feat: enhanced eth_getLogs with timestamp range validation and new error handling

- packages/relay/src/lib/errors/JsonRpcError.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/ethService/ethCommonService/index.ts
- packages/relay/src/lib/services/ethService/ethFilterService/index.ts
- packages/relay/tests/lib/eth/eth_getLogs.spec.ts
- packages/relay/tests/lib/services/eth/filter.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
Cherry pick #3431 to release/0.64
> This pull request improves the eth_getLogs functionality by:
> - Introducing a new error: TIMESTAMP_RANGE_TOO_LARGE for handling large timestamp ranges.
> - Adding validation to ensure the timestamp range between fromBlock and toBlock is within acceptable limits, 7 days (604800 seconds). (Fixes #3428)
> - Ensuring eth_getLogs gracefully handles cases where toBlock is not provided. Without toBlock, the `params.lte` field is omitted, leading to request rejected by MN. To address this, the function now returns an empty response to the client. (Fixes #3430)
>
> Tests and comments have been added to support and clarify these changes.
Fixes #3428
**Checklist**
> chore: cherry pick feat: enhanced eth_getLogs with timestamp range validation and new error handling (#3431) to release/0.64

- package-lock.json
- packages/relay/package.json
- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/clients/servicesClient.ts
It seems like `eth_getBlockByNumber` fails because one of the transactions in the block was a CONTRACT_NEGATIVE_VALUE failure. The expectation is for the block to be successfully returned.
**Steps to reproduce**:
1. call `eth_getBlockByNumber` on block [73298898](https://hashscan.io/mainnet/block/73298898)
2. see "Error invoking RPC: Invalid value - cannot pass negative number" response
The problematic transaction is [here](https://hashscan.io/mainnet/transaction/1735241436.856862230)
Fixes #3367 
**Checklist**
> feat: transaction with `CONTRACT_NEGATIVE_VALUE` breaks some routes

- .github/workflows/acceptance-workflow.yml
- .github/workflows/test.yml
- package-lock.json
- packages/relay/package.json
- packages/relay/src/formatters.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/formatters.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/clients/servicesClient.ts
cherry pick feat: transaction with CONTRACT_NEGATIVE_VALUE breaks some routes (#3387) to release/0.64 #3436
Fixes #3367
**Checklist**
> chore: cherry pick feat: transaction with CONTRACT_NEGATIVE_VALUE breaks some routes (#3387) to release/0.64 

- packages/ws-server/tests/acceptance/getLogs.spec.ts
This PR equipps a more appropriate block range for eth_getLogs WS release test
Fixes #3451 
**Checklist**
> fix(test): equipped a more appropriate block range for eth_getLogs WS release test

- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR fixes the BigInt type mismatch in the eth_sendRawTransaction precheck. It also adds unit and acceptance tests to ensure the precheck handles null values for gasPrice, maxFeePerGas, and maxPriorityFeePerGas gracefully.
Fixes #3461 
**Checklist**
> fix: Resolve BigInt type mismatch in eth_sendRawTransaction precheck

- packages/relay/src/lib/precheck.ts
- packages/relay/tests/lib/precheck.spec.ts
- packages/server/tests/acceptance/rpc_batch1.spec.ts
cherry pick fix: Resolve BigInt type mismatch in eth_sendRawTransaction precheck (#3463) to release/0.65
Fixes #3461
**Checklist**
> chore: cherry pick fix: Resolve BigInt type mismatch in eth_sendRawTransaction precheck (#3463) to release/0.65

- charts/hedera-json-rpc/dashboards/hedera-json-rpc-relay-http-server.json
This PR modifies the latest Grafana dashboard JSON file to add more panels for better tracking Ethereum RPC Execution methods (eth_call & eth_sendRawTransaction). This new section is under the row `Ethereum RPC Methods`.
This update also aims to improve metrics in preparation for ticket https://github.com/hashgraph/hedera-json-rpc-relay/issues/3122.
Fixes #3458 
**New Items**:
a. Average Latency 
b. Average RPS
c1. Total Requests Count
c2. Total Failed Requests Count
c3. Failed Rate Percentage
d1. Failed eth_call Requests By Status Code
d2. Failed eth_sendRawTransaction Requests by Status Code
**Checklist**
> chore: updated grafana dashboard for better visibility on Ethereum RPC Execution Methods

- .github/release-notes.yml
- .github/workflows/release-automation.yml
This PR:
- Modified release-automation.yml to ensure the job closes the milestone after a GA version is cut and fixed the dependent step, Create Release Notes, by setting the correct variable, steps.milestone.outputs.milestone_id, so it runs as expected.
- Renamed .github/release.yml to .github/release-notes.yml to align with the [release-notes-generator](https://github.com/marketplace/actions/release-notes-generator#section-configuration) documentation.
- Exposed the milestone from the branch_bump_tag step to attach it to the SNAPSHOT PR.
Fixes #1904
**Checklist**
> fix: fixed CI release automation to create release notes automatically

- docs/openrpc.json
- docs/rate-limiting.md
- packages/relay/src/index.ts
- packages/relay/src/lib/web3.ts
- packages/relay/tests/lib/openrpc.spec.ts
- packages/relay/tests/lib/web3.spec.ts
- packages/server/src/koaJsonRpc/lib/methodConfiguration.ts
- packages/server/src/server.ts
- packages/server/src/validator/methods.ts
- packages/server/tests/acceptance/data/conformity-tests-batch-3.json
- packages/server/tests/helpers/constants.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/postman.json
- packages/ws-server/src/utils/constants.ts
Add support for `web3_sha3`.
**Action plan**:
- add new route definition into server.ts
- add web3_sha3 definition into validator/methods.ts making the first parameter (input) required
- append the newly created method to tier3rateLimit (like web3_clientVersion) via methodConfiguration.ts
- add web3_sha3 to the web3 interface
- add the implementation within web3.ts which will create keccak256 of the input
- add tests
- add documentation
Fixes #3484 
**Checklist**
> feat: add `web3_sha3` support

- .github/scripts/check-pr.js
- .github/snyk_pull_request_template.yaml
Snyk PR titles now automatically add proper conventional type prefixes and appropriate labels. 
Fixes #3319 
Judging from the closed PR's by Snyk, I have made the assumption that they would always start with [Snyk] in their title and that they would all be a version upgrade or a security upgrade. 
**Checklist**
> feat: adds proper structure to automatic bumping PRs

- packages/relay/src/lib/services/hbarLimitService/index.ts
This PR adds a new gauge metric to track the total configured HBAR rate limit in the HbarLimitService.
Fixes #3542
**Checklist**
> chore: add total HBAR rate limit gauge metric for monitoring

- packages/config-service/src/services/globalConfig.ts
- packages/config-service/src/services/validationService.ts
- packages/config-service/tests/src/services/validationService.spec.ts
- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/src/utils.ts
- packages/relay/tests/lib/eth/eth_call.spec.ts
- packages/relay/tests/lib/hapiService.spec.ts
- packages/relay/tests/lib/utils.spec.ts
- packages/server/src/koaJsonRpc/index.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
- packages/ws-server/src/webSocketServer.ts
- packages/ws-server/tests/acceptance/batchRequest.spec.ts
This PR adds support for array type environment variables in the Hedera JSON RPC Relay configuration system. Previously, array-type environment variables were stored as strings and had to be explicitly parsed with JSON.parse() on each usage. This implementation provides a more type-safe approach .
Fixes #3178 
**Checklist**
> feat: adds support for arrays in ConfigService

- packages/server/tests/acceptance/rpc_batch1.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
The beforeAll() block in the eth_getCode suite is timing out.
By optimizing the hook in the RPC API batch 2 and removing unnecessary and expensive calls, and then rerunning the job multiple times - now it fails much less often.
Fixes partially #3353 
**Checklist**
> fix: fixes flaky CI tests in RPC Batch 2

- .github/CODEOWNERS
- .github/workflows/acceptance-public.yml
- .github/workflows/acceptance-workflow.yml
- .github/workflows/acceptance.yml
- .github/workflows/charts.yml
- .github/workflows/conformity-workflow.yml
- .github/workflows/dapp.yml
- .github/workflows/dev-tool-workflow.yml
- .github/workflows/flow-pr-title-check.yml
- .github/workflows/foundry.yml
- .github/workflows/image-build.yml
- .github/workflows/manual-testing.yml
- .github/workflows/postman.yml
- .github/workflows/pr-label-milestone-check.yml
- .github/workflows/release-acceptance.yml
- .github/workflows/release-automation.yml
- .github/workflows/release-integration.yml
- .github/workflows/release-production.yml
- .github/workflows/subgraph.yml
- .github/workflows/test.yml
- Update the CODEOWNERS file to use the `hiero-ledger` organization teams
- Update actions to use the `hiero-ledger` runners
Fixes #3560
> chore: update runners and codeowners to use hiero runners and teams

- .github/workflows/gh-pages-sync.yaml
Adds the gh-pages-sync.yaml workflow to sync the public hiero-ledger/hiero-json-rpc-relay repository and the private hashgraph/hedera-json-rpc-relay.
Fixes #3577
> ci: Add gh-pages-sync workflow to json-rpc-relay

- charts/hedera-json-rpc-relay-websocket/Chart.yaml
- charts/hedera-json-rpc-relay-websocket/values.yaml
- charts/hedera-json-rpc-relay/Chart.yaml
- charts/hedera-json-rpc-relay/templates/cronjob.yaml
- charts/hedera-json-rpc-relay/value-test.yaml
- charts/hedera-json-rpc-relay/values.yaml
- charts/hedera-json-rpc/Chart.yaml
This PR updates the links in the charts directory to point to the new repo home URL.
Fixes #3582 
**Checklist**
> fix: change urls to repo in charts directory

- charts/hedera-json-rpc-relay/postman.json
- packages/relay/src/lib/net.ts
- packages/relay/tests/lib/net.spec.ts
- packages/server/src/routes/netRoutes.ts
- packages/server/tests/acceptance/data/conformity-tests-batch-3.json
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/integration/server.spec.ts
- packages/server/tests/postman.json
This PR updates `net_listening` to return a boolean `true` instead of the previous string `'false'`. It also updates all test coverage to align with the new logic.
Fixes #3590
**Checklist**
> fix: fixed net_listening to return boolean `true`

- tools/layer-zero-example/contracts/HTSConnector.sol
There is no check for the max int64 amount value in `_debit` and `_credit` in the HTSConnector contract.
Fixes #3597 
The task is requested after the contract audit.
**Checklist**
> feat: add an addition check on the `HTSConnector` contract under the `layer-zero` example

- .github/workflows/release-automation.yml
Add `--gpg-sign` to the commit options in release workflow commit-and-tag step
Fixes #3603
> ci: Add GPG sign-off to commit options

- .github/workflows/charts.yml
- .github/workflows/image-build.yml
- .github/workflows/release-integration.yml
- .github/workflows/release-production.yml
- Dockerfile
This PR cherry picks the following PRs onto `67` release branch to fix the Docker build image workflows
- https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/3625
- https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/3628
Fixes #3629 onto `0.67` release.
**Checklist**
> chore: cherry pick to fix Docker build image workflows

- k6/README.md
- k6/src/prepare/prep.js
- k6/src/scenarios/test/index.js
This PR fixes some issues found when running release `0.67` tests. In particular
- Fix `npm run prep` script on Node 23.
- Fix broken link in `README`.
- Remove `web3_client_version` test module.
Fixes #3642.
Fixes #3643.
Fixes #3644.
**Checklist**
> chore: fix k6 issues found when running release `0.67` tests

- package-lock.json
- package.json
- tools/hardhat-example/package-lock.json
- tools/hardhat-example/package.json
- tools/hardhat-viem-example/package-lock.json
- tools/hardhat-viem-example/package.json
- tools/layer-zero-example/package-lock.json
- tools/layer-zero-example/package.json
- tools/solidity-coverage-example/package-lock.json
- tools/solidity-coverage-example/package.json
- tools/subgraph-example/package-lock.json
- tools/subgraph-example/package.json
- tools/waffle-example/package-lock.json
- tools/waffle-example/package.json
- bump elliptic to v6.6.1 in package.json  
- bump elliptic to v6.6.1 in tools/waffle-example  
- bump elliptic to v6.6.1 in tools/hardhat-example  
- bump elliptic to v6.6.1 in tools/hardhat-viem-example  
- bump elliptic to v6.6.1 in tools/layer-zero-example  
- bump elliptic to v6.6.1 in tools/solidity-coverage-example  
- bump elliptic to v6.6.1 in tools/subgraph-example  
**Related issue(s)**:  #3673
> build(deps): bump elliptic to v6.6.1 for example tools

- tools/hardhat-viem-example/package-lock.json
- tools/layer-zero-example/package-lock.json
- tools/layer-zero-example/package.json
- tools/subgraph-example/package-lock.json
- tools/subgraph-example/package.json
- tools/whbar-hardhat-example/package-lock.json
- bump axios to 1.8.4 in tools/whbar-hardhat-example
- bump axios to 1.8.4 in tools/layer-zero-example
- bump axios to 1.8.4 in tools/hardhat-viem-example
- bump axios to 1.8.4 in tools/subgraph-example
**Related issue(s)**: #3673
> build(deps): bump axios to 1.8.4 in tools/whbar-hardhat-example

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/src/lib/constants.ts
- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/eth/eth_getCode.spec.ts
- packages/server/tests/acceptance/erc20.spec.ts
- packages/server/tests/acceptance/rpc_batch2.spec.ts
- packages/server/tests/helpers/utils.ts
This PR adds preliminary support for non-zero shard/realm numbers. As described in #3614, it was mostly related to `eth_getCode` and the redirect bytecode. This was refactored to avoid duplication.
In addition it now includes `0x` hex prefix in the HTS redirect bytecode. The spec indicated that `eth_getCode` result response should be a hex encoded value starting with `0x`.
Fixes #3614
**Checklist**
> feat: support non-zero shard/realm

- packages/relay/src/lib/eth.ts
- packages/relay/tests/lib/ethGetBlockBy.spec.ts
This PR fixes a problem in the `getBlock()` method which caused duplicate transactions to be returned. 
The old code `transactionArray = showDetails ? transactionArray : _.uniq(transactionArray);` didn't account for the situation where duplicate transaction could be returned in some cases where one transaction emits multiple events (e.g. minting multiple NFT serials in one transaction). In that case, duplicate transactions would be generated from the logs. I have changed this line to account for that and exclude duplicates.
Fixes #3724
**Checklist**
> fix: fixes check to remove duplicates from transactionArray

- packages/relay/src/lib/debug.ts
- packages/relay/src/lib/types/debug.ts
- packages/relay/tests/lib/debug.spec.ts
This PR allows callTracer to return an empty array if no call actions are found, effectively preventing the deconstruction of an undefined object.
Fixes #3751
**Checklist**
> fix: allowed callTracer to return empty array if no call actions found

- tools/hardhat-example/test/rpc.js
- tools/web3js-example/test/rpc.js
For the eth_call method, the response is defined as follows:
```typescript
return contractCallResponse?.result ? prepend0x(contractCallResponse.result) : EthImpl.emptyHex;
```
This indicates that if contractCallResponse.result is not present, the method returns emptyHex, which is "0x".
There is a concern that returning "0x" might impact the decoding logic of some tools, such as Ethers.js, which may not expect an empty hex string in this context.
- The /contracts/call endpoint from the Mirror Node returns "0x" when no result is found.
```bash
> curl -X 'POST' \
'https://testnet.mirrornode.hedera.com/api/v1/contracts/call' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"data": "0x",
"to": "0x00000000000000000000000000000000002e7a5d"
}'
> {"result": "0x"}
```
- …
> chore: add proof handling for empty hex responses in web3.js and ethers.js without exceptions

- tools/whbar-hardhat-example/package-lock.json
- tools/whbar-hardhat-example/package.json
PR https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/3767/files accidentally decreased the sdk package to 2.59. This PR restored back the version, also fixed 1 package vulneriblty using npm audit.
Fixes https://github.com/hiero-ledger/hiero-json-rpc-relay/issues/3827
**Checklist**
> build(deps): restored sdk version and fixed package vuls in whbar-hardhat-exampl

- packages/relay/src/lib/services/ethService/blockService/BlockService.ts
This PR removes `getBlockReceipts`' custom cache logic leftover from https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/3758/files#r2098146076.
Fixes #3778.
**Checklist**
> fix: remove custom cache logic from `getBlockReceipts`

- README.md
- charts/hedera-json-rpc-relay-websocket/Chart.yaml
- charts/hedera-json-rpc-relay/Chart.yaml
- charts/hedera-json-rpc/Chart.yaml
- docs/openrpc.json
- package-lock.json
- package.json
- packages/config-service/package.json
- packages/relay/package.json
- packages/server/package.json
- packages/ws-server/package.json
Bump versions for v0.70.0-SNAPSHOT
Automated snapshot version bump for the next development cycle.
Fixes: https://github.com/hiero-ledger/hiero-json-rpc-relay/issues/3844
> chore(release): Bump versions for v0.70.0-SNAPSHOT

- packages/server/src/server.ts
- packages/server/tests/integration/proxyHeaders.spec.ts
- packages/server/tests/integration/server.spec.ts
This PR enables proxy support to trust proxy-added headers for client IP detection
should fix #3783
> feat: enables proxy support

- packages/relay/src/lib/clients/mirrorNodeClient.ts
- packages/relay/tests/lib/mirrorNodeClient.spec.ts
- packages/server/src/server.ts
- packages/server/tests/integration/proxyHeaders.spec.ts
With app.proxy enabled, we already parse X-Forwarded-For headers correctly. Custom parsing for Forwarded headers has been added, along with passing a Forwarded header with the original client IP to the mirror node (if present). All of this was included in the tests coverage
Fixes #3772
> feat: adds Forwarded header to downstream MN requests + custom parsing for Forwarded headers

- packages/relay/src/lib/validators/index.ts
- packages/relay/tests/lib/dispatcher/rpcMethodDispatcher.spec.ts
- packages/relay/tests/lib/validators/validators.spec.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
- packages/ws-server/tests/helper/index.ts
Some RPC endpoints, like eth_getBalance, do not validate the parameters array length properly. This can lead to a "500 Internal Server Error" when it should have been a 400 error instead.
**Solution**:
Ensure `params` array length is less or equal to `indexes` length [here](https://github.com/hiero-ledger/hiero-json-rpc-relay/blob/8ff3d144fe6bbee268f1d7cf5db74cd5225ff5de/packages/relay/src/lib/validators/index.ts#L7) and throw `INVALID_PARAMETERS` if needed.
**Affected JSON-RPC Methods**:
This issue affects the RPC endpoints that do not use a parameters layout, i.e., `RPC_LAYOUT.custom` nor `RPC_LAYOUT.REQUEST_DETAILS_ONLY`, and logs `requestDetails.formattedRequestId`. These are:
- eth_newFilter
- eth_getFilterLogs
- eth_getFilterChanges
- eth_uninstallFilter
- …
> feat: ensure rpc params array length according to rpc definitions

- charts/hedera-json-rpc-relay-websocket/ci/default-values.yaml
- charts/hedera-json-rpc-relay/ci/default-values.yaml
- charts/hedera-json-rpc/ci/default-values.yaml
This PR fixes the chart test workflow by setting the `READ_ONLY` flag. In Read-Only mode, both `OPERATOR_ID_MAIN` and `OPERATOR_KEY_MAIN` values are not checked at the start of the Relay/WebSocket.
Fixes #3931.
**Checklist**
> fix: charts install workflow after introducing Read-Only mode

- charts/hedera-json-rpc-relay-websocket/templates/configmap.yaml
The `HEDERA_NETWORK` value has special treatment because it can be a JSON string. By default, Helm treats { and } as a list[1](https://github.com/orgs/hashgraph/projects/15/views/5?sliceBy%5Bvalue%5D=natanasow&pane=issue&itemId=119371589&issue=hiero-ledger%7Chiero-json-rpc-relay%7C3921#user-content-fn-1-b3af5f22b487c1b1bedcf7321d1eec07) instead of leaving it as is. The fix was introduced here https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/2498. However, this change was not applied in the WS chart, leading to the difference.
Fixes #3921
**Checklist**
> feat: unify treatment of HEDERA_NETWORK value in Relay and WS charts

- .github/pull_request_template.md
This PR adds a .github/pull_request_template.md file to override improve the default pull request template used at the Hiero organization level [here](https://github.com/hiero-ledger/.github/blob/main/PULL_REQUEST_TEMPLATE.md?plain=1). 
The updated template aims to enhance clarity, usability, and reviewer effectiveness by addressing vague PR submissions and setting clearer expectations for contributors.
Key updates:
- Added starter prompt to description section
- Replaced vague notes section with specific guidance for testing and design changes
- Introduced optional section for technical debt and future work
- Updated checklist to reflect completed tasks
- Enhanced issue linking guidance with context and expectations
Fixes #3903 
1. Review the changes in .github/pull_request_template.md …
> chore: improve pull request template for clarity and review effectiveness

- packages/server/src/koaJsonRpc/index.ts
- packages/server/src/koaJsonRpc/lib/RpcError.ts
- packages/server/tests/integration/koaJsonRpc/rpcError.spec.ts
- packages/ws-server/src/controllers/jsonRpcController.ts
This PR correctly displays the root error message when an `InternalError` is returned.
Fixes #3949.
**Checklist**
> fix: displayed error message for `InternalError`

- k6/src/prepare/prep.js
- k6/src/scenarios/test/debug_traceBlockByNumber.js
- k6/src/scenarios/test/debug_traceTransaction.js
- k6/src/scenarios/test/eth_blobBaseFee.js
- k6/src/scenarios/test/eth_createAccessList.js
- k6/src/scenarios/test/eth_getFilterChanges.js
- k6/src/scenarios/test/eth_getFilterLogs.js
- k6/src/scenarios/test/eth_getProof.js
- k6/src/scenarios/test/eth_maxPriorityFeePerGas.js
- k6/src/scenarios/test/eth_newBlockFilter.js
- k6/src/scenarios/test/eth_newFilter.js
- k6/src/scenarios/test/eth_newPendingTransactionFilter.js
- k6/src/scenarios/test/eth_uninstallFilter.js
- k6/src/scenarios/test/index.js
- k6/src/scenarios/test/net_peerCount.js
- k6/src/scenarios/test/web3_sha3.js
This PR addresses the test coverage gap by implementing K6 performance tests for the **14 missing JSON-RPC endpoints** in the Hedera JSON RPC Relay test suite.
- eth_blobBaseFee
- eth_maxPriorityFeePerGas
- eth_newBlockFilter
- eth_newFilter
- eth_uninstallFilter
- eth_newPendingTransactionFilter
- eth_getFilterLogs
- eth_getFilterChanges
- net_peerCount
- web3_sha3
- debug_traceTransaction
- debug_traceBlockByNumber
- eth_getProof
- eth_createAccessList
Fixes #3966 
1. Spin up local-node network. Stop the relay instance from the local-node network, then run a new Relay instance from this project, remember to set `RATE_LIMIT_DISABLED` to `true` to disable IP rate limiting.
2. Use this .env file
```
PRIVATE_KEY=0x105d050185ccb907fba04dd92d8de9e32c18305e097ab41dadda21489a211524 …
```
> feat: increased k6 coverage for all RPC endpoints

- packages/relay/src/lib/services/hapiService/hapiService.ts
- packages/relay/tests/lib/hapiService.spec.ts
The rpc_relay_client_service metric currently includes a duration label that is unnecessary and contributes to increased metric cardinality.
Closes #4084
1. Verify duration has been removed in the code everywhere `rpc_relay_client_service` is referenced.
2. Once merged, verify through the dashboard
I got a warning that we still pass cacheService to the HAPIService inside the tests, so I've decided to remove it. This doesn't affect the tests and functionality.
N/A
> feat: removes duration from rpc_relay_client_service metric

- charts/hedera-json-rpc/dashboards/webSocketServer.json
- packages/ws-server/src/metrics/wsMetricRegistry.ts
- packages/ws-server/src/utils/constants.ts
- packages/ws-server/tests/unit/wsMetricRegistry.spec.ts
We used to rely on custom calculations, which may not be 100% accurate, to follow the CPU and Memory Usage of the WebSocket server.
Instead of having a custom collect function, we can use the process_cpu_seconds_total default metric for cpu and process_resident_memory_bytes for memory together with a rate function to get the percentage usage of cpu and memory.
This PR replaces custom gauges with existing default metrics (already enabled via collectDefaultMetrics()):
Fixes #3935
1. Verify custom gauges have been removed from `wsMetricRegistry.ts`
2. Verify CPU/Memory gauge definitions have been removed from `constants.ts`
3. Once merged, verify the Grafana dashboard has been updated
N/A
N/A
> feat: removes custom CPU and Memory usage Gauge

- package-lock.json
- package.json
- packages/ws-server/tests/unit/utils.spec.ts
This PR manually updates prom-client to newer major version - 15. 
It also updates unit tests, since in the new version some methods are actually instance objects, not prorotype
Fixes #4185 
1.
2.
3.
Changes in unit testing had to be done, since some of the functions of the prom-client objects e.g Counter and Histogram, were now change to be instance properties, so when stubbing them they wont actually exist (since you are not creating an instance)
https://github.com/hiero-ledger/hiero-json-rpc-relay/pull/4219/files#diff-680694a70a29a291f93442348a6ec8cdb70c6e6c6f5abfc2c51f4fd84e593e95R140
N/A
> chore: updates prom-client to new major version

- packages/relay/src/lib/clients/sdkClient.ts
- packages/relay/tests/lib/sdkClient.spec.ts
In `packages/relay/src/lib/clients/sdkClient.ts`, the `executeTransaction` method has inconsistent error handling when `!transactionResponse`. Currently:
- For "Connection Dropped" or "timeout exceeded" errors: throws `sdkClientError` (preserving original error details)
- For all other SDK errors: throws `INTERNAL_ERROR` with a generic message that doesn't include the original error details
This obfuscates the real reason for failure from the network, making debugging more difficult.
Always throw `sdkClientError` when `!transactionResponse`, so that specific error details (status, message, transactionId, nodeAccountId) are preserved and can reach the client for better debugging.
```typescript
if (!transactionResponse) {
throw sdkClientError;
}
```
- Better error reporting to clients
- …
> feat: improve error handling in SDKClient.executeTransaction to preserve original error details

- packages/ws-server/src/webSocketServer.ts
WebSocket Request ID stays the same for multiple requests within the Connection ID.
For example, the following logs were obtained first connecting to the WebSocket, then making two requests (`eth_chainId` in this case) and finally disconnecting
```txt
INFO: [Connection ID: 0x77a0021d80263409155d8b45116d9283] [Request ID: 9695871f-59f8-4acd-a528-be1716e3e135] New connection established. Current active connections: 1
TRACE: [Connection ID: 0x77a0021d80263409155d8b45116d9283] [Request ID: 9695871f-59f8-4acd-a528-be1716e3e135]: Receive single request={"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[]}
TRACE: [Connection ID: 0x77a0021d80263409155d8b45116d9283] [Request ID: 9695871f-59f8-4acd-a528-be1716e3e135]: Submitting request={"jsonrpc":"2.0","id":1,"method":"eth_chainId","params":[ …
```
> feat: use a different RequestID for each ws request within a single connection

- packages/relay/src/lib/eth.ts
- packages/relay/src/lib/validators/types.ts
- packages/server/tests/acceptance/rpc_batch3.spec.ts
Adds support for the optional `stateOverride` parameter to the `eth_call` JSON-RPC method to maintain compatibility with client tools.
Fixes #4417
> feat: add optional stateOverride parameter validation to eth_call

- packages/server/tests/acceptance/rpc_batch1.spec.ts
This PR adds negative test coverage for HBAR transfer edge cases specific to Hedera behavior via eth_sendRawTransaction. The tests verify expected Hedera-specific reverts for:
- Sending HBARs to the zero address → expect INVALID_SOLIDITY_ADDRESS
- Sending HBARs to a long zero address below 359 (e.g., id = 100) → expect INVALID_CONTRACT_ID
- Sending HBARs to a non-existing long zero address between 750–1000 (e.g., id = 850) → expect INVALID_ALIAS_KEY
- Updated contract deployment fee assertion test for [HIP-1249](https://hips.hedera.com/hip/hip-1249) compatibility (eliminates 80% minimum charge rule). This feature was recently merged to HEAD of consensus main in this PR https://github.com/hiero-ledger/hiero-consensus-node/pull/20703.
New tests are added to the acceptance suite and XTS test …
> fix: extend xts suite with new coverage for HBAR transfers to zero address and reserved system accounts
